/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\nim-0.17.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim-0.17.2\lib -o c:\webdev\dmlauto\nim\nimpy\nimcache\mymodule.o c:\webdev\dmlauto\nim\nimpy\nimcache\mymodule.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <windows.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_PyValue_qMsYTE5XbTEsC6nUXDb5DQ tyObject_PyValue_qMsYTE5XbTEsC6nUXDb5DQ;
typedef struct tyObject_Py_buffer_nRhjorz1m8nM8MZqKMfgRA tyObject_Py_buffer_nRhjorz1m8nM8MZqKMfgRA;
typedef struct tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA;
typedef struct tySequence_QIbr9abHr63pwRbRpKuoFFQ tySequence_QIbr9abHr63pwRbRpKuoFFQ;
typedef struct tySequence_1Ib9a4sxiw4YCYbDTADLEsg tySequence_1Ib9a4sxiw4YCYbDTADLEsg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg;
typedef struct tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA;
typedef struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q tyTuple_wpFMp8IwxV6MlaM4GANJ0Q;
typedef struct tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA;
typedef struct tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg;
typedef struct tySequence_m5LAl09cqBl9bzwvVnw9aEKrg tySequence_m5LAl09cqBl9bzwvVnw9aEKrg;
typedef struct tyObject_PyObjectVarHeadObj_E71nKnjQiXK69aSURXxI79cA tyObject_PyObjectVarHeadObj_E71nKnjQiXK69aSURXxI79cA;
typedef struct tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA;
typedef struct tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef size_t tyArray_5yb7pTez09b829cCwHJP2deg[2];
struct tyObject_Py_buffer_nRhjorz1m8nM8MZqKMfgRA {
void* buf;
void* obj;
size_t len;
size_t itemsize;
int readonly;
int ndim;
NCSTRING format;
size_t* shape;
size_t* strides;
size_t* suboffsets;
tyArray_5yb7pTez09b829cCwHJP2deg smalltable;
void* internal;
};
struct tyObject_PyValue_qMsYTE5XbTEsC6nUXDb5DQ {
tyObject_Py_buffer_nRhjorz1m8nM8MZqKMfgRA buf;
};
struct tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA {
NCSTRING name;
NCSTRING doc;
tySequence_QIbr9abHr63pwRbRpKuoFFQ* methods;
tySequence_1Ib9a4sxiw4YCYbDTADLEsg* types;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef N_CDECL_PTR(int, tyProc_HsCFdEWlCdoq2wOkZ2URfg) (void* f, NCSTRING fmt, ...);
typedef N_CDECL_PTR(void*, tyProc_SsjMo29bx9bP5kwe2xgM3Scg) (NCSTRING f, ...);
typedef N_CDECL_PTR(size_t, tyProc_ocClJDlcZaqgYpi2lF669cA) (void* f);
typedef N_CDECL_PTR(void*, tyProc_xKuFDtrrlpEd0ARlODf8xA) (void* f, size_t i);
typedef N_CDECL_PTR(int, tyProc_JOheI6S14zehX7QFjD9b9arA) (tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* f);
typedef N_CDECL_PTR(void*, tyProc_gaBVY12IBlwVY2fikmPgHQ) (tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* f, void* a, void* b);
typedef N_CDECL_PTR(int, tyProc_T08W9bgbY4bOv2q64h6irpw) (void* m, NCSTRING n, void* o);
typedef N_CDECL_PTR(void*, tyProc_E3yjbFti2J9bkUN9ckhwcXeg) (size_t size);
typedef N_CDECL_PTR(int, tyProc_nuVTH6REO8jfyM9augS15pw) (void* l, size_t index, void* i);
typedef N_CDECL_PTR(NI64, tyProc_mIlNZ9aGaphVJCyIIofK8mg) (void* l);
typedef N_CDECL_PTR(double, tyProc_2su9b9chqHYibM7sMkbSaSkA) (void* l);
typedef N_CDECL_PTR(void*, tyProc_RKlUmjvtmKGnc01PbvZaRQ) (long v);
struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q {
NF Field0;
NF Field1;
};
typedef N_CDECL_PTR(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, tyProc_pp2rHJik8czES8sAFDwvQQ) (void* op);
struct tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg {
void* module;
tyProc_SsjMo29bx9bP5kwe2xgM3Scg Py_BuildValue;
tyProc_ocClJDlcZaqgYpi2lF669cA PyTuple_Size;
tyProc_xKuFDtrrlpEd0ARlODf8xA PyTuple_GetItem;
void* Py_None;
tyProc_JOheI6S14zehX7QFjD9b9arA PyType_Ready;
tyProc_gaBVY12IBlwVY2fikmPgHQ PyType_GenericNew;
tyProc_T08W9bgbY4bOv2q64h6irpw PyModule_AddObject;
tyProc_E3yjbFti2J9bkUN9ckhwcXeg PyList_New;
tyProc_ocClJDlcZaqgYpi2lF669cA PyList_Size;
tyProc_xKuFDtrrlpEd0ARlODf8xA PyList_GetItem;
tyProc_nuVTH6REO8jfyM9augS15pw PyList_SetItem;
tyProc_mIlNZ9aGaphVJCyIIofK8mg PyLong_AsLongLong;
tyProc_2su9b9chqHYibM7sMkbSaSkA PyFloat_AsDouble;
tyProc_RKlUmjvtmKGnc01PbvZaRQ PyBool_FromLong;
tyProc_pp2rHJik8czES8sAFDwvQQ PyComplex_AsCComplex;
tyProc_2su9b9chqHYibM7sMkbSaSkA PyComplex_RealAsDouble;
tyProc_2su9b9chqHYibM7sMkbSaSkA PyComplex_ImagAsDouble;
};
typedef N_CDECL_PTR(void*, tyProc_VQ1ysQk017myXMGb79cPTVw) (void* s, void* a);
struct tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA {
NCSTRING ml_name;
tyProc_VQ1ysQk017myXMGb79cPTVw ml_meth;
int ml_flags;
NCSTRING ml_doc;
};
struct tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg {
tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* module;
NCSTRING name;
NCSTRING doc;
NimStringDesc* fullName;
tyProc_gaBVY12IBlwVY2fikmPgHQ newFunc;
tySequence_QIbr9abHr63pwRbRpKuoFFQ* methods;
tySequence_m5LAl09cqBl9bzwvVnw9aEKrg* members;
NI origSize;
};
struct tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA {
size_t ob_refcnt;
void* ob_type;
};
struct tyObject_PyObjectVarHeadObj_E71nKnjQiXK69aSURXxI79cA {
  tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA Sup;
size_t ob_size;
};
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* o);
typedef N_CDECL_PTR(int, tyProc_8H9bL9crYRIHExJYg9bWhYvMQ) (void* o, FILE* f, int c);
typedef N_CDECL_PTR(void*, tyProc_YezmFzxOOyM9cb11Eoq1Elg) (void* o, NCSTRING a);
typedef N_CDECL_PTR(void*, tyProc_jvPpjMAkI9bwM1B9apOphnlA) (void* o);
typedef N_CDECL_PTR(int, tyProc_7LMjBc4zOHVIsNdulNv7QQ) (void* o, void* a, void* at);
typedef N_CDECL_PTR(void*, tyProc_k4RBH32nrpDxtGF9acg45zw) (void* a, void* b, int c);
typedef N_CDECL_PTR(void*, tyProc_uQWqJp3WAx8fOY1h9aCwjIg) (void* a, void* b, void* c);
typedef N_CDECL_PTR(void*, tyProc_QuHKuhBxxkyDbOnFG79bCMA) (tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* typ, size_t sz);
struct tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA {
  tyObject_PyObjectVarHeadObj_E71nKnjQiXK69aSURXxI79cA Sup;
NCSTRING tp_name;
size_t tp_basicsize;
size_t tp_itemsize;
tyProc_32w2ZypAyMWuajvi2Jt79cg tp_dealloc;
tyProc_8H9bL9crYRIHExJYg9bWhYvMQ tp_print;
tyProc_YezmFzxOOyM9cb11Eoq1Elg tp_getattr;
tyProc_T08W9bgbY4bOv2q64h6irpw tp_setattr;
void* tp_as_async;
tyProc_jvPpjMAkI9bwM1B9apOphnlA tp_repr;
void* tp_as_number;
void* tp_as_sequence;
void* tp_as_mapping;
void* tp_hash;
void* tp_call;
tyProc_jvPpjMAkI9bwM1B9apOphnlA tp_str;
tyProc_VQ1ysQk017myXMGb79cPTVw tp_getattro;
tyProc_7LMjBc4zOHVIsNdulNv7QQ tp_setattro;
void* tp_as_buffer;
unsigned long tp_flags;
NCSTRING tp_doc;
void* tp_traverse;
void* tp_clear;
tyProc_k4RBH32nrpDxtGF9acg45zw tp_richcompare;
size_t tp_weaklistoffset;
tyProc_jvPpjMAkI9bwM1B9apOphnlA tp_iter;
tyProc_jvPpjMAkI9bwM1B9apOphnlA tp_iternext;
tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA* tp_methods;
tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw* tp_members;
void* tp_getset;
tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* tp_base;
void* tp_dict;
tyProc_uQWqJp3WAx8fOY1h9aCwjIg tp_descr_get;
tyProc_7LMjBc4zOHVIsNdulNv7QQ tp_descr_set;
size_t tp_dictoffset;
tyProc_7LMjBc4zOHVIsNdulNv7QQ tp_init;
tyProc_QuHKuhBxxkyDbOnFG79bCMA tp_alloc;
tyProc_gaBVY12IBlwVY2fikmPgHQ tp_new;
tyProc_32w2ZypAyMWuajvi2Jt79cg tp_free;
void* tp_is_gc;
tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA* tp_bases;
void* tp_mro;
void* tp_cache;
tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA* tp_subclasses;
tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA* tp_weaklist;
tyProc_32w2ZypAyMWuajvi2Jt79cg tp_del;
unsigned int tp_version_tag;
tyProc_32w2ZypAyMWuajvi2Jt79cg tp_finalize;
};
struct tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw {
NCSTRING name;
int typ;
size_t offset;
int flags;
NCSTRING doc;
};
struct tySequence_QIbr9abHr63pwRbRpKuoFFQ {
  TGenericSeq Sup;
  tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA data[SEQ_DECL_SIZE];
};
struct tySequence_1Ib9a4sxiw4YCYbDTADLEsg {
  TGenericSeq Sup;
  tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg data[SEQ_DECL_SIZE];
};
struct tySequence_m5LAl09cqBl9bzwvVnw9aEKrg {
  TGenericSeq Sup;
  tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw data[SEQ_DECL_SIZE];
};
static N_INLINE(NimStringDesc*, pyValueToNim_tFMM3qOo9atSGrx9bGvNa9c3wmymodule)(tyObject_PyValue_qMsYTE5XbTEsC6nUXDb5DQ* v);
N_NIMCALL(NimStringDesc*, toString_slL8EbtkTixT9aehlJ9cV9bGQ)(tyObject_Py_buffer_nRhjorz1m8nM8MZqKMfgRA* b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_eCPUjvTHvGnGdQ6SU3ZYeQ_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void, initPythonModuleDesc_FOOWv9a9c0A9buPW1MnJxC3qA)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m, NCSTRING name, NCSTRING doc);
N_NIMCALL(void, initmymodule)(void);
N_NIMCALL(void, initModuleAux2_QOPr6RYgxP9c8n2lZVbiDwA_2)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m);
N_NIMCALL(void*, PyInit_mymodule)(void);
N_NIMCALL(void*, initModuleAux3_fiCOhQD5a4JY3kdtM19cCuQ)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m);
N_NIMCALL(NimStringDesc*, greet_iB9cPg60pIwV9bFrXwMM0TRA)(NimStringDesc* name);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_CDECL(void*, greetPy_wrapper_jCX35zYwHMdcBbSTz9atcnA)(void* self, void* args);
static N_INLINE(void*, strToPyObject_5KC9cg9bQBGcEpbowAmucpaQnimpy)(NimStringDesc* s);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, addMethod_keJjYiB0Fqpj61YcmmSEgw)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m, NCSTRING name, NCSTRING doc, tyProc_VQ1ysQk017myXMGb79cPTVw f);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, stdlib_locksInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_locksDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sharedlistInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sharedlistDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_complexInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_complexDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimpy_nimpyInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimpy_nimpyDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, mymoduleDatInit000)(void);
extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA gPythonLocalModuleDesc_Q9a8X4d6yRV3fV2la0jm79bQ;
extern TNimType NTI_gBC8z6Ez5xj3dXoP0ylCRA_;
extern tyProc_HsCFdEWlCdoq2wOkZ2URfg PyArg_ParseTuple_zzMUabcLwhGju9bqqFfrCGw;
extern tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg* pyLib_bgKRHU9cKqO7op9cXO6AxcTw;
STRING_LITERAL(TM_eCPUjvTHvGnGdQ6SU3ZYeQ_3, "Hello, ", 7);
STRING_LITERAL(TM_eCPUjvTHvGnGdQ6SU3ZYeQ_4, "!", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NimStringDesc*, pyValueToNim_tFMM3qOo9atSGrx9bGvNa9c3wmymodule)(tyObject_PyValue_qMsYTE5XbTEsC6nUXDb5DQ* v) {
	NimStringDesc* result;
	nimfr_("pyValueToNim", "nimpy.nim");
	result = (NimStringDesc*)0;
	nimln_(696, "nimpy.nim");
	result = toString_slL8EbtkTixT9aehlJ9cV9bGQ((&(*v).buf));
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_eCPUjvTHvGnGdQ6SU3ZYeQ_2)(void) {
	nimGCvisit((void*)gPythonLocalModuleDesc_Q9a8X4d6yRV3fV2la0jm79bQ.methods, 0);
	nimGCvisit((void*)gPythonLocalModuleDesc_Q9a8X4d6yRV3fV2la0jm79bQ.types, 0);
}

N_NIMCALL(void, initmymodule)(void) {
	initModuleAux2_QOPr6RYgxP9c8n2lZVbiDwA_2((&gPythonLocalModuleDesc_Q9a8X4d6yRV3fV2la0jm79bQ));
}

N_NIMCALL(void*, PyInit_mymodule)(void) {
	void* result;
	result = (void*)0;
	result = initModuleAux3_fiCOhQD5a4JY3kdtM19cCuQ((&gPythonLocalModuleDesc_Q9a8X4d6yRV3fV2la0jm79bQ));
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, greet_iB9cPg60pIwV9bFrXwMM0TRA)(NimStringDesc* name) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	nimfr_("greet", "mymodule.nim");
{	result = (NimStringDesc*)0;
	nimln_(4, "mymodule.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString(name->Sup.len + 8);
appendString(T1_, ((NimStringDesc*) &TM_eCPUjvTHvGnGdQ6SU3ZYeQ_3));
appendString(T1_, name);
appendString(T1_, ((NimStringDesc*) &TM_eCPUjvTHvGnGdQ6SU3ZYeQ_4));
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void*, strToPyObject_5KC9cg9bQBGcEpbowAmucpaQnimpy)(NimStringDesc* s) {
	void* result;
	NCSTRING cs;
	int ln;
	nimfr_("strToPyObject", "nimpy.nim");
	result = (void*)0;
	nimln_(705, "nimpy.nim");
	cs = (NCSTRING)0;
	ln = (int)0;
	nimln_(707, "nimpy.nim");
	{
		if (!!((s == 0))) goto LA3_;
		nimln_(708, "nimpy.nim");
		cs = s->data;
		nimln_(709, "nimpy.nim");
		ln = ((int)chckRange((s->Sup.len), ((int) (-2147483647 -1)), ((int) 2147483647)));
	}
	LA3_: ;
	nimln_(710, "nimpy.nim");
	result = (*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).Py_BuildValue("s#", cs, ln);
	popFrame();
	return result;
}

N_CDECL(void*, greetPy_wrapper_jCX35zYwHMdcBbSTz9atcnA)(void* self, void* args) {
	void* result;
	tyObject_PyValue_qMsYTE5XbTEsC6nUXDb5DQ arg0name;
	NimStringDesc* T6_;
	NimStringDesc* T7_;
	nimfr_("greetPy_wrapper", "mymodule.nim");
{	result = (void*)0;
	nimln_(3, "mymodule.nim");
	memset((void*)(&arg0name), 0, sizeof(arg0name));
	nimln_(800, "nimpy.nim");
	{
		int T3_;
		nimln_(799, "nimpy.nim");
		nimln_(3, "mymodule.nim");
		T3_ = (int)0;
		T3_ = PyArg_ParseTuple_zzMUabcLwhGju9bqqFfrCGw(args, "s*", (&arg0name));
		if (!(T3_ == ((NI32) 0))) goto LA4_;
		nimln_(801, "nimpy.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(799, "nimpy.nim");
	nimln_(3, "mymodule.nim");
	T6_ = (NimStringDesc*)0;
	T6_ = pyValueToNim_tFMM3qOo9atSGrx9bGvNa9c3wmymodule((&arg0name));
	T7_ = (NimStringDesc*)0;
	T7_ = greet_iB9cPg60pIwV9bFrXwMM0TRA(T6_);
	result = strToPyObject_5KC9cg9bQBGcEpbowAmucpaQnimpy(T7_);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_locksDatInit000();
	stdlib_sharedlistDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_dynlibDatInit000();
	stdlib_macrosDatInit000();
	stdlib_winleanDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_complexDatInit000();
	nimpy_nimpyDatInit000();
	mymoduleDatInit000();
	stdlib_locksInit000();
	stdlib_sharedlistInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_dynlibInit000();
	stdlib_macrosInit000();
	stdlib_winleanInit000();
	stdlib_ospathsInit000();
	stdlib_complexInit000();
	nimpy_nimpyInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fwdreason, 
                    LPVOID lpvReserved) {
	if(fwdreason == DLL_PROCESS_ATTACH) {
	NimMain();
}
	return 1;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("mymodule", "mymodule.nim");
nimRegisterGlobalMarker(TM_eCPUjvTHvGnGdQ6SU3ZYeQ_2);
	nimln_(589, "nimpy.nim");
	initPythonModuleDesc_FOOWv9a9c0A9buPW1MnJxC3qA((&gPythonLocalModuleDesc_Q9a8X4d6yRV3fV2la0jm79bQ), "mymodule", NIM_NIL);
	nimln_(3, "mymodule.nim");
	addMethod_keJjYiB0Fqpj61YcmmSEgw((&gPythonLocalModuleDesc_Q9a8X4d6yRV3fV2la0jm79bQ), "greet", NIM_NIL, greetPy_wrapper_jCX35zYwHMdcBbSTz9atcnA);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, mymoduleDatInit000)(void) {
}

