/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\nim-0.17.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim-0.17.2\lib -o c:\webdev\dmlauto\nim\nimpy\nimcache\stdlib_complex.o c:\webdev\dmlauto\nim\nimpy\nimcache\stdlib_complex.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q tyTuple_wpFMp8IwxV6MlaM4GANJ0Q;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q {
NF Field0;
NF Field1;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, eqeq__3h7V4nvwribPA7xyE1WT6g)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(NIM_BOOL, eqtilde__3h7V4nvwribPA7xyE1WT6g_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, plus__PxbokZ24uT21B0KIdnqlpw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, plus__1s19c7HdWBlwDXuzVCtV1BA)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, NF y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, plus__m9bEmLwn59az4csS8iW6vBtw)(NF x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__LJKz8w8PBY3HVS11jZr4Pw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__PxbokZ24uT21B0KIdnqlpw_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__1s19c7HdWBlwDXuzVCtV1BA_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, NF y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__m9bEmLwn59az4csS8iW6vBtw_2)(NF x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, slash__PxbokZ24uT21B0KIdnqlpw_3)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, slash__1s19c7HdWBlwDXuzVCtV1BA_3)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, NF y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, slash__m9bEmLwn59az4csS8iW6vBtw_3)(NF x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, star__PxbokZ24uT21B0KIdnqlpw_4)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, star__m9bEmLwn59az4csS8iW6vBtw_4)(NF x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, star__1s19c7HdWBlwDXuzVCtV1BA_4)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, NF y);
N_NIMCALL(void, pluseq__VRa8lUQmyrWWHgP7IVOTcg)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, pluseq__v1vLHHKDy19bd9bFT9b48yezQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, NF y);
static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAwcomplex)(NF* x, NF y);
N_NIMCALL(void, minuseq__VRa8lUQmyrWWHgP7IVOTcg_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(void, minuseq__v1vLHHKDy19bd9bFT9b48yezQ_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, NF y);
N_NIMCALL(void, stareq__VRa8lUQmyrWWHgP7IVOTcg_3)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(void, stareq__v1vLHHKDy19bd9bFT9b48yezQ_3)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, NF y);
static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwstrutils)(NF* x, NF y);
N_NIMCALL(void, slasheq__VRa8lUQmyrWWHgP7IVOTcg_4)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(void, slasheq__v1vLHHKDy19bd9bFT9b48yezQ_4)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, NF y);
static N_INLINE(void, slasheq__7kHiltrvRlcg6wSYR3CxAwsystem)(NF* x, NF y);
N_NIMCALL(NF, abs_WUUrD3OCAD9c4YaaEwKuL1w)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, conjugate_LJKz8w8PBY3HVS11jZr4Pw_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, sqrt_LJKz8w8PBY3HVS11jZr4Pw_3)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, exp_LJKz8w8PBY3HVS11jZr4Pw_4)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, ln_LJKz8w8PBY3HVS11jZr4Pw_5)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, log10_LJKz8w8PBY3HVS11jZr4Pw_6)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, log2_LJKz8w8PBY3HVS11jZr4Pw_7)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, pow_PxbokZ24uT21B0KIdnqlpw_5)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, sin_LJKz8w8PBY3HVS11jZr4Pw_8)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arcsin_LJKz8w8PBY3HVS11jZr4Pw_9)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, cos_LJKz8w8PBY3HVS11jZr4Pw_10)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccos_LJKz8w8PBY3HVS11jZr4Pw_11)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, tan_LJKz8w8PBY3HVS11jZr4Pw_12)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arctan_LJKz8w8PBY3HVS11jZr4Pw_13)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, cot_LJKz8w8PBY3HVS11jZr4Pw_14)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccot_LJKz8w8PBY3HVS11jZr4Pw_15)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, sec_LJKz8w8PBY3HVS11jZr4Pw_16)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arcsec_LJKz8w8PBY3HVS11jZr4Pw_17)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, csc_LJKz8w8PBY3HVS11jZr4Pw_18)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccsc_LJKz8w8PBY3HVS11jZr4Pw_19)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, sinh_LJKz8w8PBY3HVS11jZr4Pw_20)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arcsinh_LJKz8w8PBY3HVS11jZr4Pw_21)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, cosh_LJKz8w8PBY3HVS11jZr4Pw_22)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccosh_LJKz8w8PBY3HVS11jZr4Pw_23)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, tanh_LJKz8w8PBY3HVS11jZr4Pw_24)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arctanh_LJKz8w8PBY3HVS11jZr4Pw_25)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, sech_LJKz8w8PBY3HVS11jZr4Pw_26)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arcsech_LJKz8w8PBY3HVS11jZr4Pw_27)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, csch_LJKz8w8PBY3HVS11jZr4Pw_28)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccsch_LJKz8w8PBY3HVS11jZr4Pw_29)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, coth_LJKz8w8PBY3HVS11jZr4Pw_30)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccoth_LJKz8w8PBY3HVS11jZr4Pw_31)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(NF, phase_WUUrD3OCAD9c4YaaEwKuL1w_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, polar_QKyyXTmKrRuI7gnBlsVkSA)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, rect_iCRrPjUjWOLrSvIXBIxbLA)(NF r, NF phi);
N_NIMCALL(NimStringDesc*, dollar__9cB0Notjw2XJStqSm8TmhqQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NIM_CONST tyTuple_wpFMp8IwxV6MlaM4GANJ0Q TM_imqGIu4p8qCA1da6NG1MuQ_2 = {0.0,
1.0000000000000000e+000}
;
STRING_LITERAL(TM_imqGIu4p8qCA1da6NG1MuQ_3, "(", 1);
STRING_LITERAL(TM_imqGIu4p8qCA1da6NG1MuQ_4, ", ", 2);
STRING_LITERAL(TM_imqGIu4p8qCA1da6NG1MuQ_5, ")", 1);

N_NIMCALL(NIM_BOOL, eqeq__3h7V4nvwribPA7xyE1WT6g)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = (x.Field0 == y.Field0);
	if (!(T1_)) goto LA2_;
	T1_ = (x.Field1 == y.Field1);
	LA2_: ;
	result = T1_;
	return result;
}

N_NIMCALL(NIM_BOOL, eqtilde__3h7V4nvwribPA7xyE1WT6g_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = ((((NF)(x.Field0) - (NF)(y.Field0)) < 0? -(((NF)(x.Field0) - (NF)(y.Field0))) : (((NF)(x.Field0) - (NF)(y.Field0)))) < 9.9999999999999995e-008);
	if (!(T1_)) goto LA2_;
	T1_ = ((((NF)(x.Field1) - (NF)(y.Field1)) < 0? -(((NF)(x.Field1) - (NF)(y.Field1))) : (((NF)(x.Field1) - (NF)(y.Field1)))) < 9.9999999999999995e-008);
	LA2_: ;
	result = T1_;
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, plus__PxbokZ24uT21B0KIdnqlpw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = ((NF)(x.Field0) + (NF)(y.Field0));
	result.Field1 = ((NF)(x.Field1) + (NF)(y.Field1));
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, plus__1s19c7HdWBlwDXuzVCtV1BA)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, NF y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = ((NF)(x.Field0) + (NF)(y));
	result.Field1 = x.Field1;
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, plus__m9bEmLwn59az4csS8iW6vBtw)(NF x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = ((NF)(x) + (NF)(y.Field0));
	result.Field1 = y.Field1;
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__LJKz8w8PBY3HVS11jZr4Pw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = -(z.Field0);
	result.Field1 = -(z.Field1);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__PxbokZ24uT21B0KIdnqlpw_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = ((NF)(x.Field0) - (NF)(y.Field0));
	result.Field1 = ((NF)(x.Field1) - (NF)(y.Field1));
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__1s19c7HdWBlwDXuzVCtV1BA_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, NF y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result = plus__1s19c7HdWBlwDXuzVCtV1BA(x, -(y));
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__m9bEmLwn59az4csS8iW6vBtw_2)(NF x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = minus__LJKz8w8PBY3HVS11jZr4Pw(y);
	result = plus__m9bEmLwn59az4csS8iW6vBtw(x, T1_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, slash__PxbokZ24uT21B0KIdnqlpw_3)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	NF r;
	NF den;
	memset((void*)(&result), 0, sizeof(result));
	r = (NF)0;
	den = (NF)0;
	{
		if (!((y.Field0 < 0? -(y.Field0) : (y.Field0)) < (y.Field1 < 0? -(y.Field1) : (y.Field1)))) goto LA3_;
		r = ((NF)(y.Field0) / (NF)(y.Field1));
		den = ((NF)(y.Field1) + (NF)(((NF)(r) * (NF)(y.Field0))));
		result.Field0 = ((NF)(((NF)(((NF)(x.Field0) * (NF)(r))) + (NF)(x.Field1))) / (NF)(den));
		result.Field1 = ((NF)(((NF)(((NF)(x.Field1) * (NF)(r))) - (NF)(x.Field0))) / (NF)(den));
	}
	goto LA1_;
	LA3_: ;
	{
		r = ((NF)(y.Field1) / (NF)(y.Field0));
		den = ((NF)(y.Field0) + (NF)(((NF)(r) * (NF)(y.Field1))));
		result.Field0 = ((NF)(((NF)(x.Field0) + (NF)(((NF)(r) * (NF)(x.Field1))))) / (NF)(den));
		result.Field1 = ((NF)(((NF)(x.Field1) - (NF)(((NF)(r) * (NF)(x.Field0))))) / (NF)(den));
	}
	LA1_: ;
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, slash__1s19c7HdWBlwDXuzVCtV1BA_3)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, NF y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = ((NF)(x.Field0) / (NF)(y));
	result.Field1 = ((NF)(x.Field1) / (NF)(y));
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, slash__m9bEmLwn59az4csS8iW6vBtw_3)(NF x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q num;
	memset((void*)(&result), 0, sizeof(result));
	num.Field0 = x;
	num.Field1 = 0.0;
	result = slash__PxbokZ24uT21B0KIdnqlpw_3(num, y);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, star__PxbokZ24uT21B0KIdnqlpw_4)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = ((NF)(((NF)(x.Field0) * (NF)(y.Field0))) - (NF)(((NF)(x.Field1) * (NF)(y.Field1))));
	result.Field1 = ((NF)(((NF)(x.Field1) * (NF)(y.Field0))) + (NF)(((NF)(x.Field0) * (NF)(y.Field1))));
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, star__m9bEmLwn59az4csS8iW6vBtw_4)(NF x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = ((NF)(x) * (NF)(y.Field0));
	result.Field1 = ((NF)(x) * (NF)(y.Field1));
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, star__1s19c7HdWBlwDXuzVCtV1BA_4)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, NF y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = ((NF)(x.Field0) * (NF)(y));
	result.Field1 = ((NF)(x.Field1) * (NF)(y));
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y) {
	nimfr_("+=", "system.nim");
	nimln_(3534, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

N_NIMCALL(void, pluseq__VRa8lUQmyrWWHgP7IVOTcg)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*x).Field0), y.Field0);
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*x).Field1), y.Field1);
}

N_NIMCALL(void, pluseq__v1vLHHKDy19bd9bFT9b48yezQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, NF y) {
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*x).Field0), y);
}

static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAwcomplex)(NF* x, NF y) {
	nimfr_("-=", "system.nim");
	nimln_(3539, "system.nim");
	(*x) = ((NF)((*x)) - (NF)(y));
	popFrame();
}

N_NIMCALL(void, minuseq__VRa8lUQmyrWWHgP7IVOTcg_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	minuseq__7kHiltrvRlcg6wSYR3CxAwcomplex((&(*x).Field0), y.Field0);
	minuseq__7kHiltrvRlcg6wSYR3CxAwcomplex((&(*x).Field1), y.Field1);
}

N_NIMCALL(void, minuseq__v1vLHHKDy19bd9bFT9b48yezQ_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, NF y) {
	minuseq__7kHiltrvRlcg6wSYR3CxAwcomplex((&(*x).Field0), y);
}

N_NIMCALL(void, stareq__VRa8lUQmyrWWHgP7IVOTcg_3)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	NF im;
	im = ((NF)(((NF)((*x).Field1) * (NF)(y.Field0))) + (NF)(((NF)((*x).Field0) * (NF)(y.Field1))));
	(*x).Field0 = ((NF)(((NF)((*x).Field0) * (NF)(y.Field0))) - (NF)(((NF)((*x).Field1) * (NF)(y.Field1))));
	(*x).Field1 = im;
}

static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwstrutils)(NF* x, NF y) {
	nimfr_("*=", "system.nim");
	nimln_(3544, "system.nim");
	(*x) = ((NF)((*x)) * (NF)(y));
	popFrame();
}

N_NIMCALL(void, stareq__v1vLHHKDy19bd9bFT9b48yezQ_3)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, NF y) {
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*x).Field0), y);
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*x).Field1), y);
}

N_NIMCALL(void, slasheq__VRa8lUQmyrWWHgP7IVOTcg_4)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	(*x) = slash__PxbokZ24uT21B0KIdnqlpw_3((*x), y);
}

static N_INLINE(void, slasheq__7kHiltrvRlcg6wSYR3CxAwsystem)(NF* x, NF y) {
	nimfr_("/=", "system.nim");
	nimln_(3548, "system.nim");
	(*x) = ((NF)((*x)) / (NF)(y));
	popFrame();
}

N_NIMCALL(void, slasheq__v1vLHHKDy19bd9bFT9b48yezQ_4)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* x, NF y) {
	slasheq__7kHiltrvRlcg6wSYR3CxAwsystem((&(*x).Field0), y);
	slasheq__7kHiltrvRlcg6wSYR3CxAwsystem((&(*x).Field1), y);
}

N_NIMCALL(NF, abs_WUUrD3OCAD9c4YaaEwKuL1w)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	NF result;
	NF x;
	NF y;
	NF temp;
	result = (NF)0;
	x = (NF)0;
	y = (NF)0;
	temp = (NF)0;
	x = (z.Field0 < 0? -(z.Field0) : (z.Field0));
	y = (z.Field1 < 0? -(z.Field1) : (z.Field1));
	{
		if (!(x == 0.0)) goto LA3_;
		result = y;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(y == 0.0)) goto LA6_;
		result = x;
	}
	goto LA1_;
	LA6_: ;
	{
		NF T11_;
		if (!(y < x)) goto LA9_;
		temp = ((NF)(y) / (NF)(x));
		T11_ = (NF)0;
		T11_ = sqrt(((NF)(1.0000000000000000e+000) + (NF)(((NF)(temp) * (NF)(temp)))));
		result = ((NF)(x) * (NF)(T11_));
	}
	goto LA1_;
	LA9_: ;
	{
		NF T13_;
		temp = ((NF)(x) / (NF)(y));
		T13_ = (NF)0;
		T13_ = sqrt(((NF)(1.0000000000000000e+000) + (NF)(((NF)(temp) * (NF)(temp)))));
		result = ((NF)(y) * (NF)(T13_));
	}
	LA1_: ;
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, conjugate_LJKz8w8PBY3HVS11jZr4Pw_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = z.Field0;
	result.Field1 = -(z.Field1);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, sqrt_LJKz8w8PBY3HVS11jZr4Pw_3)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	NF x;
	NF y;
	NF w;
	NF r;
	memset((void*)(&result), 0, sizeof(result));
	x = (NF)0;
	y = (NF)0;
	w = (NF)0;
	r = (NF)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (z.Field0 == 0.0);
		if (!(T3_)) goto LA4_;
		T3_ = (z.Field1 == 0.0);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = z;
	}
	goto LA1_;
	LA5_: ;
	{
		x = (z.Field0 < 0? -(z.Field0) : (z.Field0));
		y = (z.Field1 < 0? -(z.Field1) : (z.Field1));
		{
			NF T12_;
			NF T13_;
			NF T14_;
			if (!(y <= x)) goto LA10_;
			r = ((NF)(y) / (NF)(x));
			T12_ = (NF)0;
			T12_ = sqrt(x);
			T13_ = (NF)0;
			T13_ = sqrt(((NF)(1.0000000000000000e+000) + (NF)(((NF)(r) * (NF)(r)))));
			T14_ = (NF)0;
			T14_ = sqrt(((NF)(5.0000000000000000e-001) * (NF)(((NF)(1.0000000000000000e+000) + (NF)(T13_)))));
			w = ((NF)(T12_) * (NF)(T14_));
		}
		goto LA8_;
		LA10_: ;
		{
			NF T16_;
			NF T17_;
			NF T18_;
			r = ((NF)(x) / (NF)(y));
			T16_ = (NF)0;
			T16_ = sqrt(y);
			T17_ = (NF)0;
			T17_ = sqrt(((NF)(1.0000000000000000e+000) + (NF)(((NF)(r) * (NF)(r)))));
			T18_ = (NF)0;
			T18_ = sqrt(((NF)(5.0000000000000000e-001) * (NF)(((NF)(r) + (NF)(T17_)))));
			w = ((NF)(T16_) * (NF)(T18_));
		}
		LA8_: ;
		{
			if (!(0.0 <= z.Field0)) goto LA21_;
			result.Field0 = w;
			result.Field1 = ((NF)(z.Field1) / (NF)(((NF)(w) * (NF)(2.0000000000000000e+000))));
		}
		goto LA19_;
		LA21_: ;
		{
			{
				if (!(0.0 <= z.Field1)) goto LA26_;
				result.Field1 = w;
			}
			goto LA24_;
			LA26_: ;
			{
				result.Field1 = -(w);
			}
			LA24_: ;
			result.Field0 = ((NF)(z.Field1) / (NF)(((NF)(result.Field1) + (NF)(result.Field1))));
		}
		LA19_: ;
	}
	LA1_: ;
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, exp_LJKz8w8PBY3HVS11jZr4Pw_4)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	NF rho;
	NF theta;
	NF T1_;
	NF T2_;
	memset((void*)(&result), 0, sizeof(result));
	rho = exp(z.Field0);
	theta = z.Field1;
	T1_ = (NF)0;
	T1_ = cos(theta);
	result.Field0 = ((NF)(rho) * (NF)(T1_));
	T2_ = (NF)0;
	T2_ = sin(theta);
	result.Field1 = ((NF)(rho) * (NF)(T2_));
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, ln_LJKz8w8PBY3HVS11jZr4Pw_5)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	NF T1_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = (NF)0;
	T1_ = abs_WUUrD3OCAD9c4YaaEwKuL1w(z);
	result.Field0 = log(T1_);
	result.Field1 = atan2(z.Field1, z.Field0);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, log10_LJKz8w8PBY3HVS11jZr4Pw_6)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	NF T2_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(z);
	T2_ = (NF)0;
	T2_ = log(1.0000000000000000e+001);
	result = slash__1s19c7HdWBlwDXuzVCtV1BA_3(T1_, T2_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, log2_LJKz8w8PBY3HVS11jZr4Pw_7)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	NF T2_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(z);
	T2_ = (NF)0;
	T2_ = log(2.0000000000000000e+000);
	result = slash__1s19c7HdWBlwDXuzVCtV1BA_3(T1_, T2_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, pow_PxbokZ24uT21B0KIdnqlpw_5)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q x, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q y) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (x.Field0 == 0.0);
		if (!(T3_)) goto LA4_;
		T3_ = (x.Field1 == 0.0);
		LA4_: ;
		if (!T3_) goto LA5_;
		{
			NIM_BOOL T9_;
			T9_ = (NIM_BOOL)0;
			T9_ = (y.Field0 == 0.0);
			if (!(T9_)) goto LA10_;
			T9_ = (y.Field1 == 0.0);
			LA10_: ;
			if (!T9_) goto LA11_;
			result.Field0 = 1.0000000000000000e+000;
			result.Field1 = 0.0;
		}
		goto LA7_;
		LA11_: ;
		{
			result.Field0 = 0.0;
			result.Field1 = 0.0;
		}
		LA7_: ;
	}
	goto LA1_;
	LA5_: ;
	{
		NIM_BOOL T15_;
		T15_ = (NIM_BOOL)0;
		T15_ = (y.Field0 == 1.0000000000000000e+000);
		if (!(T15_)) goto LA16_;
		T15_ = (y.Field1 == 0.0);
		LA16_: ;
		if (!T15_) goto LA17_;
		result = x;
	}
	goto LA1_;
	LA17_: ;
	{
		NIM_BOOL T20_;
		T20_ = (NIM_BOOL)0;
		T20_ = (y.Field0 == -1.0000000000000000e+000);
		if (!(T20_)) goto LA21_;
		T20_ = (y.Field1 == 0.0);
		LA21_: ;
		if (!T20_) goto LA22_;
		result = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, x);
	}
	goto LA1_;
	LA22_: ;
	{
		NF rho;
		NF theta;
		NF s;
		NF T25_;
		NF T26_;
		NF r;
		NF T27_;
		NF T28_;
		NF T29_;
		rho = sqrt(((NF)(((NF)(x.Field0) * (NF)(x.Field0))) + (NF)(((NF)(x.Field1) * (NF)(x.Field1)))));
		theta = atan2(x.Field1, x.Field0);
		T25_ = (NF)0;
		T25_ = pow(rho, y.Field0);
		T26_ = (NF)0;
		T26_ = exp(((NF)(-(y.Field1)) * (NF)(theta)));
		s = ((NF)(T25_) * (NF)(T26_));
		T27_ = (NF)0;
		T27_ = log(rho);
		r = ((NF)(((NF)(y.Field0) * (NF)(theta))) + (NF)(((NF)(y.Field1) * (NF)(T27_))));
		T28_ = (NF)0;
		T28_ = cos(r);
		result.Field0 = ((NF)(s) * (NF)(T28_));
		T29_ = (NF)0;
		T29_ = sin(r);
		result.Field1 = ((NF)(s) * (NF)(T29_));
	}
	LA1_: ;
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, sin_LJKz8w8PBY3HVS11jZr4Pw_8)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	NF T1_;
	NF T2_;
	NF T3_;
	NF T4_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = (NF)0;
	T1_ = sin(z.Field0);
	T2_ = (NF)0;
	T2_ = cosh(z.Field1);
	result.Field0 = ((NF)(T1_) * (NF)(T2_));
	T3_ = (NF)0;
	T3_ = cos(z.Field0);
	T4_ = (NF)0;
	T4_ = sinh(z.Field1);
	result.Field1 = ((NF)(T3_) * (NF)(T4_));
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arcsin_LJKz8w8PBY3HVS11jZr4Pw_9)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q i;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T5_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T6_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T7_;
	memset((void*)(&result), 0, sizeof(result));
	i = TM_imqGIu4p8qCA1da6NG1MuQ_2;
	T1_ = minus__LJKz8w8PBY3HVS11jZr4Pw(i);
	T2_ = star__PxbokZ24uT21B0KIdnqlpw_4(i, z);
	T3_ = star__PxbokZ24uT21B0KIdnqlpw_4(z, z);
	T4_ = minus__m9bEmLwn59az4csS8iW6vBtw_2(1.0000000000000000e+000, T3_);
	T5_ = sqrt_LJKz8w8PBY3HVS11jZr4Pw_3(T4_);
	T6_ = plus__PxbokZ24uT21B0KIdnqlpw(T2_, T5_);
	T7_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T6_);
	result = star__PxbokZ24uT21B0KIdnqlpw_4(T1_, T7_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, cos_LJKz8w8PBY3HVS11jZr4Pw_10)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	NF T1_;
	NF T2_;
	NF T3_;
	NF T4_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = (NF)0;
	T1_ = cos(z.Field0);
	T2_ = (NF)0;
	T2_ = cosh(z.Field1);
	result.Field0 = ((NF)(T1_) * (NF)(T2_));
	T3_ = (NF)0;
	T3_ = sin(z.Field0);
	T4_ = (NF)0;
	T4_ = sinh(z.Field1);
	result.Field1 = ((NF)(-(T3_)) * (NF)(T4_));
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccos_LJKz8w8PBY3HVS11jZr4Pw_11)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q i;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T5_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T6_;
	memset((void*)(&result), 0, sizeof(result));
	i = TM_imqGIu4p8qCA1da6NG1MuQ_2;
	T1_ = minus__LJKz8w8PBY3HVS11jZr4Pw(i);
	T2_ = star__PxbokZ24uT21B0KIdnqlpw_4(z, z);
	T3_ = minus__1s19c7HdWBlwDXuzVCtV1BA_2(T2_, 1.0000000000000000e+000);
	T4_ = sqrt_LJKz8w8PBY3HVS11jZr4Pw_3(T3_);
	T5_ = plus__PxbokZ24uT21B0KIdnqlpw(z, T4_);
	T6_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T5_);
	result = star__PxbokZ24uT21B0KIdnqlpw_4(T1_, T6_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, tan_LJKz8w8PBY3HVS11jZr4Pw_12)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = sin_LJKz8w8PBY3HVS11jZr4Pw_8(z);
	T2_ = cos_LJKz8w8PBY3HVS11jZr4Pw_10(z);
	result = slash__PxbokZ24uT21B0KIdnqlpw_3(T1_, T2_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arctan_LJKz8w8PBY3HVS11jZr4Pw_13)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q i;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T5_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T6_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T7_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T8_;
	memset((void*)(&result), 0, sizeof(result));
	i = TM_imqGIu4p8qCA1da6NG1MuQ_2;
	T1_ = star__m9bEmLwn59az4csS8iW6vBtw_4(5.0000000000000000e-001, i);
	T2_ = star__PxbokZ24uT21B0KIdnqlpw_4(i, z);
	T3_ = minus__m9bEmLwn59az4csS8iW6vBtw_2(1.0000000000000000e+000, T2_);
	T4_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T3_);
	T5_ = star__PxbokZ24uT21B0KIdnqlpw_4(i, z);
	T6_ = plus__m9bEmLwn59az4csS8iW6vBtw(1.0000000000000000e+000, T5_);
	T7_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T6_);
	T8_ = minus__PxbokZ24uT21B0KIdnqlpw_2(T4_, T7_);
	result = star__PxbokZ24uT21B0KIdnqlpw_4(T1_, T8_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, cot_LJKz8w8PBY3HVS11jZr4Pw_14)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = cos_LJKz8w8PBY3HVS11jZr4Pw_10(z);
	T2_ = sin_LJKz8w8PBY3HVS11jZr4Pw_8(z);
	result = slash__PxbokZ24uT21B0KIdnqlpw_3(T1_, T2_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccot_LJKz8w8PBY3HVS11jZr4Pw_15)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q i;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T5_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T6_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T7_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T8_;
	memset((void*)(&result), 0, sizeof(result));
	i = TM_imqGIu4p8qCA1da6NG1MuQ_2;
	T1_ = star__m9bEmLwn59az4csS8iW6vBtw_4(5.0000000000000000e-001, i);
	T2_ = slash__PxbokZ24uT21B0KIdnqlpw_3(i, z);
	T3_ = minus__m9bEmLwn59az4csS8iW6vBtw_2(1.0000000000000000e+000, T2_);
	T4_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T3_);
	T5_ = slash__PxbokZ24uT21B0KIdnqlpw_3(i, z);
	T6_ = plus__m9bEmLwn59az4csS8iW6vBtw(1.0000000000000000e+000, T5_);
	T7_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T6_);
	T8_ = minus__PxbokZ24uT21B0KIdnqlpw_2(T4_, T7_);
	result = star__PxbokZ24uT21B0KIdnqlpw_4(T1_, T8_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, sec_LJKz8w8PBY3HVS11jZr4Pw_16)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = cos_LJKz8w8PBY3HVS11jZr4Pw_10(z);
	result = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, T1_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arcsec_LJKz8w8PBY3HVS11jZr4Pw_17)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q i;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T5_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T6_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T7_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T8_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T9_;
	memset((void*)(&result), 0, sizeof(result));
	i = TM_imqGIu4p8qCA1da6NG1MuQ_2;
	T1_ = minus__LJKz8w8PBY3HVS11jZr4Pw(i);
	T2_ = star__PxbokZ24uT21B0KIdnqlpw_4(z, z);
	T3_ = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, T2_);
	T4_ = minus__m9bEmLwn59az4csS8iW6vBtw_2(1.0000000000000000e+000, T3_);
	T5_ = sqrt_LJKz8w8PBY3HVS11jZr4Pw_3(T4_);
	T6_ = star__PxbokZ24uT21B0KIdnqlpw_4(i, T5_);
	T7_ = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, z);
	T8_ = plus__PxbokZ24uT21B0KIdnqlpw(T6_, T7_);
	T9_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T8_);
	result = star__PxbokZ24uT21B0KIdnqlpw_4(T1_, T9_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, csc_LJKz8w8PBY3HVS11jZr4Pw_18)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = sin_LJKz8w8PBY3HVS11jZr4Pw_8(z);
	result = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, T1_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccsc_LJKz8w8PBY3HVS11jZr4Pw_19)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q i;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T5_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T6_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T7_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T8_;
	memset((void*)(&result), 0, sizeof(result));
	i = TM_imqGIu4p8qCA1da6NG1MuQ_2;
	T1_ = minus__LJKz8w8PBY3HVS11jZr4Pw(i);
	T2_ = star__PxbokZ24uT21B0KIdnqlpw_4(z, z);
	T3_ = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, T2_);
	T4_ = minus__m9bEmLwn59az4csS8iW6vBtw_2(1.0000000000000000e+000, T3_);
	T5_ = sqrt_LJKz8w8PBY3HVS11jZr4Pw_3(T4_);
	T6_ = slash__PxbokZ24uT21B0KIdnqlpw_3(i, z);
	T7_ = plus__PxbokZ24uT21B0KIdnqlpw(T5_, T6_);
	T8_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T7_);
	result = star__PxbokZ24uT21B0KIdnqlpw_4(T1_, T8_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, sinh_LJKz8w8PBY3HVS11jZr4Pw_20)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = exp_LJKz8w8PBY3HVS11jZr4Pw_4(z);
	T2_ = minus__LJKz8w8PBY3HVS11jZr4Pw(z);
	T3_ = exp_LJKz8w8PBY3HVS11jZr4Pw_4(T2_);
	T4_ = minus__PxbokZ24uT21B0KIdnqlpw_2(T1_, T3_);
	result = star__m9bEmLwn59az4csS8iW6vBtw_4(5.0000000000000000e-001, T4_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arcsinh_LJKz8w8PBY3HVS11jZr4Pw_21)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = star__PxbokZ24uT21B0KIdnqlpw_4(z, z);
	T2_ = plus__1s19c7HdWBlwDXuzVCtV1BA(T1_, 1.0000000000000000e+000);
	T3_ = sqrt_LJKz8w8PBY3HVS11jZr4Pw_3(T2_);
	T4_ = plus__PxbokZ24uT21B0KIdnqlpw(z, T3_);
	result = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T4_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, cosh_LJKz8w8PBY3HVS11jZr4Pw_22)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = exp_LJKz8w8PBY3HVS11jZr4Pw_4(z);
	T2_ = minus__LJKz8w8PBY3HVS11jZr4Pw(z);
	T3_ = exp_LJKz8w8PBY3HVS11jZr4Pw_4(T2_);
	T4_ = plus__PxbokZ24uT21B0KIdnqlpw(T1_, T3_);
	result = star__m9bEmLwn59az4csS8iW6vBtw_4(5.0000000000000000e-001, T4_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccosh_LJKz8w8PBY3HVS11jZr4Pw_23)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = star__PxbokZ24uT21B0KIdnqlpw_4(z, z);
	T2_ = minus__1s19c7HdWBlwDXuzVCtV1BA_2(T1_, 1.0000000000000000e+000);
	T3_ = sqrt_LJKz8w8PBY3HVS11jZr4Pw_3(T2_);
	T4_ = plus__PxbokZ24uT21B0KIdnqlpw(z, T3_);
	result = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T4_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, tanh_LJKz8w8PBY3HVS11jZr4Pw_24)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = sinh_LJKz8w8PBY3HVS11jZr4Pw_20(z);
	T2_ = cosh_LJKz8w8PBY3HVS11jZr4Pw_22(z);
	result = slash__PxbokZ24uT21B0KIdnqlpw_3(T1_, T2_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arctanh_LJKz8w8PBY3HVS11jZr4Pw_25)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = plus__m9bEmLwn59az4csS8iW6vBtw(1.0000000000000000e+000, z);
	T2_ = minus__m9bEmLwn59az4csS8iW6vBtw_2(1.0000000000000000e+000, z);
	T3_ = slash__PxbokZ24uT21B0KIdnqlpw_3(T1_, T2_);
	T4_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T3_);
	result = star__m9bEmLwn59az4csS8iW6vBtw_4(5.0000000000000000e-001, T4_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, sech_LJKz8w8PBY3HVS11jZr4Pw_26)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = exp_LJKz8w8PBY3HVS11jZr4Pw_4(z);
	T2_ = minus__LJKz8w8PBY3HVS11jZr4Pw(z);
	T3_ = exp_LJKz8w8PBY3HVS11jZr4Pw_4(T2_);
	T4_ = plus__PxbokZ24uT21B0KIdnqlpw(T1_, T3_);
	result = slash__m9bEmLwn59az4csS8iW6vBtw_3(2.0000000000000000e+000, T4_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arcsech_LJKz8w8PBY3HVS11jZr4Pw_27)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T5_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T6_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T7_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T8_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T9_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, z);
	T2_ = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, z);
	T3_ = plus__1s19c7HdWBlwDXuzVCtV1BA(T2_, 1.0000000000000000e+000);
	T4_ = sqrt_LJKz8w8PBY3HVS11jZr4Pw_3(T3_);
	T5_ = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, z);
	T6_ = minus__1s19c7HdWBlwDXuzVCtV1BA_2(T5_, 1.0000000000000000e+000);
	T7_ = sqrt_LJKz8w8PBY3HVS11jZr4Pw_3(T6_);
	T8_ = star__PxbokZ24uT21B0KIdnqlpw_4(T4_, T7_);
	T9_ = plus__PxbokZ24uT21B0KIdnqlpw(T1_, T8_);
	result = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T9_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, csch_LJKz8w8PBY3HVS11jZr4Pw_28)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = exp_LJKz8w8PBY3HVS11jZr4Pw_4(z);
	T2_ = minus__LJKz8w8PBY3HVS11jZr4Pw(z);
	T3_ = exp_LJKz8w8PBY3HVS11jZr4Pw_4(T2_);
	T4_ = minus__PxbokZ24uT21B0KIdnqlpw_2(T1_, T3_);
	result = slash__m9bEmLwn59az4csS8iW6vBtw_3(2.0000000000000000e+000, T4_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccsch_LJKz8w8PBY3HVS11jZr4Pw_29)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T5_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T6_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, z);
	T2_ = star__PxbokZ24uT21B0KIdnqlpw_4(z, z);
	T3_ = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, T2_);
	T4_ = plus__1s19c7HdWBlwDXuzVCtV1BA(T3_, 1.0000000000000000e+000);
	T5_ = sqrt_LJKz8w8PBY3HVS11jZr4Pw_3(T4_);
	T6_ = plus__PxbokZ24uT21B0KIdnqlpw(T1_, T5_);
	result = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T6_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, coth_LJKz8w8PBY3HVS11jZr4Pw_30)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = cosh_LJKz8w8PBY3HVS11jZr4Pw_22(z);
	T2_ = sinh_LJKz8w8PBY3HVS11jZr4Pw_20(z);
	result = slash__PxbokZ24uT21B0KIdnqlpw_3(T1_, T2_);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, arccoth_LJKz8w8PBY3HVS11jZr4Pw_31)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T3_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T4_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T5_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T6_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T7_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, z);
	T2_ = plus__m9bEmLwn59az4csS8iW6vBtw(1.0000000000000000e+000, T1_);
	T3_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T2_);
	T4_ = slash__m9bEmLwn59az4csS8iW6vBtw_3(1.0000000000000000e+000, z);
	T5_ = minus__m9bEmLwn59az4csS8iW6vBtw_2(1.0000000000000000e+000, T4_);
	T6_ = ln_LJKz8w8PBY3HVS11jZr4Pw_5(T5_);
	T7_ = minus__PxbokZ24uT21B0KIdnqlpw_2(T3_, T6_);
	result = star__m9bEmLwn59az4csS8iW6vBtw_4(5.0000000000000000e-001, T7_);
	return result;
}

N_NIMCALL(NF, phase_WUUrD3OCAD9c4YaaEwKuL1w_2)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	NF result;
	result = (NF)0;
	result = atan2(z.Field1, z.Field0);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, polar_QKyyXTmKrRuI7gnBlsVkSA)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = abs_WUUrD3OCAD9c4YaaEwKuL1w(z);
	result.Field1 = phase_WUUrD3OCAD9c4YaaEwKuL1w_2(z);
	return result;
}

N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, rect_iCRrPjUjWOLrSvIXBIxbLA)(NF r, NF phi) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	NF T1_;
	NF T2_;
	memset((void*)(&result), 0, sizeof(result));
	T1_ = (NF)0;
	T1_ = cos(phi);
	result.Field0 = ((NF)(r) * (NF)(T1_));
	T2_ = (NF)0;
	T2_ = sin(phi);
	result.Field1 = ((NF)(r) * (NF)(T2_));
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, dollar__9cB0Notjw2XJStqSm8TmhqQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q z) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimFloatToStr(z.Field0);
	T3_ = (NimStringDesc*)0;
	T3_ = nimFloatToStr(z.Field1);
	T1_ = rawNewString(T2_->Sup.len + T3_->Sup.len + 4);
appendString(T1_, ((NimStringDesc*) &TM_imqGIu4p8qCA1da6NG1MuQ_3));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_imqGIu4p8qCA1da6NG1MuQ_4));
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_imqGIu4p8qCA1da6NG1MuQ_5));
	result = T1_;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_complexInit000)(void) {
	nimfr_("complex", "complex.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_complexDatInit000)(void) {
}

