/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Yobmod\.choosenim\toolchains\nim-0.18.0\lib -o c:\Webdev\dmltests\nim\jester\nimcache\stdlib_sockets.o c:\Webdev\dmltests\nim\jester\nimcache\stdlib_sockets.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#include "winsock2.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ;
typedef struct tySequence_bTfD0pPidBST9bT9bmQFkEdg tySequence_bTfD0pPidBST9bT9bmQFkEdg;
typedef struct tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA;
typedef struct tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef NIM_CHAR tyArray_EWK8XzFKXCg2WflN3ijhqA[257];
typedef NIM_CHAR tyArray_4249al09aeC68W9cvqMnjIYOA[129];
typedef N_STDCALL_PTR(int, tyProc_As5z9bYt859cLKWaorPRgQYA) (NI16 wVersionRequired, WSADATA* WSData);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_CHAR tyArray_QQGLPNVVwLhYjkngqAxXQQ[4001];
struct tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ {
NI fd;
NIM_BOOL isBuffered;
union{
struct {tyArray_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
} S1;
} isBufferedU;
NIM_BOOL nonblocking;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyEnum_Protocol_hB5Btjev9bu2I7PAPRf7c6w;
typedef NU8 tyEnum_Domain_Bjy2oxSaLi9aMyifvsWxBnQ;
typedef NU8 tyEnum_SockType_4T9bvFMSAnW6LGgV3ydpJzQ;
typedef N_STDCALL_PTR(NI, tyProc_9aO2cP4IgwjXF8JfUR57CHQ) (int af, int typ, int protocol);
typedef N_STDCALL_PTR(int, tyProc_awTV7srwWeJ9cGPOCgBQa7g) (NI s, long cmd, long* argptr);
typedef N_STDCALL_PTR(int, tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w) (NI s, void* buf, int len, int flags);
struct tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ {
int ai_flags;
int ai_family;
int ai_socktype;
int ai_protocol;
size_t ai_addrlen;
NCSTRING ai_canonname;
SOCKADDR* ai_addr;
tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai_next;
};
typedef N_STDCALL_PTR(int, tyProc_MvjKU9c5nvs0N3IrS4vNgSw) (NCSTRING nodename, NCSTRING servname, tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* hints, tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ** res);
typedef N_STDCALL_PTR(int, tyProc_T129bsPZ4FvuSF4rGFSBKkg) (NI s, SOCKADDR* name, unsigned int namelen);
typedef N_STDCALL_PTR(void, tyProc_IV3cwg4tBg3JP8ITSKt7oQ) (tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai);
typedef N_STDCALL_PTR(int, tyProc_IQbFr9cLT9bipWCXYfwYwjOw) (NI s);
typedef NIM_CHAR tyArray_1NlJ8ipZDU6GZ9bDFAyQjfQ[8];
typedef N_STDCALL_PTR(int, tyProc_wy9bpl6t1mtPtDWeg0xLpDA) (NI s, int backlog);
typedef N_STDCALL_PTR(NI, tyProc_v29cxQYDpNcYLQEZV01BR5g) (NI s, SOCKADDR* a, unsigned int* addrlen);
typedef N_STDCALL_PTR(NCSTRING, tyProc_MgrHyJlVVXQLRahsT9c14gQ) (IN_ADDR i);
struct tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA {
NI32 tv_sec;
NI32 tv_usec;
};
typedef NI tyArray_SLBTEB08vk46ttuRaTxAYw[64];
struct tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog {
int fd_count;
tyArray_SLBTEB08vk46ttuRaTxAYw fd_array;
};
typedef N_STDCALL_PTR(int, tyProc_rWrG4X5lbcXQyLNkF9aNWhQ) (int nfds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* readfds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* writefds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* exceptfds, tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA* timeout);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
typedef NU8 tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg;
typedef NU8 tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw;
typedef NU8 tyEnum_SOBool_qY5afbczMeenVKcifqQxQg;
typedef N_STDCALL_PTR(int, tyProc_K6tJduk9ckQgneh7oD8F4Bg) (NI s, int level, int optname, void* optval, unsigned int optlen);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
typedef NIM_CHAR tyArray_NSMq3FMCIrS8gSbyinBZ8w[14];
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NI align;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9agrCtWKhCnWWMJpKKugJag[16];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9agrCtWKhCnWWMJpKKugJag bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9agrCtWKhCnWWMJpKKugJag bits;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_bTfD0pPidBST9bT9bmQFkEdg {
  TGenericSeq Sup;
  tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_9bdZBDTfBOjOcVVodbA2otw)(void);
static N_NIMCALL(void, Marker_tyRef_cOUvSWxuQTnH5Tt9bNSuuDw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*, newTSocket_47SzfEE5QS3I6WeeMUOKhQ)(NI fd, NIM_BOOL isBuff);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, FieldDiscriminantCheck)(NI oldDiscVal, NI newDiscVal, TNimNode** a, NI L);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(NI, send_WXPjALWv6pg9beQZkAUGAcw)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, void* data, NI size);
N_LIB_PRIVATE N_NIMCALL(int, toInt_9ckZlFHVRQCrf9a3K3Hk2ykg)(tyEnum_Domain_Bjy2oxSaLi9aMyifvsWxBnQ domain);
N_LIB_PRIVATE N_NIMCALL(int, toInt_6SFUoE2huyo9c72rGWmFN6A)(tyEnum_SockType_4T9bvFMSAnW6LGgV3ydpJzQ typ);
N_LIB_PRIVATE N_NIMCALL(int, toInt_hZgPgY6HFfhi6zjpqhMhtw)(tyEnum_Protocol_hB5Btjev9bu2I7PAPRf7c6w p);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__rzAI8EMyNBAQwGODeohhAA)(NU64 x);
N_LIB_PRIVATE N_NIMCALL(NI16, ntohs_rADiZfiQwv4wJCR2h5eMCA)(NI16 x);
N_LIB_PRIVATE N_NIMCALL(NI32, ntohl_Lv48cDIdk9cDv9cEDrXZ7uSQ)(NI32 x);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA, timeValFromMilliseconds_NIte9cl59aaaR2tw3QnZgo9bw)(NI timeout);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, createFdSet_KpofmEKnwuZMokQawJcchQ)(tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* fd, tySequence_bTfD0pPidBST9bT9bmQFkEdg* s, NI* m);
N_LIB_PRIVATE N_NIMCALL(void, FD_ZERO_yeePfMmq9aNgPmxq9aV4wa4A)(tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* s);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, FD_SET_RyfVGaM8zBlYSZOQ5CvEEQ)(NI socket_0, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* s);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, pruneSocketSet_yhKN7mCFg7gC9a9co4guWCXA)(tySequence_bTfD0pPidBST9bT9bmQFkEdg** s, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* fd);
N_LIB_PRIVATE N_NIMCALL(int, FD_ISSET_NkjjeLx4p9b4GT29buKQYcxA)(NI socket_0, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* set);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_7EL8Zq3xF2ujDWgp3bAEogsystem)(void* p, NI size);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(NI, recv_WXPjALWv6pg9beQZkAUGAcw_2)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, void* data, NI size);
N_LIB_PRIVATE N_NIMCALL(NI, readIntoBuf_nYUySyzaV1z9bLM1uYkWDsw)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NI32 flags);
static N_INLINE(void, copyMem_fPlwH3r9agN9aEHB6yCPMh0wsystem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NI, peekChar_yvFqgxh8V169ciAXvPCcd7g)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NIM_CHAR* c);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, raiseSocketError_pS2otRA79aO1ctxOIlhpXgw)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NI err, NIM_BOOL async);
N_LIB_PRIVATE N_NIMCALL(int, toCInt_26J2CiwBhk9clpsA6MQOH8w)(tyEnum_SOBool_qY5afbczMeenVKcifqQxQg opt);
N_LIB_PRIVATE N_NIMCALL(NI, checkBuffer_aAVQct6lZ5x9cb0hbJJsyeA)(tySequence_bTfD0pPidBST9bT9bmQFkEdg** readfds);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasDataBuffered_LkL3W9bGq7xFDN9a9c1LFIpuw)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* s);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, acceptAddr_PNW7a0XAnzN1Vc9aiqZmcmQ)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* server, tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ** client, NimStringDesc** address);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
NI osInvalidSocket_Cd5FXu8AR5CJVkibL4fIlg;
WSADATA wsa_kip9aLoJVEKbO857Iek9awvA;
extern tyProc_As5z9bYt859cLKWaorPRgQYA Dl_141146_;
TNimType NTI_0npQHvqsTpGEM2MQEwnDKQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_QQGLPNVVwLhYjkngqAxXQQ_;
TNimType NTI_cOUvSWxuQTnH5Tt9bNSuuDw_;
TNimType NTI_hB5Btjev9bu2I7PAPRf7c6w_;
extern TNimNode* NimDT__0npQHvqsTpGEM2MQEwnDKQ_isBuffered[3];
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_9aO2cP4IgwjXF8JfUR57CHQ Dl_140999_;
static void* TM_Eup9aWRghLcrbvSbC7oHuCw_9;
tyProc_awTV7srwWeJ9cGPOCgBQa7g Dl_322052_;
extern tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w Dl_141084_;
extern tyProc_MvjKU9c5nvs0N3IrS4vNgSw Dl_141151_;
extern tyProc_T129bsPZ4FvuSF4rGFSBKkg Dl_141020_;
extern tyProc_IV3cwg4tBg3JP8ITSKt7oQ Dl_141160_;
extern tyProc_IQbFr9cLT9bipWCXYfwYwjOw Dl_141004_;
extern tyProc_T129bsPZ4FvuSF4rGFSBKkg Dl_141014_;
extern tyProc_wy9bpl6t1mtPtDWeg0xLpDA Dl_141055_;
extern tyProc_v29cxQYDpNcYLQEZV01BR5g Dl_141007_;
extern tyProc_MgrHyJlVVXQLRahsT9c14gQ Dl_141164_;
extern tyProc_rWrG4X5lbcXQyLNkF9aNWhQ Dl_141075_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w Dl_141059_;
extern tyProc_K6tJduk9ckQgneh7oD8F4Bg Dl_141048_;
extern TNimType NTI_bTfD0pPidBST9bT9bmQFkEdg_;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
STRING_LITERAL(TM_Eup9aWRghLcrbvSbC7oHuCw_2, "", 0);
TNimNode* NimDT__0npQHvqsTpGEM2MQEwnDKQ_isBuffered[3];
STRING_LITERAL(TM_Eup9aWRghLcrbvSbC7oHuCw_8, "currPos", 7);
STRING_LITERAL(TM_Eup9aWRghLcrbvSbC7oHuCw_11, "ws2_32.dll", 10);
STRING_LITERAL(TM_Eup9aWRghLcrbvSbC7oHuCw_12, "ws2_32.dll", 10);
STRING_LITERAL(TM_Eup9aWRghLcrbvSbC7oHuCw_15, "bufLen", 6);
STRING_LITERAL(TM_Eup9aWRghLcrbvSbC7oHuCw_16, "\012not (client == nil) ", 21);
STRING_LITERAL(TM_Eup9aWRghLcrbvSbC7oHuCw_22, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_Eup9aWRghLcrbvSbC7oHuCw_28, "buffer", 6);
STRING_LITERAL(TM_Eup9aWRghLcrbvSbC7oHuCw_38, "This function cannot be used on non-blocking sockets.", 53);
STRING_LITERAL(TM_Eup9aWRghLcrbvSbC7oHuCw_39, "Could not send all data.", 24);
static N_NIMCALL(void, Marker_tyRef_cOUvSWxuQTnH5Tt9bNSuuDw)(void* p, NI op) {
	tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* a;
	NI T1_;
	a = (tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*)p;
	switch ((*a).isBuffered) {
	case NIM_TRUE:
	T1_ = (NI)0;
	break;
	case NIM_FALSE:
	break;
	} 
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*, newTSocket_47SzfEE5QS3I6WeeMUOKhQ)(NI fd, NIM_BOOL isBuff) {
	tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* result;
	NIM_BOOL T5_;
	nimfr_("newTSocket", "sockets.nim");
{	result = (tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*)0;
	nimln_(167, "sockets.nim");
	{
		if (!(fd == osInvalidSocket_Cd5FXu8AR5CJVkibL4fIlg)) goto LA3_;
		nimln_(168, "sockets.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(169, "sockets.nim");
	result = (tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*) newObj((&NTI_cOUvSWxuQTnH5Tt9bNSuuDw_), sizeof(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ));
	nimln_(170, "sockets.nim");
	(*result).fd = fd;
	nimln_(171, "sockets.nim");
	T5_ = (NIM_BOOL)0;
	T5_ = isBuff;
	FieldDiscriminantCheck((NI)(NU)((*result).isBuffered), (NI)(NU)(T5_), NimDT__0npQHvqsTpGEM2MQEwnDKQ_isBuffered, 3);
	(*result).isBuffered = T5_;
	nimln_(172, "sockets.nim");
	{
		if (!isBuff) goto LA8_;
		if (!(((2 &(1U<<((NU)((*result).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_8));
		nimln_(173, "sockets.nim");
		(*result).isBufferedU.S1.currPos = ((NI) 0);
	}
	LA8_: ;
	nimln_(174, "sockets.nim");
	(*result).nonblocking = NIM_FALSE;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*, socket_hIq41Z3o42tkUr3ybgCXZw)(tyEnum_Domain_Bjy2oxSaLi9aMyifvsWxBnQ domain, tyEnum_SockType_4T9bvFMSAnW6LGgV3ydpJzQ typ, tyEnum_Protocol_hB5Btjev9bu2I7PAPRf7c6w protocol, NIM_BOOL buffered) {
	tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* result;
	NI T1_;
	nimfr_("socket", "sockets.nim");
	result = (tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*)0;
	nimln_(265, "sockets.nim");
	T1_ = (NI)0;
	T1_ = Dl_140999_(((int) (domain)), ((int) (typ)), ((int) (protocol)));
	result = newTSocket_47SzfEE5QS3I6WeeMUOKhQ(T1_, buffered);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setBlocking_2yOVbysWOMsZ9c4y2yNm6gQ)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* s, NIM_BOOL blocking) {
	long mode;
	nimfr_("setBlocking", "sockets.nim");
	nimln_(1703, "sockets.nim");
	mode = ((long) (!(blocking)));
	nimln_(1704, "sockets.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = Dl_322052_((*s).fd, ((NI32) -2147195266), (&mode));
		if (!(T3_ == ((NI32) -1))) goto LA4_;
		nimln_(1705, "sockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
	}
	LA4_: ;
	nimln_(1714, "sockets.nim");
	(*s).nonblocking = !(blocking);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, send_WXPjALWv6pg9beQZkAUGAcw)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, void* data, NI size) {
	NI result;
	int T1_;
	nimfr_("send", "sockets.nim");
	result = (NI)0;
	nimln_(1592, "sockets.nim");
	T1_ = (int)0;
	T1_ = Dl_141084_((*socket_0).fd, data, ((int) (size)), ((NI32) 0));
	result = ((NI) (T1_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, sendAsync_9cQkh6O6JzJjWkGHk3CK1vw)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NimStringDesc* data) {
	NI result;
	nimfr_("sendAsync", "sockets.nim");
{	result = (NI)0;
	nimln_(1621, "sockets.nim");
	result = send_WXPjALWv6pg9beQZkAUGAcw(socket_0, ((void*) (data->data)), (data ? data->Sup.len : 0));
	nimln_(1640, "sockets.nim");
	{
		NI32 err;
		if (!(result == ((NI) -1))) goto LA3_;
		nimln_(1641, "sockets.nim");
		err = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		nimln_(1643, "sockets.nim");
		{
			if (!(err == ((NI32) 10036))) goto LA7_;
			nimln_(1644, "sockets.nim");
			result = ((NI) 0);
			goto BeforeRet_;
		}
		goto LA5_;
		LA7_: ;
		{
			nimln_(1645, "sockets.nim");
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(err, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
		}
		LA5_: ;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, getFD_kg6UtAfyArHG8QBjly5deQ)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0) {
	NI result;
	nimfr_("getFD", "sockets.nim");
{	result = (NI)0;
	nimln_(1745, "sockets.nim");
	result = (*socket_0).fd;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasDataBuffered_LkL3W9bGq7xFDN9a9c1LFIpuw)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* s) {
	NIM_BOOL result;
	nimfr_("hasDataBuffered", "sockets.nim");
	result = (NIM_BOOL)0;
	nimln_(979, "sockets.nim");
	result = NIM_FALSE;
	nimln_(980, "sockets.nim");
	{
		NIM_BOOL T5_;
		if (!(*s).isBuffered) goto LA3_;
		nimln_(981, "sockets.nim");
		T5_ = (NIM_BOOL)0;
		if (!(((2 &(1U<<((NU)((*s).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_15));
		T5_ = (((NI) 0) < (*s).isBufferedU.S1.bufLen);
		if (!(T5_)) goto LA6_;
		nimln_(398, "system.nim");
		nimln_(981, "sockets.nim");
		if (!(((2 &(1U<<((NU)((*s).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_8));
		if (!(((2 &(1U<<((NU)((*s).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_15));
		T5_ = !(((*s).isBufferedU.S1.currPos == (*s).isBufferedU.S1.bufLen));
		LA6_: ;
		result = T5_;
	}
	LA3_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, toInt_9ckZlFHVRQCrf9a3K3Hk2ykg)(tyEnum_Domain_Bjy2oxSaLi9aMyifvsWxBnQ domain) {
	int result;
	nimfr_("toInt", "sockets.nim");
	result = (int)0;
	nimln_(251, "sockets.nim");
	result = ((int) (((NI16)(NU16)(NU)(domain))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, toInt_6SFUoE2huyo9c72rGWmFN6A)(tyEnum_SockType_4T9bvFMSAnW6LGgV3ydpJzQ typ) {
	int result;
	nimfr_("toInt", "sockets.nim");
	result = (int)0;
	nimln_(254, "sockets.nim");
	result = ((int) (typ));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, toInt_hZgPgY6HFfhi6zjpqhMhtw)(tyEnum_Protocol_hB5Btjev9bu2I7PAPRf7c6w p) {
	int result;
	nimfr_("toInt", "sockets.nim");
	result = (int)0;
	nimln_(257, "sockets.nim");
	result = ((int) (p));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, connectAsync_bMXzVwvRhOGFAqC2VCqGuQ)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NimStringDesc* name, NU16 port, tyEnum_Domain_Bjy2oxSaLi9aMyifvsWxBnQ af) {
	tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ hints;
	tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* aiList;
	int gaiResult;
	NimStringDesc* T1_;
	NIM_BOOL success;
	NI32 lastError;
	tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* it;
	nimfr_("connectAsync", "sockets.nim");
	memset((void*)(&hints), 0, sizeof(hints));
	nimln_(878, "sockets.nim");
	aiList = NIM_NIL;
	nimln_(879, "sockets.nim");
	hints.ai_family = toInt_9ckZlFHVRQCrf9a3K3Hk2ykg(af);
	nimln_(880, "sockets.nim");
	hints.ai_socktype = toInt_6SFUoE2huyo9c72rGWmFN6A(((tyEnum_SockType_4T9bvFMSAnW6LGgV3ydpJzQ) 1));
	nimln_(881, "sockets.nim");
	hints.ai_protocol = toInt_hZgPgY6HFfhi6zjpqhMhtw(((tyEnum_Protocol_hB5Btjev9bu2I7PAPRf7c6w) 6));
	nimln_(448, "sockets.nim");
	nimln_(882, "sockets.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = dollar__rzAI8EMyNBAQwGODeohhAA(port);
	gaiResult = Dl_141151_(name->data, T1_->data, (&hints), &aiList);
	{
		NI32 T6_;
		nimln_(398, "system.nim");
		nimln_(449, "sockets.nim");
		if (!!((gaiResult == ((NI32) 0)))) goto LA4_;
		nimln_(451, "sockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
	}
	LA4_: ;
	nimln_(884, "sockets.nim");
	success = NIM_FALSE;
	lastError = (NI32)0;
	nimln_(886, "sockets.nim");
	it = aiList;
	{
		nimln_(887, "sockets.nim");
		while (1) {
			int ret;
			nimln_(398, "system.nim");
			nimln_(887, "sockets.nim");
			if (!!((it == NIM_NIL))) goto LA8;
			nimln_(888, "sockets.nim");
			ret = Dl_141020_((*socket_0).fd, (*it).ai_addr, ((unsigned int) ((*it).ai_addrlen)));
			nimln_(889, "sockets.nim");
			{
				if (!(ret == ((NI32) 0))) goto LA11_;
				nimln_(890, "sockets.nim");
				success = NIM_TRUE;
				nimln_(891, "sockets.nim");
				goto LA7;
			}
			goto LA9_;
			LA11_: ;
			{
				nimln_(893, "sockets.nim");
				lastError = osLastError_9bdZBDTfBOjOcVVodbA2otw();
				nimln_(896, "sockets.nim");
				{
					if (!(lastError == ((NI32) 10035))) goto LA16_;
					nimln_(897, "sockets.nim");
					success = NIM_TRUE;
					nimln_(898, "sockets.nim");
					goto LA7;
				}
				LA16_: ;
			}
			LA9_: ;
			nimln_(904, "sockets.nim");
			it = (*it).ai_next;
		} LA8: ;
	} LA7: ;
	nimln_(906, "sockets.nim");
	Dl_141160_(aiList);
	nimln_(907, "sockets.nim");
	{
		if (!!(success)) goto LA20_;
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(lastError, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
	}
	LA20_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, close_NjyMDfTHg89c25LoSxFJ9bBA)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0) {
	int T1_;
	nimfr_("close", "sockets.nim");
	nimln_(662, "sockets.nim");
	T1_ = (int)0;
	T1_ = Dl_141004_((*socket_0).fd);
	T1_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI16, ntohs_rADiZfiQwv4wJCR2h5eMCA)(NI16 x) {
	NI16 result;
	nimfr_("ntohs", "sockets.nim");
	result = (NI16)0;
	nimln_(197, "sockets.nim");
	result = (NI16)((NI16)((NU16)(x) >> (NU16)(((NI16) 8))) | (NI16)((NU16)(x) << (NU16)(((NI16) 8))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI32, ntohl_Lv48cDIdk9cDv9cEDrXZ7uSQ)(NI32 x) {
	NI32 result;
	nimfr_("ntohl", "sockets.nim");
	result = (NI32)0;
	nimln_(188, "sockets.nim");
	nimln_(187, "sockets.nim");
	nimln_(188, "sockets.nim");
	nimln_(189, "sockets.nim");
	nimln_(190, "sockets.nim");
	result = (NI32)((NI32)((NI32)((NI32)((NU32)(x) >> (NU32)(((NI32) 24))) | (NI32)((NI32)((NU32)(x) >> (NU32)(((NI32) 8))) & ((NI32) 65280))) | (NI32)((NI32)((NU32)(x) << (NU32)(((NI32) 8))) & ((NI32) 16711680))) | (NI32)((NU32)(x) << (NU32)(((NI32) 24))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, bindAddr_RFrj3TNNZuD7msYELSbldA)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NU16 port, NimStringDesc* address) {
	nimfr_("bindAddr", "sockets.nim");
	nimln_(461, "sockets.nim");
	{
		SOCKADDR_IN name;
		NI16 T5_;
		NI32 T6_;
		if (!((address) && (address)->Sup.len == 0)) goto LA3_;
		memset((void*)(&name), 0, sizeof(name));
		nimln_(464, "sockets.nim");
		name.sin_family = ((NI16) 2);
		nimln_(467, "sockets.nim");
		nimln_(215, "sockets.nim");
		T5_ = (NI16)0;
		T5_ = ntohs_rADiZfiQwv4wJCR2h5eMCA(((NI16) (port)));
		name.sin_port = ((NU16) (T5_));
		nimln_(468, "sockets.nim");
		nimln_(212, "sockets.nim");
		T6_ = (NI32)0;
		T6_ = ntohl_Lv48cDIdk9cDv9cEDrXZ7uSQ(((NI32) (((NU32) 0))));
		name.sin_addr.s_addr = ((NU32) (T6_));
		nimln_(469, "sockets.nim");
		{
			int T9_;
			NI32 T12_;
			nimln_(470, "sockets.nim");
			T9_ = (int)0;
			T9_ = Dl_141014_((*socket_0).fd, ((SOCKADDR*) ((&name))), ((unsigned int) (((NI)sizeof(SOCKADDR_IN)))));
			if (!(T9_ < ((NI32) 0))) goto LA10_;
			nimln_(471, "sockets.nim");
			T12_ = (NI32)0;
			T12_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T12_, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
		}
		LA10_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ hints;
		tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* aiList;
		int gaiResult;
		NimStringDesc* T14_;
		memset((void*)(&hints), 0, sizeof(hints));
		nimln_(474, "sockets.nim");
		aiList = NIM_NIL;
		nimln_(475, "sockets.nim");
		hints.ai_family = toInt_9ckZlFHVRQCrf9a3K3Hk2ykg(((tyEnum_Domain_Bjy2oxSaLi9aMyifvsWxBnQ) 2));
		nimln_(476, "sockets.nim");
		hints.ai_socktype = toInt_6SFUoE2huyo9c72rGWmFN6A(((tyEnum_SockType_4T9bvFMSAnW6LGgV3ydpJzQ) 1));
		nimln_(477, "sockets.nim");
		hints.ai_protocol = toInt_hZgPgY6HFfhi6zjpqhMhtw(((tyEnum_Protocol_hB5Btjev9bu2I7PAPRf7c6w) 6));
		nimln_(448, "sockets.nim");
		nimln_(478, "sockets.nim");
		T14_ = (NimStringDesc*)0;
		T14_ = dollar__rzAI8EMyNBAQwGODeohhAA(port);
		gaiResult = Dl_141151_(address->data, T14_->data, (&hints), &aiList);
		{
			NI32 T19_;
			nimln_(398, "system.nim");
			nimln_(449, "sockets.nim");
			if (!!((gaiResult == ((NI32) 0)))) goto LA17_;
			nimln_(451, "sockets.nim");
			T19_ = (NI32)0;
			T19_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T19_, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
		}
		LA17_: ;
		nimln_(479, "sockets.nim");
		{
			int T22_;
			NI32 T25_;
			T22_ = (int)0;
			T22_ = Dl_141014_((*socket_0).fd, (*aiList).ai_addr, ((unsigned int) ((*aiList).ai_addrlen)));
			if (!(T22_ < ((NI32) 0))) goto LA23_;
			nimln_(480, "sockets.nim");
			T25_ = (NI32)0;
			T25_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T25_, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
		}
		LA23_: ;
	}
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, listen_drBTE9bG3Kk9agesqZoZA3wA)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, int backlog) {
	nimfr_("listen", "sockets.nim");
	nimln_(413, "sockets.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = Dl_141055_((*socket_0).fd, backlog);
		if (!(T3_ < ((NI32) 0))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
	}
	LA4_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, acceptAddr_PNW7a0XAnzN1Vc9aiqZmcmQ)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* server, tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ** client, NimStringDesc** address) {
	SOCKADDR_IN sockAddress;
	unsigned int addrLen;
	NI sock;
	nimfr_("acceptAddr", "sockets.nim");
{	nimln_(499, "sockets.nim");
	{
		if (!!(!(((*client) == NIM_NIL)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_16));
	}
	LA3_: ;
	memset((void*)(&sockAddress), 0, sizeof(sockAddress));
	nimln_(501, "sockets.nim");
	addrLen = ((unsigned int) (((NI)sizeof(SOCKADDR_IN))));
	nimln_(502, "sockets.nim");
	sock = Dl_141007_((*server).fd, ((SOCKADDR*) ((&sockAddress))), (&addrLen));
	nimln_(554, "sockets.nim");
	{
		NI32 err;
		nimln_(505, "sockets.nim");
		if (!(sock == osInvalidSocket_Cd5FXu8AR5CJVkibL4fIlg)) goto LA7_;
		nimln_(506, "sockets.nim");
		err = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		nimln_(508, "sockets.nim");
		{
			if (!(err == ((NI32) 10036))) goto LA11_;
			nimln_(157, "sockets.nim");
			unsureAsgnRef((void**) (&(*client)), NIM_NIL);
			nimln_(510, "sockets.nim");
			unsureAsgnRef((void**) (&(*address)), copyString(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2)));
			nimln_(512, "sockets.nim");
			goto BeforeRet_;
		}
		goto LA9_;
		LA11_: ;
		{
			nimln_(515, "sockets.nim");
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(err, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
		}
		LA9_: ;
	}
	goto LA5_;
	LA7_: ;
	{
		NIM_BOOL T15_;
		NCSTRING T16_;
		nimln_(526, "sockets.nim");
		(*(*client)).fd = sock;
		nimln_(527, "sockets.nim");
		T15_ = (NIM_BOOL)0;
		T15_ = (*server).isBuffered;
		FieldDiscriminantCheck((NI)(NU)((*(*client)).isBuffered), (NI)(NU)(T15_), NimDT__0npQHvqsTpGEM2MQEwnDKQ_isBuffered, 3);
		(*(*client)).isBuffered = T15_;
		nimln_(530, "sockets.nim");
		T16_ = (NCSTRING)0;
		T16_ = Dl_141164_(sockAddress.sin_addr);
		unsureAsgnRef((void**) (&(*address)), cstrToNimstr(T16_));
		nimln_(532, "sockets.nim");
		goto BeforeRet_;
	}
	LA5_: ;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, raiseSocketError_pS2otRA79aO1ctxOIlhpXgw)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NI err, NIM_BOOL async) {
	nimfr_("raiseSocketError", "sockets.nim");
{	nimln_(396, "sockets.nim");
	{
		NIM_BOOL T3_;
		NI32 lastError;
		T3_ = (NIM_BOOL)0;
		T3_ = (err == ((NI) -1));
		if (!(T3_)) goto LA4_;
		T3_ = NIM_TRUE;
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(397, "sockets.nim");
		lastError = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		nimln_(398, "sockets.nim");
		{
			if (!async) goto LA9_;
			nimln_(400, "sockets.nim");
			{
				if (!(lastError == ((NI32) 10035))) goto LA13_;
				nimln_(401, "sockets.nim");
				goto BeforeRet_;
			}
			goto LA11_;
			LA13_: ;
			{
				nimln_(402, "sockets.nim");
				raiseOSError_bEwAamo1N7TKcaU9akpiyIg(lastError, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
			}
			LA11_: ;
		}
		goto LA7_;
		LA9_: ;
		{
			nimln_(407, "sockets.nim");
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(lastError, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
		}
		LA7_: ;
	}
	LA5_: ;
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (-2147483647 -1)));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA, timeValFromMilliseconds_NIte9cl59aaaR2tw3QnZgo9bw)(NI timeout) {
	tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA result;
	nimfr_("timeValFromMilliseconds", "sockets.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(954, "sockets.nim");
	{
		NI seconds;
		NI TM_Eup9aWRghLcrbvSbC7oHuCw_17;
		NI TM_Eup9aWRghLcrbvSbC7oHuCw_18;
		NI TM_Eup9aWRghLcrbvSbC7oHuCw_19;
		NI TM_Eup9aWRghLcrbvSbC7oHuCw_20;
		nimln_(398, "system.nim");
		nimln_(954, "sockets.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3_;
		nimln_(955, "sockets.nim");
		TM_Eup9aWRghLcrbvSbC7oHuCw_17 = divInt(timeout, ((NI) 1000));
		seconds = (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_17);
		nimln_(956, "sockets.nim");
		result.tv_sec = ((NI32) (seconds));
		nimln_(957, "sockets.nim");
		TM_Eup9aWRghLcrbvSbC7oHuCw_18 = mulInt(seconds, ((NI) 1000));
		TM_Eup9aWRghLcrbvSbC7oHuCw_19 = subInt(timeout, (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_18));
		TM_Eup9aWRghLcrbvSbC7oHuCw_20 = mulInt((NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_19), ((NI) 1000));
		result.tv_usec = ((NI32) ((NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_20)));
	}
	LA3_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, createFdSet_KpofmEKnwuZMokQawJcchQ)(tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* fd, tySequence_bTfD0pPidBST9bT9bmQFkEdg* s, NI* m) {
	nimfr_("createFdSet", "sockets.nim");
	nimln_(960, "sockets.nim");
	FD_ZERO_yeePfMmq9aNgPmxq9aV4wa4A(fd);
	{
		tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* i;
		NI i_2;
		NI L;
		NI T2_;
		i = (tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*)0;
		nimln_(3805, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (s ? s->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_Eup9aWRghLcrbvSbC7oHuCw_21;
				if (!(i_2 < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i_2) >= (NU)(s->Sup.len)) raiseIndexError();
				i = s->data[i_2];
				nimln_(962, "sockets.nim");
				(*m) = (((*m) >= (*i).fd) ? (*m) : (*i).fd);
				nimln_(963, "sockets.nim");
				FD_SET_RyfVGaM8zBlYSZOQ5CvEEQ((*i).fd, fd);
				nimln_(3809, "system.nim");
				TM_Eup9aWRghLcrbvSbC7oHuCw_21 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_21);
				nimln_(3810, "system.nim");
				{
					NI T7_;
					T7_ = (s ? s->Sup.len : 0);
					if (!!((T7_ == L))) goto LA8_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_22));
				}
				LA8_: ;
			} LA4: ;
		}
	}
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU32)(((NI) (ptrdiff_t) (usr))) - (NU32)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU32)((*c_2).refcount) < (NU32)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_7EL8Zq3xF2ujDWgp3bAEogsystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) 1073741823)) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) 1073741823)));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 8)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU32)((NI)((NU32)(((NI) (ptrdiff_t) (result))) + (NU32)(((NI) 8)))) + (NU32)((NI)((NU32)(i) * (NU32)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_7EL8Zq3xF2ujDWgp3bAEogsystem(((void*) ((NI)((NU32)((NI)((NU32)(((NI) (ptrdiff_t) (result))) + (NU32)(((NI) 8)))) + (NU32)((NI)((NU32)(newLen) * (NU32)(elemSize)))))), ((NI) ((NI)((NU32)((NI)((NU32)((*result).len) - (NU32)(newLen))) * (NU32)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, pruneSocketSet_yhKN7mCFg7gC9a9co4guWCXA)(tySequence_bTfD0pPidBST9bT9bmQFkEdg** s, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* fd) {
	NI i;
	NI L;
	NI T1_;
	nimfr_("pruneSocketSet", "sockets.nim");
	nimln_(966, "sockets.nim");
	i = ((NI) 0);
	nimln_(967, "sockets.nim");
	T1_ = ((*s) ? (*s)->Sup.len : 0);
	L = T1_;
	{
		nimln_(968, "sockets.nim");
		while (1) {
			if (!(i < L)) goto LA3;
			nimln_(969, "sockets.nim");
			{
				int T6_;
				NI TM_Eup9aWRghLcrbvSbC7oHuCw_25;
				NI TM_Eup9aWRghLcrbvSbC7oHuCw_26;
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				T6_ = (int)0;
				T6_ = FD_ISSET_NkjjeLx4p9b4GT29buKQYcxA((*(*s)->data[i]).fd, fd);
				if (!(T6_ == ((NI32) 0))) goto LA7_;
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				nimln_(971, "sockets.nim");
				TM_Eup9aWRghLcrbvSbC7oHuCw_25 = subInt(L, ((NI) 1));
				if ((NU)((NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_25)) >= (NU)((*s)->Sup.len)) raiseIndexError();
				asgnRefNoCycle((void**) (&(*s)->data[i]), (*s)->data[(NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_25)]);
				nimln_(972, "sockets.nim");
				TM_Eup9aWRghLcrbvSbC7oHuCw_26 = subInt(L, ((NI) 1));
				L = (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_26);
			}
			goto LA4_;
			LA7_: ;
			{
				NI TM_Eup9aWRghLcrbvSbC7oHuCw_27;
				nimln_(974, "sockets.nim");
				TM_Eup9aWRghLcrbvSbC7oHuCw_27 = addInt(i, ((NI) 1));
				i = (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_27);
			}
			LA4_: ;
		} LA3: ;
	}
	nimln_(975, "sockets.nim");
	(*s) = (tySequence_bTfD0pPidBST9bT9bmQFkEdg*) setLengthSeq(&((*s))->Sup, sizeof(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*), ((NI)chckRange(L, ((NI) 0), ((NI) 2147483647))));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, selectWrite_cHf09brecr7vURt9bzrI9b9a7A)(tySequence_bTfD0pPidBST9bT9bmQFkEdg** writefds, NI timeout) {
	NI result;
	tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA tv;
	tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog wr;
	NI m;
	nimfr_("selectWrite", "sockets.nim");
	result = (NI)0;
	nimln_(1060, "sockets.nim");
	tv = timeValFromMilliseconds_NIte9cl59aaaR2tw3QnZgo9bw(timeout);
	memset((void*)(&wr), 0, sizeof(wr));
	nimln_(1063, "sockets.nim");
	m = ((NI) 0);
	nimln_(1064, "sockets.nim");
	createFdSet_KpofmEKnwuZMokQawJcchQ((&wr), (*writefds), (&m));
	nimln_(1066, "sockets.nim");
	{
		NI TM_Eup9aWRghLcrbvSbC7oHuCw_23;
		int T5_;
		nimln_(398, "system.nim");
		nimln_(1066, "sockets.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3_;
		nimln_(1067, "sockets.nim");
		TM_Eup9aWRghLcrbvSbC7oHuCw_23 = addInt(m, ((NI) 1));
		T5_ = (int)0;
		T5_ = Dl_141075_(((int) ((NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_23))), NIM_NIL, (&wr), NIM_NIL, (&tv));
		result = ((NI) (T5_));
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_Eup9aWRghLcrbvSbC7oHuCw_24;
		int T7_;
		nimln_(1069, "sockets.nim");
		TM_Eup9aWRghLcrbvSbC7oHuCw_24 = addInt(m, ((NI) 1));
		T7_ = (int)0;
		T7_ = Dl_141075_(((int) ((NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_24))), NIM_NIL, (&wr), NIM_NIL, NIM_NIL);
		result = ((NI) (T7_));
	}
	LA1_: ;
	nimln_(1071, "sockets.nim");
	pruneSocketSet_yhKN7mCFg7gC9a9co4guWCXA(writefds, (&wr));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, readIntoBuf_nYUySyzaV1z9bLM1uYkWDsw)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NI32 flags) {
	NI result;
	int T1_;
	nimfr_("readIntoBuf", "sockets.nim");
{	result = (NI)0;
	nimln_(1092, "sockets.nim");
	result = ((NI) 0);
	nimln_(1099, "sockets.nim");
	if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_28));
	T1_ = (int)0;
	T1_ = Dl_141059_((*socket_0).fd, ((void*) ((*socket_0).isBufferedU.S1.buffer)), ((int) 4000), flags);
	result = ((NI) (T1_));
	nimln_(1100, "sockets.nim");
	{
		if (!(result <= ((NI) 0))) goto LA4_;
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_15));
		nimln_(1101, "sockets.nim");
		(*socket_0).isBufferedU.S1.bufLen = ((NI) 0);
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_8));
		nimln_(1102, "sockets.nim");
		(*socket_0).isBufferedU.S1.currPos = ((NI) 0);
		nimln_(1103, "sockets.nim");
		goto BeforeRet_;
	}
	LA4_: ;
	if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_15));
	nimln_(1104, "sockets.nim");
	(*socket_0).isBufferedU.S1.bufLen = result;
	if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_8));
	nimln_(1105, "sockets.nim");
	(*socket_0).isBufferedU.S1.currPos = ((NI) 0);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_fPlwH3r9agN9aEHB6yCPMh0wsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

N_LIB_PRIVATE N_NIMCALL(NI, recv_WXPjALWv6pg9beQZkAUGAcw_2)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, void* data, NI size) {
	NI result;
	nimfr_("recv", "sockets.nim");
{	result = (NI)0;
	nimln_(1120, "sockets.nim");
	{
		if (!(size == ((NI) 0))) goto LA3_;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(1121, "sockets.nim");
	{
		NI read;
		if (!(*socket_0).isBuffered) goto LA7_;
		nimln_(1122, "sockets.nim");
		{
			NI res;
			if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_15));
			if (!((*socket_0).isBufferedU.S1.bufLen == ((NI) 0))) goto LA11_;
			nimln_(1108, "sockets.nim");
			res = readIntoBuf_nYUySyzaV1z9bLM1uYkWDsw(socket_0, ((NI32) 0));
			nimln_(1123, "sockets.nim");
			{
				nimln_(1109, "sockets.nim");
				if (!(res <= ((NI) 0))) goto LA15_;
				nimln_(1110, "sockets.nim");
				{
					if (!NIM_FALSE) goto LA19_;
					nimln_(1111, "sockets.nim");
					nimln_(1123, "sockets.nim");
					result = ((NI) 0);
					goto BeforeRet_;
				}
				goto LA17_;
				LA19_: ;
				{
					nimln_(1113, "sockets.nim");
					result = res;
					goto BeforeRet_;
				}
				LA17_: ;
			}
			LA15_: ;
		}
		LA11_: ;
		nimln_(1125, "sockets.nim");
		read = ((NI) 0);
		{
			nimln_(1126, "sockets.nim");
			while (1) {
				NI chunk;
				NI TM_Eup9aWRghLcrbvSbC7oHuCw_29;
				NI TM_Eup9aWRghLcrbvSbC7oHuCw_30;
				NCSTRING d;
				NI TM_Eup9aWRghLcrbvSbC7oHuCw_31;
				NI TM_Eup9aWRghLcrbvSbC7oHuCw_32;
				if (!(read < size)) goto LA23;
				nimln_(1127, "sockets.nim");
				{
					NI res_2;
					if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_15));
					if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_8));
					if (!((*socket_0).isBufferedU.S1.bufLen <= (*socket_0).isBufferedU.S1.currPos)) goto LA26_;
					nimln_(1108, "sockets.nim");
					res_2 = readIntoBuf_nYUySyzaV1z9bLM1uYkWDsw(socket_0, ((NI32) 0));
					nimln_(1128, "sockets.nim");
					{
						nimln_(1109, "sockets.nim");
						if (!(res_2 <= ((NI) 0))) goto LA30_;
						nimln_(1110, "sockets.nim");
						{
							if (!(((NI) 0) < read)) goto LA34_;
							nimln_(1111, "sockets.nim");
							nimln_(1128, "sockets.nim");
							result = read;
							goto BeforeRet_;
						}
						goto LA32_;
						LA34_: ;
						{
							nimln_(1113, "sockets.nim");
							result = res_2;
							goto BeforeRet_;
						}
						LA32_: ;
					}
					LA30_: ;
				}
				LA26_: ;
				nimln_(1130, "sockets.nim");
				if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_15));
				if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_8));
				TM_Eup9aWRghLcrbvSbC7oHuCw_29 = subInt((*socket_0).isBufferedU.S1.bufLen, (*socket_0).isBufferedU.S1.currPos);
				TM_Eup9aWRghLcrbvSbC7oHuCw_30 = subInt(size, read);
				chunk = (((NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_29) <= (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_30)) ? (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_29) : (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_30));
				nimln_(1131, "sockets.nim");
				d = ((NCSTRING) (data));
				nimln_(1132, "sockets.nim");
				if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_28));
				if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_8));
				if ((NU)((*socket_0).isBufferedU.S1.currPos) > (NU)(4000)) raiseIndexError();
				copyMem_fPlwH3r9agN9aEHB6yCPMh0wsystem(((void*) ((&d[read]))), ((void*) ((&(*socket_0).isBufferedU.S1.buffer[((*socket_0).isBufferedU.S1.currPos)- 0]))), ((NI)chckRange(chunk, ((NI) 0), ((NI) 2147483647))));
				nimln_(1133, "sockets.nim");
				TM_Eup9aWRghLcrbvSbC7oHuCw_31 = addInt(read, chunk);
				read = (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_31);
				nimln_(1134, "sockets.nim");
				if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_8));
				TM_Eup9aWRghLcrbvSbC7oHuCw_32 = addInt((*socket_0).isBufferedU.S1.currPos, chunk);
				(*socket_0).isBufferedU.S1.currPos = (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_32);
			} LA23: ;
		}
		nimln_(1136, "sockets.nim");
		result = read;
	}
	goto LA5_;
	LA7_: ;
	{
		int T38_;
		nimln_(1153, "sockets.nim");
		T38_ = (int)0;
		T38_ = Dl_141059_((*socket_0).fd, data, ((int) (size)), ((NI32) 0));
		result = ((NI) (T38_));
	}
	LA5_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, peekChar_yvFqgxh8V169ciAXvPCcd7g)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NIM_CHAR* c) {
	NI result;
	nimfr_("peekChar", "sockets.nim");
	result = (NI)0;
	nimln_(1242, "sockets.nim");
	{
		if (!(*socket_0).isBuffered) goto LA3_;
		nimln_(1243, "sockets.nim");
		result = ((NI) 1);
		nimln_(1244, "sockets.nim");
		{
			NIM_BOOL T7_;
			NI TM_Eup9aWRghLcrbvSbC7oHuCw_33;
			NI res;
			T7_ = (NIM_BOOL)0;
			if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_15));
			T7_ = ((*socket_0).isBufferedU.S1.bufLen == ((NI) 0));
			if (T7_) goto LA8_;
			if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_15));
			TM_Eup9aWRghLcrbvSbC7oHuCw_33 = subInt((*socket_0).isBufferedU.S1.bufLen, ((NI) 1));
			if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_8));
			T7_ = ((NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_33) < (*socket_0).isBufferedU.S1.currPos);
			LA8_: ;
			if (!T7_) goto LA9_;
			nimln_(1245, "sockets.nim");
			res = readIntoBuf_nYUySyzaV1z9bLM1uYkWDsw(socket_0, ((NI32) 0));
			nimln_(1246, "sockets.nim");
			{
				if (!(res <= ((NI) 0))) goto LA13_;
				nimln_(1247, "sockets.nim");
				result = res;
			}
			LA13_: ;
		}
		LA9_: ;
		nimln_(1249, "sockets.nim");
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_28));
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_8));
		if ((NU)((*socket_0).isBufferedU.S1.currPos) > (NU)(4000)) raiseIndexError();
		(*c) = (*socket_0).isBufferedU.S1.buffer[((*socket_0).isBufferedU.S1.currPos)- 0];
	}
	goto LA1_;
	LA3_: ;
	{
		int T16_;
		nimln_(1259, "sockets.nim");
		T16_ = (int)0;
		T16_ = Dl_141059_((*socket_0).fd, ((void*) (c)), ((int) 1), ((int) 2));
		result = ((NI) (T16_));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg, recvLineAsync_ApQM286RDA9bj0rolnjqJRg)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NimStringDesc** line) {
	tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg result;
	nimfr_("recvLineAsync", "sockets.nim");
{	result = (tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg)0;
	nimln_(1363, "sockets.nim");
	(*line) = setLengthStr((*line), ((NI) 0));
	{
		nimln_(1364, "sockets.nim");
		while (1) {
			NIM_CHAR c;
			NI n;
			c = (NIM_CHAR)0;
			nimln_(1366, "sockets.nim");
			n = recv_WXPjALWv6pg9beQZkAUGAcw_2(socket_0, ((void*) ((&c))), ((NI) 1));
			nimln_(1367, "sockets.nim");
			{
				if (!(n < ((NI) 0))) goto LA5_;
				nimln_(1368, "sockets.nim");
				{
					if (!(((*line) ? (*line)->Sup.len : 0) == ((NI) 0))) goto LA9_;
					result = ((tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg) 3);
				}
				goto LA7_;
				LA9_: ;
				{
					result = ((tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg) 1);
				}
				LA7_: ;
				goto BeforeRet_;
			}
			goto LA3_;
			LA5_: ;
			{
				nimln_(1369, "sockets.nim");
				if (!(n == ((NI) 0))) goto LA13_;
				nimln_(1370, "sockets.nim");
				{
					if (!(((*line) ? (*line)->Sup.len : 0) == ((NI) 0))) goto LA17_;
					result = ((tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg) 2);
				}
				goto LA15_;
				LA17_: ;
				{
					result = ((tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg) 1);
				}
				LA15_: ;
				goto BeforeRet_;
			}
			goto LA3_;
			LA13_: ;
			LA3_: ;
			nimln_(1371, "sockets.nim");
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA22_;
				nimln_(1372, "sockets.nim");
				n = peekChar_yvFqgxh8V169ciAXvPCcd7g(socket_0, (&c));
				nimln_(1373, "sockets.nim");
				{
					NIM_BOOL T26_;
					NI T30_;
					T26_ = (NIM_BOOL)0;
					T26_ = (((NI) 0) < n);
					if (!(T26_)) goto LA27_;
					T26_ = ((NU8)(c) == (NU8)(10));
					LA27_: ;
					if (!T26_) goto LA28_;
					nimln_(1374, "sockets.nim");
					T30_ = (NI)0;
					T30_ = recv_WXPjALWv6pg9beQZkAUGAcw_2(socket_0, ((void*) ((&c))), ((NI) 1));
					T30_;
				}
				goto LA24_;
				LA28_: ;
				{
					nimln_(1375, "sockets.nim");
					if (!(n <= ((NI) 0))) goto LA32_;
					nimln_(1376, "sockets.nim");
					{
						if (!(((*line) ? (*line)->Sup.len : 0) == ((NI) 0))) goto LA36_;
						result = ((tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg) 3);
					}
					goto LA34_;
					LA36_: ;
					{
						result = ((tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg) 1);
					}
					LA34_: ;
					goto BeforeRet_;
				}
				goto LA24_;
				LA32_: ;
				LA24_: ;
				nimln_(1377, "sockets.nim");
				result = ((tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg) 0);
				goto BeforeRet_;
			}
			goto LA20_;
			LA22_: ;
			{
				nimln_(1378, "sockets.nim");
				if (!((NU8)(c) == (NU8)(10))) goto LA40_;
				result = ((tyEnum_RecvLineResult_qXaT2IM9a24ZUViEPEpZvyg) 0);
				goto BeforeRet_;
			}
			goto LA20_;
			LA40_: ;
			LA20_: ;
			nimln_(1379, "sockets.nim");
			(*line) = addChar((*line), c);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw, readLineAsync_9cC57DOj0IEqJ2zF3OJ412Q)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NimStringDesc** line) {
	tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw result;
	nimfr_("readLineAsync", "sockets.nim");
{	result = (tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw)0;
	nimln_(1392, "sockets.nim");
	(*line) = setLengthStr((*line), ((NI) 0));
	{
		nimln_(1398, "sockets.nim");
		while (1) {
			NIM_CHAR c;
			NI n;
			c = (NIM_CHAR)0;
			nimln_(1400, "sockets.nim");
			n = recv_WXPjALWv6pg9beQZkAUGAcw_2(socket_0, ((void*) ((&c))), ((NI) 1));
			nimln_(1402, "sockets.nim");
			{
				if (!(n < ((NI) 0))) goto LA5_;
				nimln_(1403, "sockets.nim");
				{
					if (!(((*line) ? (*line)->Sup.len : 0) == ((NI) 0))) goto LA9_;
					nimln_(1395, "sockets.nim");
					raiseSocketError_pS2otRA79aO1ctxOIlhpXgw(socket_0, ((NI) -1), NIM_TRUE);
					nimln_(1403, "sockets.nim");
					nimln_(1396, "sockets.nim");
					result = ((tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw) 3);
					goto BeforeRet_;
				}
				goto LA7_;
				LA9_: ;
				{
					nimln_(1403, "sockets.nim");
					result = ((tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw) 1);
					goto BeforeRet_;
				}
				LA7_: ;
			}
			goto LA3_;
			LA5_: ;
			{
				nimln_(1404, "sockets.nim");
				if (!(n == ((NI) 0))) goto LA13_;
				nimln_(1405, "sockets.nim");
				{
					if (!(((*line) ? (*line)->Sup.len : 0) == ((NI) 0))) goto LA17_;
					result = ((tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw) 2);
				}
				goto LA15_;
				LA17_: ;
				{
					result = ((tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw) 1);
				}
				LA15_: ;
				goto BeforeRet_;
			}
			goto LA3_;
			LA13_: ;
			LA3_: ;
			nimln_(1406, "sockets.nim");
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA22_;
				nimln_(1407, "sockets.nim");
				n = peekChar_yvFqgxh8V169ciAXvPCcd7g(socket_0, (&c));
				nimln_(1408, "sockets.nim");
				{
					NIM_BOOL T26_;
					NI T30_;
					T26_ = (NIM_BOOL)0;
					T26_ = (((NI) 0) < n);
					if (!(T26_)) goto LA27_;
					T26_ = ((NU8)(c) == (NU8)(10));
					LA27_: ;
					if (!T26_) goto LA28_;
					nimln_(1409, "sockets.nim");
					T30_ = (NI)0;
					T30_ = recv_WXPjALWv6pg9beQZkAUGAcw_2(socket_0, ((void*) ((&c))), ((NI) 1));
					T30_;
				}
				goto LA24_;
				LA28_: ;
				{
					nimln_(1410, "sockets.nim");
					if (!(n <= ((NI) 0))) goto LA32_;
					nimln_(1411, "sockets.nim");
					{
						if (!(((*line) ? (*line)->Sup.len : 0) == ((NI) 0))) goto LA36_;
						nimln_(1395, "sockets.nim");
						raiseSocketError_pS2otRA79aO1ctxOIlhpXgw(socket_0, ((NI) -1), NIM_TRUE);
						nimln_(1411, "sockets.nim");
						nimln_(1396, "sockets.nim");
						result = ((tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw) 3);
						goto BeforeRet_;
					}
					goto LA34_;
					LA36_: ;
					{
						nimln_(1411, "sockets.nim");
						result = ((tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw) 1);
						goto BeforeRet_;
					}
					LA34_: ;
				}
				goto LA24_;
				LA32_: ;
				LA24_: ;
				nimln_(1412, "sockets.nim");
				result = ((tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw) 0);
				goto BeforeRet_;
			}
			goto LA20_;
			LA22_: ;
			{
				nimln_(1413, "sockets.nim");
				if (!((NU8)(c) == (NU8)(10))) goto LA40_;
				result = ((tyEnum_ReadLineResult_HPNBmM8ecA7VJyy2S2WtGw) 0);
				goto BeforeRet_;
			}
			goto LA20_;
			LA40_: ;
			LA20_: ;
			nimln_(1414, "sockets.nim");
			(*line) = addChar((*line), c);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, toCInt_26J2CiwBhk9clpsA6MQOH8w)(tyEnum_SOBool_qY5afbczMeenVKcifqQxQg opt) {
	int result;
	nimfr_("toCInt", "sockets.nim");
	result = (int)0;
	nimln_(779, "sockets.nim");
	switch (opt) {
	case ((tyEnum_SOBool_qY5afbczMeenVKcifqQxQg) 0):
	{
		result = SO_ACCEPTCONN;
	}
	break;
	case ((tyEnum_SOBool_qY5afbczMeenVKcifqQxQg) 1):
	{
		result = SO_BROADCAST;
	}
	break;
	case ((tyEnum_SOBool_qY5afbczMeenVKcifqQxQg) 2):
	{
		result = SO_DEBUG;
	}
	break;
	case ((tyEnum_SOBool_qY5afbczMeenVKcifqQxQg) 3):
	{
		result = SO_DONTROUTE;
	}
	break;
	case ((tyEnum_SOBool_qY5afbczMeenVKcifqQxQg) 4):
	{
		result = SO_KEEPALIVE;
	}
	break;
	case ((tyEnum_SOBool_qY5afbczMeenVKcifqQxQg) 5):
	{
		result = SO_OOBINLINE;
	}
	break;
	case ((tyEnum_SOBool_qY5afbczMeenVKcifqQxQg) 6):
	{
		result = SO_REUSEADDR;
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setSockOpt_W0c9cGezdaflNgDQEoQgYWg)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, tyEnum_SOBool_qY5afbczMeenVKcifqQxQg opt, NIM_BOOL value, int level) {
	int valuei;
	NI T1_;
	nimfr_("setSockOpt", "sockets.nim");
	nimln_(801, "sockets.nim");
	T1_ = (NI)0;
	{
		if (!value) goto LA4_;
		T1_ = ((NI) 1);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) 0);
	}
	LA2_: ;
	valuei = ((int) (T1_));
	nimln_(802, "sockets.nim");
	{
		int T9_;
		int T10_;
		NI32 T13_;
		T9_ = (int)0;
		T9_ = toCInt_26J2CiwBhk9clpsA6MQOH8w(opt);
		T10_ = (int)0;
		T10_ = Dl_141048_((*socket_0).fd, level, T9_, ((void*) ((&valuei))), ((unsigned int) 4));
		if (!(T10_ < ((NI32) 0))) goto LA11_;
		nimln_(804, "sockets.nim");
		T13_ = (NI32)0;
		T13_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T13_, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
	}
	LA11_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, checkBuffer_aAVQct6lZ5x9cb0hbJJsyeA)(tySequence_bTfD0pPidBST9bT9bmQFkEdg** readfds) {
	NI result;
	tySequence_bTfD0pPidBST9bT9bmQFkEdg* res;
	nimfr_("checkBuffer", "sockets.nim");
	result = (NI)0;
	nimln_(990, "sockets.nim");
	res = (tySequence_bTfD0pPidBST9bT9bmQFkEdg*) newSeq((&NTI_bTfD0pPidBST9bT9bmQFkEdg_), 0);
	nimln_(991, "sockets.nim");
	result = ((NI) 0);
	{
		tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* s;
		tySequence_bTfD0pPidBST9bT9bmQFkEdg* colontmp_;
		NI i;
		NI L;
		NI T2_;
		s = (tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*)0;
		colontmp_ = (tySequence_bTfD0pPidBST9bT9bmQFkEdg*)0;
		nimln_(992, "sockets.nim");
		colontmp_ = (*readfds);
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_Eup9aWRghLcrbvSbC7oHuCw_35;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				s = colontmp_->data[i];
				nimln_(993, "sockets.nim");
				{
					NIM_BOOL T7_;
					NI TM_Eup9aWRghLcrbvSbC7oHuCw_34;
					NI T10_;
					T7_ = (NIM_BOOL)0;
					T7_ = hasDataBuffered_LkL3W9bGq7xFDN9a9c1LFIpuw(s);
					if (!T7_) goto LA8_;
					nimln_(994, "sockets.nim");
					TM_Eup9aWRghLcrbvSbC7oHuCw_34 = addInt(result, ((NI) 1));
					result = (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_34);
					nimln_(995, "sockets.nim");
					res = (tySequence_bTfD0pPidBST9bT9bmQFkEdg*) incrSeqV2(&(res)->Sup, sizeof(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*));
					T10_ = res->Sup.len++;
					asgnRefNoCycle((void**) (&res->data[T10_]), s);
				}
				LA8_: ;
				nimln_(3809, "system.nim");
				TM_Eup9aWRghLcrbvSbC7oHuCw_35 = addInt(i, ((NI) 1));
				i = (NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_35);
				nimln_(3810, "system.nim");
				{
					NI T13_;
					T13_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T13_ == L))) goto LA14_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_22));
				}
				LA14_: ;
			} LA4: ;
		}
	}
	nimln_(996, "sockets.nim");
	{
		if (!(((NI) 0) < result)) goto LA18_;
		nimln_(997, "sockets.nim");
		genericSeqAssign((&(*readfds)), res, (&NTI_bTfD0pPidBST9bT9bmQFkEdg_));
	}
	LA18_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, select_bki0kAldp9a0hqy2SCoMkqQ)(tySequence_bTfD0pPidBST9bT9bmQFkEdg** readfds, NI timeout) {
	NI result;
	NI buffersFilled;
	tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA tv;
	tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog rd;
	NI m;
	nimfr_("select", "sockets.nim");
{	result = (NI)0;
	nimln_(1075, "sockets.nim");
	buffersFilled = checkBuffer_aAVQct6lZ5x9cb0hbJJsyeA(readfds);
	nimln_(1076, "sockets.nim");
	{
		if (!(((NI) 0) < buffersFilled)) goto LA3_;
		nimln_(1077, "sockets.nim");
		result = buffersFilled;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(1078, "sockets.nim");
	tv = timeValFromMilliseconds_NIte9cl59aaaR2tw3QnZgo9bw(timeout);
	memset((void*)(&rd), 0, sizeof(rd));
	nimln_(1081, "sockets.nim");
	m = ((NI) 0);
	nimln_(1082, "sockets.nim");
	createFdSet_KpofmEKnwuZMokQawJcchQ((&rd), (*readfds), (&m));
	nimln_(1084, "sockets.nim");
	{
		NI TM_Eup9aWRghLcrbvSbC7oHuCw_36;
		int T9_;
		nimln_(398, "system.nim");
		nimln_(1084, "sockets.nim");
		if (!!((timeout == ((NI) -1)))) goto LA7_;
		nimln_(1085, "sockets.nim");
		TM_Eup9aWRghLcrbvSbC7oHuCw_36 = addInt(m, ((NI) 1));
		T9_ = (int)0;
		T9_ = Dl_141075_(((int) ((NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_36))), (&rd), NIM_NIL, NIM_NIL, (&tv));
		result = ((NI) (T9_));
	}
	goto LA5_;
	LA7_: ;
	{
		NI TM_Eup9aWRghLcrbvSbC7oHuCw_37;
		int T11_;
		nimln_(1087, "sockets.nim");
		TM_Eup9aWRghLcrbvSbC7oHuCw_37 = addInt(m, ((NI) 1));
		T11_ = (int)0;
		T11_ = Dl_141075_(((int) ((NI)(TM_Eup9aWRghLcrbvSbC7oHuCw_37))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
		result = ((NI) (T11_));
	}
	LA5_: ;
	nimln_(1089, "sockets.nim");
	pruneSocketSet_yhKN7mCFg7gC9a9co4guWCXA(readfds, (&rd));
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, accept_fmEeiVB2kLoz9b19cak1kHwg)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* server, tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ** client) {
	NimStringDesc* addrDummy;
	nimfr_("accept", "sockets.nim");
	nimln_(639, "sockets.nim");
	addrDummy = copyString(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
	nimln_(640, "sockets.nim");
	acceptAddr_PNW7a0XAnzN1Vc9aiqZmcmQ(server, client, (&addrDummy));
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU32)((*c).refcount) + (NU32)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, send_9a1fIRn6xj8KC9cT72UBEWAw)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NimStringDesc* data) {
	NI sent;
	nimfr_("send", "sockets.nim");
	nimln_(1600, "sockets.nim");
	{
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T5_;
		if (!(*socket_0).nonblocking) goto LA3_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		nimln_(1601, "sockets.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_38));
		if (T5_) nimGCunrefNoCycle(T5_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(1601, "sockets.nim");
		raiseException((Exception*)e, "ValueError");
	}
	LA3_: ;
	nimln_(1602, "sockets.nim");
	sent = send_WXPjALWv6pg9beQZkAUGAcw(socket_0, ((void*) (data->data)), (data ? data->Sup.len : 0));
	nimln_(1603, "sockets.nim");
	{
		NI32 T10_;
		if (!(sent < ((NI) 0))) goto LA8_;
		nimln_(1608, "sockets.nim");
		T10_ = (NI32)0;
		T10_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T10_, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
	}
	LA8_: ;
	nimln_(1610, "sockets.nim");
	{
		NI32 T15_;
		nimln_(398, "system.nim");
		nimln_(1610, "sockets.nim");
		if (!!((sent == (data ? data->Sup.len : 0)))) goto LA13_;
		nimln_(1611, "sockets.nim");
		T15_ = (NI32)0;
		T15_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_39));
	}
	LA13_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, recvAsync_a4lvnpe0O29a8Q9cAJ2ZGNiw)(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ* socket_0, NimStringDesc** data, NI size) {
	NI result;
	nimfr_("recvAsync", "sockets.nim");
	result = (NI)0;
	nimln_(1233, "sockets.nim");
	(*data) = setLengthStr((*data), ((NI)chckRange(size, ((NI) 0), ((NI) 2147483647))));
	nimln_(1234, "sockets.nim");
	result = recv_WXPjALWv6pg9beQZkAUGAcw_2(socket_0, ((void*) ((*data)->data)), size);
	nimln_(1235, "sockets.nim");
	{
		if (!(result < ((NI) 0))) goto LA3_;
		nimln_(1236, "sockets.nim");
		(*data) = setLengthStr((*data), ((NI) 0));
		nimln_(1237, "sockets.nim");
		raiseSocketError_pS2otRA79aO1ctxOIlhpXgw(socket_0, ((NI) -1), NIM_TRUE);
		nimln_(1238, "sockets.nim");
		result = ((NI) -1);
	}
	LA3_: ;
	nimln_(1239, "sockets.nim");
	(*data) = setLengthStr((*data), ((NI)chckRange(result, ((NI) 0), ((NI) 2147483647))));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_socketsInit000)(void) {
	nimfr_("sockets", "sockets.nim");
	nimln_(161, "sockets.nim");
	osInvalidSocket_Cd5FXu8AR5CJVkibL4fIlg = INVALID_SOCKET;
	nimln_(1753, "sockets.nim");
	{
		int T3_;
		NI32 T6_;
		nimln_(398, "system.nim");
		nimln_(1753, "sockets.nim");
		T3_ = (int)0;
		T3_ = Dl_141146_(((NI16) 257), (&wsa_kip9aLoJVEKbO857Iek9awvA));
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_2));
	}
	LA4_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_socketsDatInit000)(void) {
static TNimNode* TM_Eup9aWRghLcrbvSbC7oHuCw_3[3];
static TNimNode* TM_Eup9aWRghLcrbvSbC7oHuCw_4[3];
static TNimNode* TM_Eup9aWRghLcrbvSbC7oHuCw_5[6];
NI TM_Eup9aWRghLcrbvSbC7oHuCw_7;
static char* NIM_CONST TM_Eup9aWRghLcrbvSbC7oHuCw_6[6] = {
"IPPROTO_TCP", 
"IPPROTO_UDP", 
"IPPROTO_IP", 
"IPPROTO_IPV6", 
"IPPROTO_RAW", 
"IPPROTO_ICMP"};
static TNimNode TM_Eup9aWRghLcrbvSbC7oHuCw_0[16];
NTI_0npQHvqsTpGEM2MQEwnDKQ_.size = sizeof(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ);
NTI_0npQHvqsTpGEM2MQEwnDKQ_.kind = 18;
NTI_0npQHvqsTpGEM2MQEwnDKQ_.base = 0;
NTI_0npQHvqsTpGEM2MQEwnDKQ_.flags = 3;
TM_Eup9aWRghLcrbvSbC7oHuCw_3[0] = &TM_Eup9aWRghLcrbvSbC7oHuCw_0[1];
TM_Eup9aWRghLcrbvSbC7oHuCw_0[1].kind = 1;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[1].offset = offsetof(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ, fd);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[1].name = "fd";
TM_Eup9aWRghLcrbvSbC7oHuCw_3[1] = &TM_Eup9aWRghLcrbvSbC7oHuCw_0[2];
TM_Eup9aWRghLcrbvSbC7oHuCw_0[2].kind = 3;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[2].offset = offsetof(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ, isBuffered);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[2].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[2].name = "isBuffered";
TM_Eup9aWRghLcrbvSbC7oHuCw_0[2].sons = &NimDT__0npQHvqsTpGEM2MQEwnDKQ_isBuffered[0];
TM_Eup9aWRghLcrbvSbC7oHuCw_0[2].len = 2;
TM_Eup9aWRghLcrbvSbC7oHuCw_4[0] = &TM_Eup9aWRghLcrbvSbC7oHuCw_0[4];
TM_Eup9aWRghLcrbvSbC7oHuCw_0[4].kind = 1;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[4].offset = offsetof(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ, isBufferedU.S1.buffer);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[4].typ = (&NTI_QQGLPNVVwLhYjkngqAxXQQ_);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[4].name = "buffer";
TM_Eup9aWRghLcrbvSbC7oHuCw_4[1] = &TM_Eup9aWRghLcrbvSbC7oHuCw_0[5];
TM_Eup9aWRghLcrbvSbC7oHuCw_0[5].kind = 1;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[5].offset = offsetof(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ, isBufferedU.S1.currPos);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[5].name = "currPos";
TM_Eup9aWRghLcrbvSbC7oHuCw_4[2] = &TM_Eup9aWRghLcrbvSbC7oHuCw_0[6];
TM_Eup9aWRghLcrbvSbC7oHuCw_0[6].kind = 1;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[6].offset = offsetof(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ, isBufferedU.S1.bufLen);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[6].name = "bufLen";
TM_Eup9aWRghLcrbvSbC7oHuCw_0[3].len = 3; TM_Eup9aWRghLcrbvSbC7oHuCw_0[3].kind = 2; TM_Eup9aWRghLcrbvSbC7oHuCw_0[3].sons = &TM_Eup9aWRghLcrbvSbC7oHuCw_4[0];
NimDT__0npQHvqsTpGEM2MQEwnDKQ_isBuffered[1] = &TM_Eup9aWRghLcrbvSbC7oHuCw_0[3];
TM_Eup9aWRghLcrbvSbC7oHuCw_0[7].len = 0; TM_Eup9aWRghLcrbvSbC7oHuCw_0[7].kind = 2;
NimDT__0npQHvqsTpGEM2MQEwnDKQ_isBuffered[0] = &TM_Eup9aWRghLcrbvSbC7oHuCw_0[7];
TM_Eup9aWRghLcrbvSbC7oHuCw_3[2] = &TM_Eup9aWRghLcrbvSbC7oHuCw_0[8];
TM_Eup9aWRghLcrbvSbC7oHuCw_0[8].kind = 1;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[8].offset = offsetof(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ, nonblocking);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[8].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Eup9aWRghLcrbvSbC7oHuCw_0[8].name = "nonblocking";
TM_Eup9aWRghLcrbvSbC7oHuCw_0[0].len = 3; TM_Eup9aWRghLcrbvSbC7oHuCw_0[0].kind = 2; TM_Eup9aWRghLcrbvSbC7oHuCw_0[0].sons = &TM_Eup9aWRghLcrbvSbC7oHuCw_3[0];
NTI_0npQHvqsTpGEM2MQEwnDKQ_.node = &TM_Eup9aWRghLcrbvSbC7oHuCw_0[0];
NTI_cOUvSWxuQTnH5Tt9bNSuuDw_.size = sizeof(tyObject_SocketImpl_0npQHvqsTpGEM2MQEwnDKQ*);
NTI_cOUvSWxuQTnH5Tt9bNSuuDw_.kind = 22;
NTI_cOUvSWxuQTnH5Tt9bNSuuDw_.base = (&NTI_0npQHvqsTpGEM2MQEwnDKQ_);
NTI_cOUvSWxuQTnH5Tt9bNSuuDw_.flags = 2;
NTI_cOUvSWxuQTnH5Tt9bNSuuDw_.marker = Marker_tyRef_cOUvSWxuQTnH5Tt9bNSuuDw;
NTI_hB5Btjev9bu2I7PAPRf7c6w_.size = sizeof(tyEnum_Protocol_hB5Btjev9bu2I7PAPRf7c6w);
NTI_hB5Btjev9bu2I7PAPRf7c6w_.kind = 14;
NTI_hB5Btjev9bu2I7PAPRf7c6w_.base = 0;
NTI_hB5Btjev9bu2I7PAPRf7c6w_.flags = 3;
for (TM_Eup9aWRghLcrbvSbC7oHuCw_7 = 0; TM_Eup9aWRghLcrbvSbC7oHuCw_7 < 6; TM_Eup9aWRghLcrbvSbC7oHuCw_7++) {
TM_Eup9aWRghLcrbvSbC7oHuCw_0[TM_Eup9aWRghLcrbvSbC7oHuCw_7+9].kind = 1;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[TM_Eup9aWRghLcrbvSbC7oHuCw_7+9].offset = TM_Eup9aWRghLcrbvSbC7oHuCw_7;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[TM_Eup9aWRghLcrbvSbC7oHuCw_7+9].name = TM_Eup9aWRghLcrbvSbC7oHuCw_6[TM_Eup9aWRghLcrbvSbC7oHuCw_7];
TM_Eup9aWRghLcrbvSbC7oHuCw_5[TM_Eup9aWRghLcrbvSbC7oHuCw_7] = &TM_Eup9aWRghLcrbvSbC7oHuCw_0[TM_Eup9aWRghLcrbvSbC7oHuCw_7+9];
}
TM_Eup9aWRghLcrbvSbC7oHuCw_0[9].offset = 6;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[10].offset = 17;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[11].offset = 18;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[12].offset = 19;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[13].offset = 20;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[14].offset = 21;
TM_Eup9aWRghLcrbvSbC7oHuCw_0[15].len = 6; TM_Eup9aWRghLcrbvSbC7oHuCw_0[15].kind = 2; TM_Eup9aWRghLcrbvSbC7oHuCw_0[15].sons = &TM_Eup9aWRghLcrbvSbC7oHuCw_5[0];
NTI_hB5Btjev9bu2I7PAPRf7c6w_.node = &TM_Eup9aWRghLcrbvSbC7oHuCw_0[15];
NTI_hB5Btjev9bu2I7PAPRf7c6w_.flags = 1<<2;
if (!((TM_Eup9aWRghLcrbvSbC7oHuCw_9 = nimLoadLibrary((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_11))
)) nimLoadLibraryError((NimStringDesc*) &TM_Eup9aWRghLcrbvSbC7oHuCw_12);
	Dl_322052_ = (tyProc_awTV7srwWeJ9cGPOCgBQa7g) nimGetProcAddr(TM_Eup9aWRghLcrbvSbC7oHuCw_9, "ioctlsocket");
}

