/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Yobmod\.choosenim\toolchains\nim-0.18.0\lib -o c:\Webdev\dmltests\nim\jester\nimcache\stdlib_logging.o c:\Webdev\dmltests\nim\jester\nimcache\stdlib_logging.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_gngkqwVsuclWSwd9cJImMYw tySequence_gngkqwVsuclWSwd9cJImMYw;
typedef struct tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RootObj RootObj;
typedef struct tyTuple_7q7q3E6Oj24ZNVJb9aonhAg tyTuple_7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA;
typedef struct Exception Exception;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w;
typedef struct tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g;
typedef struct tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA;
typedef struct tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_uTUOefOZpRbrah39bBH8rtw[8];
typedef NU8 tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug {
  RootObj Sup;
tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold;
NimStringDesc* fmtStr;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyTuple_7q7q3E6Oj24ZNVJb9aonhAg {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA {
  tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug Sup;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w {
  tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug Sup;
FILE* file;
};
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g {
  tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w Sup;
NI maxLines;
NI curLine;
NimStringDesc* baseName;
tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ baseMode;
NI logFiles;
NI bufSize;
};
typedef NU8 tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg;
struct tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw {
NI32 dwLowDateTime;
NI32 dwHighDateTime;
};
typedef NI16 tyArray_EKfNt9b8uxndgFbu2Ky3XAQ[260];
typedef NI16 tyArray_Get9cpRTS5VjGKP6CDsI9bYA[14];
struct tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA {
NI32 dwFileAttributes;
tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw ftCreationTime;
tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw ftLastAccessTime;
tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw ftLastWriteTime;
NI32 nFileSizeHigh;
NI32 nFileSizeLow;
NI32 dwReserved0;
NI32 dwReserved1;
tyArray_EKfNt9b8uxndgFbu2Ky3XAQ cFileName;
tyArray_Get9cpRTS5VjGKP6CDsI9bYA cAlternateFileName;
};
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
typedef N_STDCALL_PTR(NI32, tyProc_jwEWAkul5J6p6K0UfXa1tw) (NI hFindFile, tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA* lpFindFileData);
typedef N_STDCALL_PTR(NI32, tyProc_9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(void, tyProc_ofoySXaAAlxxs9bQS9a1etlg) (NI hFindFile);
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NI align;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9agrCtWKhCnWWMJpKKugJag[16];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9agrCtWKhCnWWMJpKKugJag bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9agrCtWKhCnWWMJpKKugJag bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_gngkqwVsuclWSwd9cJImMYw {
  TGenericSeq Sup;
  tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_GA38ua3ZxEHLLuvtleWIKw)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_gngkqwVsuclWSwd9cJImMYw)(void* p, NI op);
static N_NIMCALL(void, TM_7EbqAVTAsJVrNKIE9b0UU9bA_13)(void);
N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substituteLog_GUiLaZ0b21eA2W7LstPGkg)(NimStringDesc* frmt, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_DCrUjdaMvFDHaR1hs7sQGwsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_fPlwH3r9agN9aEHB6yCPMh0wsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringDesc* path, tyTuple_7q7q3E6Oj24ZNVJb9aonhAg* Result);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, log_ickm9bT0pWcynhn7oX83aTg)(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, log_F2wVp9bYd9alkwSwovfO9aanw)(tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qlogging)(FILE* f, NimStringDesc** x, NI xLen_0);
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, flushFile_BWnr8V7RERYno9bIdPmw8Hw_3)(FILE* f);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA*, newConsoleLogger_EgdHBnSBbwirQsDvEbPCdg)(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold, NimStringDesc* fmtStr);
static N_NIMCALL(void, Marker_tyRef_sld5f81MZHmkeseB9a2pc9cA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, log_ZlB8IWVc9cdlahbPdrAh0Og)(tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, defaultFilename_M9azl059cBgzmuyH8nmghD5Q)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, noschangeFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w*, newFileLogger_EylKLfnJvWfrolZXdDlSPA)(FILE* file, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold, NimStringDesc* fmtStr);
static N_NIMCALL(void, Marker_tyRef_SgN9afM7kbfbLF8z1Uhhmpw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w*, newFileLogger_LrkX9b6HDGG0bBvoCQ2zdVw)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold, NimStringDesc* fmtStr, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(NI, countLogLines_6gVzeXzXkdVD4DK52Nyw4A)(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g* logger);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine_sO1bQXVRA6RP9cdYJXNKeSw)(FILE* f, NimStringDesc** line);
N_LIB_PRIVATE N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(NI, countFiles_0BZmLO9amvNhBRMKPzZQ6Wg)(NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(NI, findFirstFile_9cPKjuaUWDYlrzWunhDgNng)(NimStringDesc* a, tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA* b);
static N_INLINE(NIM_BOOL, skipFindData_Paqclu9aSY8chOSEIvA5ZoAlogging)(tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA* f);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosextractFilename)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__D2o4ABrO3iHTudww2CqX4w)(NI16* s);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
static N_INLINE(NimStringDesc*, X5BX5D__lkBUIkH7j2jb0vaXPf2frAstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__ctxq0YSon7aLz7isCROwwQuri)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g*, newRollingFileLogger_mNP2yaC4s3yw9ctYnGfc00w)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold, NimStringDesc* fmtStr, NI maxLines, NI bufSize);
static N_NIMCALL(void, Marker_tyRef_ysBAzRrImnix9cpwFmcaxZQ)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, rotate_syaiH6U59aM6LtCRd9aW2tXg)(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g* logger);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, nosmoveFile)(NimStringDesc* source, NimStringDesc* dest);
N_LIB_PRIVATE N_NIMCALL(void, log_Z1wwTzhV8hfwxjrAweVVZQ)(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, logLoop_Y1QvvdpC0FmKBCafruMWGQ)(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, log_15uDclQ9cwzr06QrR8BYZqA)(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, addHandler_tg0stk9atBM54nh79a3PBrOA)(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* handler);
static N_INLINE(void, nimGCunrefRC1)(void* p);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_LIB_PRIVATE N_NIMCALL(tySequence_gngkqwVsuclWSwd9cJImMYw*, getHandlers_T85bEDQSt0UQcLetx56kcQ)(void);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, setLogFilter_CbDskkOBDVPDz8J81JVpdw)(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg lvl);
N_LIB_PRIVATE N_NIMCALL(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg, getLogFilter_VpsumEqOIaR8tmI1dyA6cA)(void);
tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level_hzbRBHMSEnpbC61ptpdKmA;
tySequence_gngkqwVsuclWSwd9cJImMYw* handlers_OpA9asfHAsjfRTcLDwhkNfA;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_igsiUXBFuP9cp5KwKL5yiug_;
TNimType NTI_pW4mH4lipH6u2NKDGEWdGg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_GA38ua3ZxEHLLuvtleWIKw_;
TNimType NTI_gngkqwVsuclWSwd9cJImMYw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_QaTO46vt5hgK2eu9ah2xGrA_;
TNimType NTI_sld5f81MZHmkeseB9a2pc9cA_;
TNimType NTI_DiHvgyNJFmeALM5A2LhG3w_;
extern TNimType NTI_7BHnQsEj49a9c6QtudqWTo1w_;
TNimType NTI_SgN9afM7kbfbLF8z1Uhhmpw_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
extern tyProc_jwEWAkul5J6p6K0UfXa1tw Dl_140243_;
extern tyProc_9bXer9a4ps9aSGctILcxWReVw Dl_139630_;
extern tyProc_ofoySXaAAlxxs9bQS9a1etlg Dl_140401_;
TNimType NTI_O2Lvje8yIZTOG9bz4MrKW7g_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_fVUBHvW79bXUw1j55Oo9avSQ_;
TNimType NTI_ysBAzRrImnix9cpwFmcaxZQ_;
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_2, "DEBUG", 5);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_3, "INFO", 4);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_4, "NOTICE", 6);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_5, "WARN", 4);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_6, "ERROR", 5);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_7, "FATAL", 5);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_8, "NONE", 4);
NIM_CONST tyArray_uTUOefOZpRbrah39bBH8rtw LevelNames_phezTIRn5apX0TyIzWqOtw = {((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_2),
((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_2),
((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_3),
((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_4),
((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_5),
((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_6),
((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_7),
((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_8)}
;
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_21, "", 0);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_23, "date", 4);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_24, "time", 4);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_25, "datetime", 8);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_26, "app", 3);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_27, "appdir", 6);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_28, "appname", 7);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_29, "levelid", 7);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_30, "levelname", 9);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_31, "T", 1);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_32, "nil", 3);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_35, "\012", 1);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_36, "log", 3);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_38, ".", 1);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_39, "*", 1);
STRING_LITERAL(TM_7EbqAVTAsJVrNKIE9b0UU9bA_54, "len(a) == L seq modified while iterating over it", 48);
static N_NIMCALL(void, Marker_tyRef_GA38ua3ZxEHLLuvtleWIKw)(void* p, NI op) {
	tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* a;
	a = (tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug*)p;
	nimGCvisit((void*)(*a).fmtStr, op);
}
static N_NIMCALL(void, Marker_tySequence_gngkqwVsuclWSwd9cJImMYw)(void* p, NI op) {
	tySequence_gngkqwVsuclWSwd9cJImMYw* a;
	NI T1_;
	a = (tySequence_gngkqwVsuclWSwd9cJImMYw*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, TM_7EbqAVTAsJVrNKIE9b0UU9bA_13)(void) {
	nimGCvisit((void*)handlers_OpA9asfHAsjfRTcLDwhkNfA, 0);
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_DCrUjdaMvFDHaR1hs7sQGwsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_DCrUjdaMvFDHaR1hs7sQGwsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_fPlwH3r9agN9aEHB6yCPMh0wsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_fPlwH3r9agN9aEHB6yCPMh0wsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substituteLog_GUiLaZ0b21eA2W7LstPGkg)(NimStringDesc* frmt, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	NimStringDesc* result;
	NI msgLen;
	NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_17;
	NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_18;
	NI i_2;
	nimfr_("substituteLog", "logging.nim");
	result = (NimStringDesc*)0;
	nimln_(112, "logging.nim");
	msgLen = ((NI) 0);
	{
		NimStringDesc* arg;
		NI i;
		arg = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_16;
				if (!(i < argsLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i) >= (NU)(argsLen_0)) raiseIndexError();
				arg = args[i];
				nimln_(114, "logging.nim");
				{
					NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_14;
					if (!(arg == 0)) goto LA6_;
					nimln_(115, "logging.nim");
					TM_7EbqAVTAsJVrNKIE9b0UU9bA_14 = addInt(msgLen, ((NI) 3));
					msgLen = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_14);
				}
				goto LA4_;
				LA6_: ;
				{
					NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_15;
					nimln_(117, "logging.nim");
					TM_7EbqAVTAsJVrNKIE9b0UU9bA_15 = addInt(msgLen, (arg ? arg->Sup.len : 0));
					msgLen = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_15);
				}
				LA4_: ;
				nimln_(2188, "system.nim");
				TM_7EbqAVTAsJVrNKIE9b0UU9bA_16 = addInt(i, ((NI) 1));
				i = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_16);
			} LA3: ;
		}
	}
	nimln_(118, "logging.nim");
	TM_7EbqAVTAsJVrNKIE9b0UU9bA_17 = addInt((frmt ? frmt->Sup.len : 0), msgLen);
	TM_7EbqAVTAsJVrNKIE9b0UU9bA_18 = addInt((NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_17), ((NI) 20));
	result = rawNewString(((NI)chckRange((NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_18), ((NI) 0), ((NI) 2147483647))));
	nimln_(119, "logging.nim");
	i_2 = ((NI) 0);
	{
		nimln_(120, "logging.nim");
		while (1) {
			if (!(i_2 < (frmt ? frmt->Sup.len : 0))) goto LA10;
			nimln_(121, "logging.nim");
			{
				NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_19;
				nimln_(398, "system.nim");
				nimln_(121, "logging.nim");
				if ((NU)(i_2) > (NU)(frmt->Sup.len)) raiseIndexError();
				if (!!(((NU8)(frmt->data[i_2]) == (NU8)(36)))) goto LA13_;
				nimln_(122, "logging.nim");
				if ((NU)(i_2) > (NU)(frmt->Sup.len)) raiseIndexError();
				result = addChar(result, frmt->data[i_2]);
				nimln_(123, "logging.nim");
				TM_7EbqAVTAsJVrNKIE9b0UU9bA_19 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_19);
			}
			goto LA11_;
			LA13_: ;
			{
				NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_20;
				NimStringDesc* v;
				NimStringDesc* app;
				nimln_(125, "logging.nim");
				TM_7EbqAVTAsJVrNKIE9b0UU9bA_20 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_20);
				nimln_(126, "logging.nim");
				v = copyString(((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_21));
				nimln_(127, "logging.nim");
				app = nosgetAppFilename();
				{
					nimln_(128, "logging.nim");
					while (1) {
						NIM_CHAR T18_;
						NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_22;
						if ((NU)(i_2) > (NU)(frmt->Sup.len)) raiseIndexError();
						if (!(((NU8)(frmt->data[i_2])) >= ((NU8)(97)) && ((NU8)(frmt->data[i_2])) <= ((NU8)(122)) || ((NU8)(frmt->data[i_2])) >= ((NU8)(65)) && ((NU8)(frmt->data[i_2])) <= ((NU8)(90)) || ((NU8)(frmt->data[i_2])) >= ((NU8)(48)) && ((NU8)(frmt->data[i_2])) <= ((NU8)(57)) || ((NU8)(frmt->data[i_2])) == ((NU8)(95)))) goto LA17;
						nimln_(129, "logging.nim");
						if ((NU)(i_2) > (NU)(frmt->Sup.len)) raiseIndexError();
						T18_ = (NIM_CHAR)0;
						T18_ = nsuToLowerChar(frmt->data[i_2]);
						v = addChar(v, T18_);
						nimln_(130, "logging.nim");
						TM_7EbqAVTAsJVrNKIE9b0UU9bA_22 = addInt(i_2, ((NI) 1));
						i_2 = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_22);
					} LA17: ;
				}
				nimln_(131, "logging.nim");
				if (eqStrings(v, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_23))) goto LA19_;
				if (eqStrings(v, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_24))) goto LA20_;
				if (eqStrings(v, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_25))) goto LA21_;
				if (eqStrings(v, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_26))) goto LA22_;
				if (eqStrings(v, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_27))) goto LA23_;
				if (eqStrings(v, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_28))) goto LA24_;
				if (eqStrings(v, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_29))) goto LA25_;
				if (eqStrings(v, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_30))) goto LA26_;
				goto LA27_;
				LA19_: ;
				{
					NimStringDesc* T30_;
					nimln_(132, "logging.nim");
					T30_ = (NimStringDesc*)0;
					T30_ = ntgetDateStr();
					result = resizeString(result, T30_->Sup.len + 0);
appendString(result, T30_);
				}
				goto LA28_;
				LA20_: ;
				{
					NimStringDesc* T32_;
					nimln_(133, "logging.nim");
					T32_ = (NimStringDesc*)0;
					T32_ = ntgetClockStr();
					result = resizeString(result, T32_->Sup.len + 0);
appendString(result, T32_);
				}
				goto LA28_;
				LA21_: ;
				{
					NimStringDesc* T34_;
					NimStringDesc* T35_;
					NimStringDesc* T36_;
					nimln_(134, "logging.nim");
					T34_ = (NimStringDesc*)0;
					T35_ = (NimStringDesc*)0;
					T35_ = ntgetDateStr();
					T36_ = (NimStringDesc*)0;
					T36_ = ntgetClockStr();
					T34_ = rawNewString(T35_->Sup.len + T36_->Sup.len + 1);
appendString(T34_, T35_);
appendString(T34_, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_31));
appendString(T34_, T36_);
					result = resizeString(result, T34_->Sup.len + 0);
appendString(result, T34_);
				}
				goto LA28_;
				LA22_: ;
				{
					nimln_(135, "logging.nim");
					result = resizeString(result, app->Sup.len + 0);
appendString(result, app);
				}
				goto LA28_;
				LA23_: ;
				{
					tyTuple_7q7q3E6Oj24ZNVJb9aonhAg T39_;
					nimln_(137, "logging.nim");
					memset((void*)(&T39_), 0, sizeof(T39_));
					nossplitFile(app, (&T39_));
					result = resizeString(result, T39_.Field0->Sup.len + 0);
appendString(result, T39_.Field0);
				}
				goto LA28_;
				LA24_: ;
				{
					tyTuple_7q7q3E6Oj24ZNVJb9aonhAg T41_;
					nimln_(139, "logging.nim");
					memset((void*)(&T41_), 0, sizeof(T41_));
					nossplitFile(app, (&T41_));
					result = resizeString(result, T41_.Field1->Sup.len + 0);
appendString(result, T41_.Field1);
				}
				goto LA28_;
				LA25_: ;
				{
					nimln_(140, "logging.nim");
					if ((NU)(((NI) 0)) > (NU)(LevelNames_phezTIRn5apX0TyIzWqOtw[(level)- 0]->Sup.len)) raiseIndexError();
					result = addChar(result, LevelNames_phezTIRn5apX0TyIzWqOtw[(level)- 0]->data[((NI) 0)]);
				}
				goto LA28_;
				LA26_: ;
				{
					nimln_(141, "logging.nim");
					result = resizeString(result, LevelNames_phezTIRn5apX0TyIzWqOtw[(level)- 0]->Sup.len + 0);
appendString(result, LevelNames_phezTIRn5apX0TyIzWqOtw[(level)- 0]);
				}
				goto LA28_;
				LA27_: ;
				{
				}
				LA28_: ;
			}
			LA11_: ;
		} LA10: ;
	}
	{
		NimStringDesc* arg_2;
		NI i_3;
		arg_2 = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i_3 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_33;
				if (!(i_3 < argsLen_0)) goto LA47;
				nimln_(2187, "system.nim");
				if ((NU)(i_3) >= (NU)(argsLen_0)) raiseIndexError();
				arg_2 = args[i_3];
				nimln_(144, "logging.nim");
				{
					if (!(arg_2 == 0)) goto LA50_;
					nimln_(145, "logging.nim");
					result = resizeString(result, 3);
appendString(result, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_32));
				}
				goto LA48_;
				LA50_: ;
				{
					nimln_(147, "logging.nim");
					result = resizeString(result, arg_2->Sup.len + 0);
appendString(result, arg_2);
				}
				LA48_: ;
				nimln_(2188, "system.nim");
				TM_7EbqAVTAsJVrNKIE9b0UU9bA_33 = addInt(i_3, ((NI) 1));
				i_3 = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_33);
			} LA47: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, log_ickm9bT0pWcynhn7oX83aTg)(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	nimfr_("log", "logging.nim");
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qlogging)(FILE* f, NimStringDesc** x, NI xLen_0) {
	nimfr_("writeLine", "sysio.nim");
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				if (!(i_2 < xLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				i = x[i_2];
				nimln_(274, "sysio.nim");
				write_c4mGyJBvK73pdM22jiweKQ(f, i);
				nimln_(2188, "system.nim");
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	nimln_(275, "sysio.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_35));
	popFrame();
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "system.nim");
	result = (Exception*)0;
	nimln_(3350, "system.nim");
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU32)((*c).refcount) + (NU32)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU32)(((NI) (ptrdiff_t) (usr))) - (NU32)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), (*currException_9bVPeDJlYTi9bQApZpfH8wjg).up);
}

N_LIB_PRIVATE N_NIMCALL(void, log_F2wVp9bYd9alkwSwovfO9aanw)(tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	nimfr_("log", "logging.nim");
	nimln_(158, "logging.nim");
	{
		NIM_BOOL T3_;
		NimStringDesc* ln;
		TSafePoint TM_7EbqAVTAsJVrNKIE9b0UU9bA_34;
		T3_ = (NIM_BOOL)0;
		T3_ = (level_hzbRBHMSEnpbC61ptpdKmA <= level);
		if (!(T3_)) goto LA4_;
		T3_ = ((*logger).Sup.levelThreshold <= level);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(159, "logging.nim");
		ln = substituteLog_GUiLaZ0b21eA2W7LstPGkg((*logger).Sup.fmtStr, level, args, argsLen_0);
		nimln_(164, "logging.nim");
		pushSafePoint(&TM_7EbqAVTAsJVrNKIE9b0UU9bA_34);
		TM_7EbqAVTAsJVrNKIE9b0UU9bA_34.status = setjmp(TM_7EbqAVTAsJVrNKIE9b0UU9bA_34.context);
		if (TM_7EbqAVTAsJVrNKIE9b0UU9bA_34.status == 0) {
			tyArray_nHXaesL0DJZHyVS07ARPRA T8_;
			nimln_(165, "logging.nim");
			memset((void*)T8_, 0, sizeof(T8_));
			T8_[0] = copyString(ln);
			writeLine_rBQVO3cm3BhnA9aEFD7PG6Qlogging(stdout, T8_, 1);
			nimln_(166, "logging.nim");
			{
				if (!((96 &(1U<<((NU)(level)&7U)))!=0)) goto LA11_;
				flushFile_BWnr8V7RERYno9bIdPmw8Hw_3(stdout);
			}
			LA11_: ;
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
			if (isObj(getCurrentException()->Sup.m_type, (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_))) {
				TM_7EbqAVTAsJVrNKIE9b0UU9bA_34.status = 0;
				popCurrentException();
			}
		}
		if (TM_7EbqAVTAsJVrNKIE9b0UU9bA_34.status != 0) reraiseException();
	}
	LA5_: ;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_sld5f81MZHmkeseB9a2pc9cA)(void* p, NI op) {
	tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA* a;
	a = (tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA*)p;
	nimGCvisit((void*)(*a).Sup.fmtStr, op);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA*, newConsoleLogger_EgdHBnSBbwirQsDvEbPCdg)(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold, NimStringDesc* fmtStr) {
	tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA* result;
	NimStringDesc* T1_;
	nimfr_("newConsoleLogger", "logging.nim");
	result = (tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA*)0;
	nimln_(172, "logging.nim");
	result = (tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA*) newObj((&NTI_sld5f81MZHmkeseB9a2pc9cA_), sizeof(tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA));
	(*result).Sup.Sup.m_type = (&NTI_QaTO46vt5hgK2eu9ah2xGrA_);
	nimln_(173, "logging.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*result).Sup.fmtStr; (*result).Sup.fmtStr = copyStringRC1(fmtStr);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(174, "logging.nim");
	(*result).Sup.levelThreshold = levelThreshold;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, log_ZlB8IWVc9cdlahbPdrAh0Og)(tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	nimfr_("log", "logging.nim");
	nimln_(179, "logging.nim");
	{
		NIM_BOOL T3_;
		tyArray_nHXaesL0DJZHyVS07ARPRA T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = (level_hzbRBHMSEnpbC61ptpdKmA <= level);
		if (!(T3_)) goto LA4_;
		T3_ = ((*logger).Sup.levelThreshold <= level);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(180, "logging.nim");
		memset((void*)T7_, 0, sizeof(T7_));
		T7_[0] = substituteLog_GUiLaZ0b21eA2W7LstPGkg((*logger).Sup.fmtStr, level, args, argsLen_0);
		writeLine_rBQVO3cm3BhnA9aEFD7PG6Qlogging((*logger).file, T7_, 1);
		nimln_(181, "logging.nim");
		{
			if (!((96 &(1U<<((NU)(level)&7U)))!=0)) goto LA10_;
			flushFile_BWnr8V7RERYno9bIdPmw8Hw_3((*logger).file);
		}
		LA10_: ;
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, defaultFilename_M9azl059cBgzmuyH8nmghD5Q)(void) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	tyTuple_7q7q3E6Oj24ZNVJb9aonhAg T2_;
	NimStringDesc* path;
	NimStringDesc* name;
	NimStringDesc* _;
	NimStringDesc* T3_;
	nimfr_("defaultFilename", "logging.nim");
	result = (NimStringDesc*)0;
	nimln_(185, "logging.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = nosgetAppFilename();
	memset((void*)(&T2_), 0, sizeof(T2_));
	nossplitFile(T1_, (&T2_));
	path = (NimStringDesc*)0;
	path = copyString(T2_.Field0);
	name = (NimStringDesc*)0;
	name = copyString(T2_.Field1);
	_ = (NimStringDesc*)0;
	_ = copyString(T2_.Field2);
	nimln_(186, "logging.nim");
	T3_ = (NimStringDesc*)0;
	T3_ = slash__lXoMhn1ZYc9cAJa9bfA61msg(path, name);
	result = noschangeFileExt(T3_, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_36));
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_SgN9afM7kbfbLF8z1Uhhmpw)(void* p, NI op) {
	tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w* a;
	a = (tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w*)p;
	nimGCvisit((void*)(*a).Sup.fmtStr, op);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w*, newFileLogger_EylKLfnJvWfrolZXdDlSPA)(FILE* file, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold, NimStringDesc* fmtStr) {
	tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w* result;
	NimStringDesc* T1_;
	nimfr_("newFileLogger", "logging.nim");
	result = (tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w*)0;
	nimln_(192, "logging.nim");
	result = (tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w*) newObj((&NTI_SgN9afM7kbfbLF8z1Uhhmpw_), sizeof(tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w));
	(*result).Sup.Sup.m_type = (&NTI_DiHvgyNJFmeALM5A2LhG3w_);
	nimln_(193, "logging.nim");
	(*result).file = file;
	nimln_(194, "logging.nim");
	(*result).Sup.levelThreshold = levelThreshold;
	nimln_(195, "logging.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*result).Sup.fmtStr; (*result).Sup.fmtStr = copyStringRC1(fmtStr);
	if (T1_) nimGCunrefNoCycle(T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w*, newFileLogger_LrkX9b6HDGG0bBvoCQ2zdVw)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold, NimStringDesc* fmtStr, NI bufSize) {
	tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w* result;
	FILE* file;
	nimfr_("newFileLogger", "logging.nim");
	result = (tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w*)0;
	nimln_(202, "logging.nim");
	nimln_(206, "logging.nim");
	file = open_hqzpWQbdA2B8l9a6wwNoP4g(filename, mode, bufSize);
	nimln_(207, "logging.nim");
	result = newFileLogger_EylKLfnJvWfrolZXdDlSPA(file, levelThreshold, fmtStr);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, countLogLines_6gVzeXzXkdVD4DK52Nyw4A)(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g* logger) {
	NI result;
	FILE* fp;
	nimfr_("countLogLines", "logging.nim");
	result = (NI)0;
	nimln_(212, "logging.nim");
	result = ((NI) 0);
	nimln_(213, "logging.nim");
	fp = open_hqzpWQbdA2B8l9a6wwNoP4g((*logger).baseName, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
	{
		NimStringDesc* line;
		NimStringDesc* res;
		line = (NimStringDesc*)0;
		nimln_(3340, "system.nim");
		res = rawNewString(((NI) 80));
		{
			nimln_(3341, "system.nim");
			while (1) {
				NIM_BOOL T4_;
				NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_37;
				T4_ = (NIM_BOOL)0;
				T4_ = readLine_sO1bQXVRA6RP9cdYJXNKeSw(fp, (&res));
				if (!T4_) goto LA3;
				line = res;
				nimln_(215, "logging.nim");
				TM_7EbqAVTAsJVrNKIE9b0UU9bA_37 = addInt(result, ((NI) 1));
				result = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_37);
			} LA3: ;
		}
	}
	nimln_(216, "logging.nim");
	close_BWnr8V7RERYno9bIdPmw8Hw_2(fp);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, skipFindData_Paqclu9aSY8chOSEIvA5ZoAlogging)(tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA* f) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T3_;
	NIM_BOOL T5_;
	nimfr_("skipFindData", "os.nim");
	result = (NIM_BOOL)0;
	nimln_(68, "os.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = (((NI) ((*f).cFileName[(((NI) 0))- 0])) == ((NI) 46));
	if (!(T1_)) goto LA2_;
	T3_ = (NIM_BOOL)0;
	T3_ = (((NI) ((*f).cFileName[(((NI) 1))- 0])) == ((NI) 0));
	if (T3_) goto LA4_;
	nimln_(69, "os.nim");
	T5_ = (NIM_BOOL)0;
	T5_ = (((NI) ((*f).cFileName[(((NI) 1))- 0])) == ((NI) 46));
	if (!(T5_)) goto LA6_;
	T5_ = (((NI) ((*f).cFileName[(((NI) 2))- 0])) == ((NI) 0));
	LA6_: ;
	T3_ = T5_;
	LA4_: ;
	T1_ = T3_;
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NimStringDesc*, X5BX5D__lkBUIkH7j2jb0vaXPf2frAstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_42;
	NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_43;
	NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_44;
	nimfr_("[]", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(3556, "system.nim");
	a = x.a;
	nimln_(3557, "system.nim");
	nimln_(3546, "system.nim");
	nimln_(3557, "system.nim");
	TM_7EbqAVTAsJVrNKIE9b0UU9bA_42 = subInt((s ? s->Sup.len : 0), x.b);
	TM_7EbqAVTAsJVrNKIE9b0UU9bA_43 = subInt((NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_42), a);
	TM_7EbqAVTAsJVrNKIE9b0UU9bA_44 = addInt((NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_43), ((NI) 1));
	L = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_44);
	nimln_(3558, "system.nim");
	result = mnewString(((NI)chckRange(L, ((NI) 0), ((NI) 2147483647))));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_45;
				NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_46;
				if (!(i_2 < L)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(3559, "system.nim");
				TM_7EbqAVTAsJVrNKIE9b0UU9bA_45 = addInt(i, a);
				if ((NU)((NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_45)) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i] = s->data[(NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_45)];
				nimln_(3522, "system.nim");
				TM_7EbqAVTAsJVrNKIE9b0UU9bA_46 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_46);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__ctxq0YSon7aLz7isCROwwQuri)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, countFiles_0BZmLO9amvNhBRMKPzZQ6Wg)(NimStringDesc* filename) {
	NI volatile result;
	tyTuple_7q7q3E6Oj24ZNVJb9aonhAg T1_;
	NimStringDesc* dir;
	NimStringDesc* name;
	NimStringDesc* ext;
	nimfr_("countFiles", "logging.nim");
	result = (NI)0;
	nimln_(220, "logging.nim");
	result = ((NI) 0);
	nimln_(221, "logging.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	nossplitFile(filename, (&T1_));
	dir = (NimStringDesc*)0;
	dir = copyString(T1_.Field0);
	name = (NimStringDesc*)0;
	name = copyString(T1_.Field1);
	ext = (NimStringDesc*)0;
	ext = copyString(T1_.Field2);
	nimln_(222, "logging.nim");
	{
		if (!((dir) && (dir)->Sup.len == 0)) goto LA4_;
		nimln_(223, "logging.nim");
		dir = copyString(((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_38));
	}
	LA4_: ;
	{
		tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg kind;
		NimStringDesc* path;
		tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA f;
		NI h;
		NimStringDesc* T7_;
		kind = (tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg)0;
		path = (NimStringDesc*)0;
		memset((void*)(&f), 0, sizeof(f));
		nimln_(780, "os.nim");
		T7_ = (NimStringDesc*)0;
		T7_ = slash__lXoMhn1ZYc9cAJa9bfA61msg(dir, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_39));
		h = findFirstFile_9cPKjuaUWDYlrzWunhDgNng(T7_, (&f));
		nimln_(781, "os.nim");
		{
			TSafePoint TM_7EbqAVTAsJVrNKIE9b0UU9bA_40;
			nimln_(398, "system.nim");
			nimln_(781, "os.nim");
			if (!!((h == ((NI) -1)))) goto LA10_;
			nimln_(782, "os.nim");
			pushSafePoint(&TM_7EbqAVTAsJVrNKIE9b0UU9bA_40);
			TM_7EbqAVTAsJVrNKIE9b0UU9bA_40.status = setjmp(TM_7EbqAVTAsJVrNKIE9b0UU9bA_40.context);
			if (TM_7EbqAVTAsJVrNKIE9b0UU9bA_40.status == 0) {
				{
					nimln_(783, "os.nim");
					while (1) {
						tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg volatile k;
						nimln_(784, "os.nim");
						k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 0);
						nimln_(785, "os.nim");
						{
							NIM_BOOL T17_;
							NimStringDesc* xx;
							T17_ = (NIM_BOOL)0;
							T17_ = skipFindData_Paqclu9aSY8chOSEIvA5ZoAlogging((&f));
							if (!!(T17_)) goto LA18_;
							nimln_(786, "os.nim");
							{
								nimln_(398, "system.nim");
								nimln_(786, "os.nim");
								if (!!(((NI32)(f.dwFileAttributes & ((NI32) 16)) == ((NI32) 0)))) goto LA22_;
								nimln_(787, "os.nim");
								k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2);
							}
							LA22_: ;
							nimln_(788, "os.nim");
							{
								NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_41;
								nimln_(398, "system.nim");
								nimln_(788, "os.nim");
								if (!!(((NI32)(f.dwFileAttributes & ((NI32) 1024)) == ((NI32) 0)))) goto LA26_;
								nimln_(789, "os.nim");
								TM_7EbqAVTAsJVrNKIE9b0UU9bA_41 = addInt(k, ((NI) 1));
								if (TM_7EbqAVTAsJVrNKIE9b0UU9bA_41 < 0 || TM_7EbqAVTAsJVrNKIE9b0UU9bA_41 > 3) raiseOverflow();
								k = (tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_41);
							}
							LA26_: ;
							nimln_(790, "os.nim");
							{
								NimStringDesc* T32_;
								if (!NIM_FALSE) goto LA30_;
								nimln_(57, "os.nim");
								T32_ = (NimStringDesc*)0;
								T32_ = dollar__D2o4ABrO3iHTudww2CqX4w(((NI16*) ((&f.cFileName[(((NI) 0))- 0]))));
								xx = nosextractFilename(T32_);
							}
							goto LA28_;
							LA30_: ;
							{
								NimStringDesc* T34_;
								NimStringDesc* T35_;
								nimln_(791, "os.nim");
								nimln_(57, "os.nim");
								T34_ = (NimStringDesc*)0;
								T34_ = dollar__D2o4ABrO3iHTudww2CqX4w(((NI16*) ((&f.cFileName[(((NI) 0))- 0]))));
								T35_ = (NimStringDesc*)0;
								T35_ = nosextractFilename(T34_);
								xx = slash__lXoMhn1ZYc9cAJa9bfA61msg(dir, T35_);
							}
							LA28_: ;
							nimln_(792, "os.nim");
							kind = k;
							path = xx;
							nimln_(225, "logging.nim");
							{
								NimStringDesc* llfn;
								NimStringDesc* T40_;
								if (!(kind == ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 0))) goto LA38_;
								nimln_(226, "logging.nim");
								T40_ = (NimStringDesc*)0;
								T40_ = rawNewString(name->Sup.len + ext->Sup.len + 1);
appendString(T40_, name);
appendString(T40_, ext);
appendChar(T40_, 46);
								llfn = T40_;
								nimln_(227, "logging.nim");
								{
									NimStringDesc* T43_;
									NIM_BOOL T44_;
									NimStringDesc* numS;
									NimStringDesc* T47_;
									tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T48_;
									TSafePoint TM_7EbqAVTAsJVrNKIE9b0UU9bA_47;
									T43_ = (NimStringDesc*)0;
									T43_ = nosextractFilename(path);
									T44_ = (NIM_BOOL)0;
									T44_ = nsuStartsWith(T43_, llfn);
									if (!T44_) goto LA45_;
									nimln_(228, "logging.nim");
									T47_ = (NimStringDesc*)0;
									T47_ = nosextractFilename(path);
									T48_ = dotdot__ctxq0YSon7aLz7isCROwwQuri((llfn ? llfn->Sup.len : 0), ((NI) 1));
									numS = X5BX5D__lkBUIkH7j2jb0vaXPf2frAstrutils(T47_, T48_);
									nimln_(229, "logging.nim");
									pushSafePoint(&TM_7EbqAVTAsJVrNKIE9b0UU9bA_47);
									TM_7EbqAVTAsJVrNKIE9b0UU9bA_47.status = setjmp(TM_7EbqAVTAsJVrNKIE9b0UU9bA_47.context);
									if (TM_7EbqAVTAsJVrNKIE9b0UU9bA_47.status == 0) {
										NI num;
										nimln_(230, "logging.nim");
										num = nsuParseInt(numS);
										nimln_(231, "logging.nim");
										{
											if (!(result < num)) goto LA52_;
											nimln_(232, "logging.nim");
											result = num;
										}
										LA52_: ;
										popSafePoint();
									}
									else {
										popSafePoint();
										setFrame((TFrame*)&FR_);
										if (isObj(getCurrentException()->Sup.m_type, (&NTI_Gi06FkNeykJn7mrqRZYrkA_))) {
											TM_7EbqAVTAsJVrNKIE9b0UU9bA_47.status = 0;
											popCurrentException();
										}
									}
									if (TM_7EbqAVTAsJVrNKIE9b0UU9bA_47.status != 0) reraiseException();
								}
								LA45_: ;
							}
							LA38_: ;
						}
						LA18_: ;
						nimln_(793, "os.nim");
						{
							NI32 T58_;
							NI32 errCode;
							T58_ = (NI32)0;
							T58_ = Dl_140243_(h, (&f));
							if (!(T58_ == ((NI32) 0))) goto LA59_;
							nimln_(794, "os.nim");
							errCode = Dl_139630_();
							nimln_(795, "os.nim");
							{
								if (!(errCode == ((NI32) 18))) goto LA63_;
								goto LA13;
							}
							goto LA61_;
							LA63_: ;
							{
								nimln_(796, "os.nim");
								raiseOSError_bEwAamo1N7TKcaU9akpiyIg(errCode, ((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_21));
							}
							LA61_: ;
						}
						LA59_: ;
					}
				} LA13: ;
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&FR_);
			}
			{
				nimln_(782, "os.nim");
				Dl_140401_(h);
			}
			if (TM_7EbqAVTAsJVrNKIE9b0UU9bA_40.status != 0) reraiseException();
		}
		LA10_: ;
	}
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_ysBAzRrImnix9cpwFmcaxZQ)(void* p, NI op) {
	tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g* a;
	a = (tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g*)p;
	nimGCvisit((void*)(*a).Sup.Sup.fmtStr, op);
	nimGCvisit((void*)(*a).baseName, op);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g*, newRollingFileLogger_mNP2yaC4s3yw9ctYnGfc00w)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold, NimStringDesc* fmtStr, NI maxLines, NI bufSize) {
	tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("newRollingFileLogger", "logging.nim");
	result = (tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g*)0;
	nimln_(245, "logging.nim");
	result = (tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g*) newObj((&NTI_ysBAzRrImnix9cpwFmcaxZQ_), sizeof(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g));
	(*result).Sup.Sup.Sup.m_type = (&NTI_O2Lvje8yIZTOG9bz4MrKW7g_);
	nimln_(246, "logging.nim");
	(*result).Sup.Sup.levelThreshold = levelThreshold;
	nimln_(247, "logging.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*result).Sup.Sup.fmtStr; (*result).Sup.Sup.fmtStr = copyStringRC1(fmtStr);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(248, "logging.nim");
	(*result).maxLines = maxLines;
	nimln_(249, "logging.nim");
	(*result).bufSize = bufSize;
	nimln_(250, "logging.nim");
	(*result).Sup.file = open_hqzpWQbdA2B8l9a6wwNoP4g(filename, mode, (*result).bufSize);
	nimln_(251, "logging.nim");
	(*result).curLine = ((NI) 0);
	nimln_(252, "logging.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = (*result).baseName; (*result).baseName = copyStringRC1(filename);
	if (T2_) nimGCunrefNoCycle(T2_);
	nimln_(253, "logging.nim");
	(*result).baseMode = mode;
	nimln_(255, "logging.nim");
	(*result).logFiles = countFiles_0BZmLO9amvNhBRMKPzZQ6Wg(filename);
	nimln_(257, "logging.nim");
	{
		if (!(mode == ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 4))) goto LA5_;
		nimln_(259, "logging.nim");
		(*result).curLine = countLogLines_6gVzeXzXkdVD4DK52Nyw4A(result);
	}
	LA5_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, rotate_syaiH6U59aM6LtCRd9aW2tXg)(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g* logger) {
	tyTuple_7q7q3E6Oj24ZNVJb9aonhAg T1_;
	NimStringDesc* dir;
	NimStringDesc* name;
	NimStringDesc* ext;
	nimfr_("rotate", "logging.nim");
	nimln_(262, "logging.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	nossplitFile((*logger).baseName, (&T1_));
	dir = (NimStringDesc*)0;
	dir = T1_.Field0;
	name = (NimStringDesc*)0;
	name = T1_.Field1;
	ext = (NimStringDesc*)0;
	ext = T1_.Field2;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(263, "logging.nim");
		colontmp_ = (*logger).logFiles;
		nimln_(2015, "system.nim");
		res = colontmp_;
		{
			nimln_(2016, "system.nim");
			while (1) {
				NimStringDesc* srcSuff;
				NimStringDesc* T12_;
				NimStringDesc* T13_;
				NimStringDesc* T14_;
				NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_49;
				NimStringDesc* T15_;
				NimStringDesc* T16_;
				NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_50;
				nimln_(263, "logging.nim");
				if (!(((NI) 0) <= res)) goto LA4;
				nimln_(2017, "system.nim");
				i = res;
				nimln_(264, "logging.nim");
				{
					NimStringDesc* T9_;
					NimStringDesc* T10_;
					nimln_(398, "system.nim");
					nimln_(264, "logging.nim");
					if (!!((i == ((NI) 0)))) goto LA7_;
					T9_ = (NimStringDesc*)0;
					T10_ = (NimStringDesc*)0;
					T10_ = nimIntToStr(i);
					T9_ = rawNewString(T10_->Sup.len + 1);
appendChar(T9_, 46);
appendString(T9_, T10_);
					srcSuff = T9_;
				}
				goto LA5_;
				LA7_: ;
				{
					srcSuff = copyString(((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_21));
				}
				LA5_: ;
				nimln_(265, "logging.nim");
				T12_ = (NimStringDesc*)0;
				T12_ = rawNewString(name->Sup.len + ext->Sup.len + srcSuff->Sup.len + 0);
appendString(T12_, name);
appendString(T12_, ext);
appendString(T12_, srcSuff);
				T13_ = (NimStringDesc*)0;
				T13_ = slash__lXoMhn1ZYc9cAJa9bfA61msg(dir, T12_);
				nimln_(266, "logging.nim");
				T14_ = (NimStringDesc*)0;
				TM_7EbqAVTAsJVrNKIE9b0UU9bA_49 = addInt(i, ((NI) 1));
				T15_ = (NimStringDesc*)0;
				T15_ = nimIntToStr((NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_49));
				T14_ = rawNewString(name->Sup.len + ext->Sup.len + T15_->Sup.len + 1);
appendString(T14_, name);
appendString(T14_, ext);
appendChar(T14_, 46);
appendString(T14_, T15_);
				T16_ = (NimStringDesc*)0;
				T16_ = slash__lXoMhn1ZYc9cAJa9bfA61msg(dir, T14_);
				nosmoveFile(T13_, T16_);
				nimln_(2018, "system.nim");
				TM_7EbqAVTAsJVrNKIE9b0UU9bA_50 = subInt(res, ((NI) 1));
				res = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_50);
			} LA4: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, log_Z1wwTzhV8hfwxjrAweVVZQ)(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	nimfr_("log", "logging.nim");
	nimln_(270, "logging.nim");
	{
		NIM_BOOL T3_;
		tyArray_nHXaesL0DJZHyVS07ARPRA T11_;
		NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_52;
		T3_ = (NIM_BOOL)0;
		T3_ = (level_hzbRBHMSEnpbC61ptpdKmA <= level);
		if (!(T3_)) goto LA4_;
		T3_ = ((*logger).Sup.Sup.levelThreshold <= level);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(271, "logging.nim");
		{
			NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_51;
			if (!((*logger).maxLines <= (*logger).curLine)) goto LA9_;
			nimln_(272, "logging.nim");
			close_BWnr8V7RERYno9bIdPmw8Hw_2((*logger).Sup.file);
			nimln_(273, "logging.nim");
			rotate_syaiH6U59aM6LtCRd9aW2tXg(logger);
			nimln_(274, "logging.nim");
			TM_7EbqAVTAsJVrNKIE9b0UU9bA_51 = addInt((*logger).logFiles, ((NI) 1));
			(*logger).logFiles = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_51);
			nimln_(275, "logging.nim");
			(*logger).curLine = ((NI) 0);
			nimln_(276, "logging.nim");
			(*logger).Sup.file = open_hqzpWQbdA2B8l9a6wwNoP4g((*logger).baseName, (*logger).baseMode, (*logger).bufSize);
		}
		LA9_: ;
		nimln_(278, "logging.nim");
		memset((void*)T11_, 0, sizeof(T11_));
		T11_[0] = substituteLog_GUiLaZ0b21eA2W7LstPGkg((*logger).Sup.Sup.fmtStr, level, args, argsLen_0);
		writeLine_rBQVO3cm3BhnA9aEFD7PG6Qlogging((*logger).Sup.file, T11_, 1);
		nimln_(279, "logging.nim");
		{
			if (!((96 &(1U<<((NU)(level)&7U)))!=0)) goto LA14_;
			flushFile_BWnr8V7RERYno9bIdPmw8Hw_3((*logger).Sup.file);
		}
		LA14_: ;
		nimln_(280, "logging.nim");
		TM_7EbqAVTAsJVrNKIE9b0UU9bA_52 = addInt((*logger).curLine, ((NI) 1));
		(*logger).curLine = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_52);
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, logLoop_Y1QvvdpC0FmKBCafruMWGQ)(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	nimfr_("logLoop", "logging.nim");
	{
		tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* logger;
		NI i;
		NI L;
		NI T2_;
		logger = (tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug*)0;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (handlers_OpA9asfHAsjfRTcLDwhkNfA ? handlers_OpA9asfHAsjfRTcLDwhkNfA->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_53;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(handlers_OpA9asfHAsjfRTcLDwhkNfA->Sup.len)) raiseIndexError();
				logger = handlers_OpA9asfHAsjfRTcLDwhkNfA->data[i];
				nimln_(286, "logging.nim");
				{
					if (!((*logger).levelThreshold <= level)) goto LA7_;
					nimln_(287, "logging.nim");
					log_15uDclQ9cwzr06QrR8BYZqA(logger, level, args, argsLen_0);
				}
				LA7_: ;
				nimln_(3809, "system.nim");
				TM_7EbqAVTAsJVrNKIE9b0UU9bA_53 = addInt(i, ((NI) 1));
				i = (NI)(TM_7EbqAVTAsJVrNKIE9b0UU9bA_53);
				nimln_(3810, "system.nim");
				{
					NI T11_;
					T11_ = (handlers_OpA9asfHAsjfRTcLDwhkNfA ? handlers_OpA9asfHAsjfRTcLDwhkNfA->Sup.len : 0);
					if (!!((T11_ == L))) goto LA12_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_7EbqAVTAsJVrNKIE9b0UU9bA_54));
				}
				LA12_: ;
			} LA4: ;
		}
	}
	popFrame();
}

static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefRC1", "gc.nim");
	nimln_(258, "gc.nim");
	T1_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, addHandler_tg0stk9atBM54nh79a3PBrOA)(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* handler) {
	NI T5_;
	nimfr_("addHandler", "logging.nim");
	nimln_(345, "logging.nim");
	{
		if (!(handlers_OpA9asfHAsjfRTcLDwhkNfA == 0)) goto LA3_;
		if (handlers_OpA9asfHAsjfRTcLDwhkNfA) { nimGCunrefRC1(handlers_OpA9asfHAsjfRTcLDwhkNfA); handlers_OpA9asfHAsjfRTcLDwhkNfA = NIM_NIL; }
		handlers_OpA9asfHAsjfRTcLDwhkNfA = (tySequence_gngkqwVsuclWSwd9cJImMYw*) newSeqRC1((&NTI_gngkqwVsuclWSwd9cJImMYw_), 0);
	}
	LA3_: ;
	nimln_(346, "logging.nim");
	handlers_OpA9asfHAsjfRTcLDwhkNfA = (tySequence_gngkqwVsuclWSwd9cJImMYw*) incrSeqV2(&(handlers_OpA9asfHAsjfRTcLDwhkNfA)->Sup, sizeof(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug*));
	T5_ = handlers_OpA9asfHAsjfRTcLDwhkNfA->Sup.len++;
	asgnRef((void**) (&handlers_OpA9asfHAsjfRTcLDwhkNfA->data[T5_]), handler);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tySequence_gngkqwVsuclWSwd9cJImMYw*, getHandlers_T85bEDQSt0UQcLetx56kcQ)(void) {
	tySequence_gngkqwVsuclWSwd9cJImMYw* result;
	nimfr_("getHandlers", "logging.nim");
{	result = (tySequence_gngkqwVsuclWSwd9cJImMYw*)0;
	nimln_(350, "logging.nim");
	genericSeqAssign((&result), handlers_OpA9asfHAsjfRTcLDwhkNfA, (&NTI_gngkqwVsuclWSwd9cJImMYw_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setLogFilter_CbDskkOBDVPDz8J81JVpdw)(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg lvl) {
	nimfr_("setLogFilter", "logging.nim");
	nimln_(354, "logging.nim");
	level_hzbRBHMSEnpbC61ptpdKmA = lvl;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg, getLogFilter_VpsumEqOIaR8tmI1dyA6cA)(void) {
	tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg result;
	nimfr_("getLogFilter", "logging.nim");
{	result = (tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg)0;
	nimln_(358, "logging.nim");
	result = level_hzbRBHMSEnpbC61ptpdKmA;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_loggingInit000)(void) {
	nimfr_("logging", "logging.nim");
nimRegisterThreadLocalMarker(TM_7EbqAVTAsJVrNKIE9b0UU9bA_13);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_loggingDatInit000)(void) {
static TNimNode* TM_7EbqAVTAsJVrNKIE9b0UU9bA_9[2];
static TNimNode* TM_7EbqAVTAsJVrNKIE9b0UU9bA_10[8];
NI TM_7EbqAVTAsJVrNKIE9b0UU9bA_12;
static char* NIM_CONST TM_7EbqAVTAsJVrNKIE9b0UU9bA_11[8] = {
"lvlAll", 
"lvlDebug", 
"lvlInfo", 
"lvlNotice", 
"lvlWarn", 
"lvlError", 
"lvlFatal", 
"lvlNone"};
static TNimNode* TM_7EbqAVTAsJVrNKIE9b0UU9bA_48[6];
static TNimNode TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[21];
NTI_igsiUXBFuP9cp5KwKL5yiug_.size = sizeof(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug);
NTI_igsiUXBFuP9cp5KwKL5yiug_.kind = 17;
NTI_igsiUXBFuP9cp5KwKL5yiug_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_9[0] = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[1];
NTI_pW4mH4lipH6u2NKDGEWdGg_.size = sizeof(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg);
NTI_pW4mH4lipH6u2NKDGEWdGg_.kind = 14;
NTI_pW4mH4lipH6u2NKDGEWdGg_.base = 0;
NTI_pW4mH4lipH6u2NKDGEWdGg_.flags = 3;
for (TM_7EbqAVTAsJVrNKIE9b0UU9bA_12 = 0; TM_7EbqAVTAsJVrNKIE9b0UU9bA_12 < 8; TM_7EbqAVTAsJVrNKIE9b0UU9bA_12++) {
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[TM_7EbqAVTAsJVrNKIE9b0UU9bA_12+2].kind = 1;
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[TM_7EbqAVTAsJVrNKIE9b0UU9bA_12+2].offset = TM_7EbqAVTAsJVrNKIE9b0UU9bA_12;
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[TM_7EbqAVTAsJVrNKIE9b0UU9bA_12+2].name = TM_7EbqAVTAsJVrNKIE9b0UU9bA_11[TM_7EbqAVTAsJVrNKIE9b0UU9bA_12];
TM_7EbqAVTAsJVrNKIE9b0UU9bA_10[TM_7EbqAVTAsJVrNKIE9b0UU9bA_12] = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[TM_7EbqAVTAsJVrNKIE9b0UU9bA_12+2];
}
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[10].len = 8; TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[10].kind = 2; TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[10].sons = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_10[0];
NTI_pW4mH4lipH6u2NKDGEWdGg_.node = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[10];
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[1].kind = 1;
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[1].offset = offsetof(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug, levelThreshold);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[1].typ = (&NTI_pW4mH4lipH6u2NKDGEWdGg_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[1].name = "levelThreshold";
TM_7EbqAVTAsJVrNKIE9b0UU9bA_9[1] = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[11];
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[11].kind = 1;
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[11].offset = offsetof(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug, fmtStr);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[11].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[11].name = "fmtStr";
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[0].len = 2; TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[0].kind = 2; TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[0].sons = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_9[0];
NTI_igsiUXBFuP9cp5KwKL5yiug_.node = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[0];
NTI_GA38ua3ZxEHLLuvtleWIKw_.size = sizeof(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug*);
NTI_GA38ua3ZxEHLLuvtleWIKw_.kind = 22;
NTI_GA38ua3ZxEHLLuvtleWIKw_.base = (&NTI_igsiUXBFuP9cp5KwKL5yiug_);
NTI_GA38ua3ZxEHLLuvtleWIKw_.marker = Marker_tyRef_GA38ua3ZxEHLLuvtleWIKw;
NTI_gngkqwVsuclWSwd9cJImMYw_.size = sizeof(tySequence_gngkqwVsuclWSwd9cJImMYw*);
NTI_gngkqwVsuclWSwd9cJImMYw_.kind = 24;
NTI_gngkqwVsuclWSwd9cJImMYw_.base = (&NTI_GA38ua3ZxEHLLuvtleWIKw_);
NTI_gngkqwVsuclWSwd9cJImMYw_.marker = Marker_tySequence_gngkqwVsuclWSwd9cJImMYw;
NTI_QaTO46vt5hgK2eu9ah2xGrA_.size = sizeof(tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA);
NTI_QaTO46vt5hgK2eu9ah2xGrA_.kind = 17;
NTI_QaTO46vt5hgK2eu9ah2xGrA_.base = (&NTI_igsiUXBFuP9cp5KwKL5yiug_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[12].len = 0; TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[12].kind = 2;
NTI_QaTO46vt5hgK2eu9ah2xGrA_.node = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[12];
NTI_sld5f81MZHmkeseB9a2pc9cA_.size = sizeof(tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA*);
NTI_sld5f81MZHmkeseB9a2pc9cA_.kind = 22;
NTI_sld5f81MZHmkeseB9a2pc9cA_.base = (&NTI_QaTO46vt5hgK2eu9ah2xGrA_);
NTI_sld5f81MZHmkeseB9a2pc9cA_.marker = Marker_tyRef_sld5f81MZHmkeseB9a2pc9cA;
NTI_DiHvgyNJFmeALM5A2LhG3w_.size = sizeof(tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w);
NTI_DiHvgyNJFmeALM5A2LhG3w_.kind = 17;
NTI_DiHvgyNJFmeALM5A2LhG3w_.base = (&NTI_igsiUXBFuP9cp5KwKL5yiug_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[13].kind = 1;
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[13].offset = offsetof(tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w, file);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[13].typ = (&NTI_7BHnQsEj49a9c6QtudqWTo1w_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[13].name = "file";
NTI_DiHvgyNJFmeALM5A2LhG3w_.node = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[13];
NTI_SgN9afM7kbfbLF8z1Uhhmpw_.size = sizeof(tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w*);
NTI_SgN9afM7kbfbLF8z1Uhhmpw_.kind = 22;
NTI_SgN9afM7kbfbLF8z1Uhhmpw_.base = (&NTI_DiHvgyNJFmeALM5A2LhG3w_);
NTI_SgN9afM7kbfbLF8z1Uhhmpw_.marker = Marker_tyRef_SgN9afM7kbfbLF8z1Uhhmpw;
NTI_O2Lvje8yIZTOG9bz4MrKW7g_.size = sizeof(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g);
NTI_O2Lvje8yIZTOG9bz4MrKW7g_.kind = 17;
NTI_O2Lvje8yIZTOG9bz4MrKW7g_.base = (&NTI_DiHvgyNJFmeALM5A2LhG3w_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_48[0] = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[15];
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[15].kind = 1;
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[15].offset = offsetof(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g, maxLines);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[15].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[15].name = "maxLines";
TM_7EbqAVTAsJVrNKIE9b0UU9bA_48[1] = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[16];
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[16].kind = 1;
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[16].offset = offsetof(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g, curLine);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[16].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[16].name = "curLine";
TM_7EbqAVTAsJVrNKIE9b0UU9bA_48[2] = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[17];
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[17].kind = 1;
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[17].offset = offsetof(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g, baseName);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[17].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[17].name = "baseName";
TM_7EbqAVTAsJVrNKIE9b0UU9bA_48[3] = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[18];
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[18].kind = 1;
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[18].offset = offsetof(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g, baseMode);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[18].typ = (&NTI_fVUBHvW79bXUw1j55Oo9avSQ_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[18].name = "baseMode";
TM_7EbqAVTAsJVrNKIE9b0UU9bA_48[4] = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[19];
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[19].kind = 1;
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[19].offset = offsetof(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g, logFiles);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[19].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[19].name = "logFiles";
TM_7EbqAVTAsJVrNKIE9b0UU9bA_48[5] = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[20];
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[20].kind = 1;
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[20].offset = offsetof(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g, bufSize);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[20].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[20].name = "bufSize";
TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[14].len = 6; TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[14].kind = 2; TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[14].sons = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_48[0];
NTI_O2Lvje8yIZTOG9bz4MrKW7g_.node = &TM_7EbqAVTAsJVrNKIE9b0UU9bA_0[14];
NTI_ysBAzRrImnix9cpwFmcaxZQ_.size = sizeof(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g*);
NTI_ysBAzRrImnix9cpwFmcaxZQ_.kind = 22;
NTI_ysBAzRrImnix9cpwFmcaxZQ_.base = (&NTI_O2Lvje8yIZTOG9bz4MrKW7g_);
NTI_ysBAzRrImnix9cpwFmcaxZQ_.marker = Marker_tyRef_ysBAzRrImnix9cpwFmcaxZQ;
}

