/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\nim17\nim-0.17.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim17\nim-0.17.2\lib -o c:\Webdev\dmltests\nim\nimcache\gtk2_gtk2.o c:\Webdev\dmltests\nim\nimcache\gtk2_gtk2.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw;
typedef struct tyObject_TButton_zkMLVjvhqBf5x5ia9bhBZLA tyObject_TButton_zkMLVjvhqBf5x5ia9bhBZLA;
typedef struct tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw;
typedef struct tyObject_TVBox_159bZqc5AeQ9ct4wkWgJmv2w tyObject_TVBox_159bZqc5AeQ9ct4wkWgJmv2w;
typedef struct tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w;
typedef struct tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA;
typedef struct tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ;
typedef struct tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA;
typedef struct tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg;
typedef struct tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ;
typedef struct tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ;
typedef struct tyObject_TStyle_9b5KThw81CgYurztY67hTiQ tyObject_TStyle_9b5KThw81CgYurztY67hTiQ;
typedef struct tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg;
typedef struct tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw;
typedef struct tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg;
typedef struct tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg;
typedef struct tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg;
typedef struct tyObject_TMisc_GZgvr3NWk4gh9brfsR3nAAw tyObject_TMisc_GZgvr3NWk4gh9brfsR3nAAw;
typedef struct tyObject_TAttrList_EVP824dXKE9blEQXanTMtVA tyObject_TAttrList_EVP824dXKE9blEQXanTMtVA;
typedef struct tyObject_TLayout_7oe2Q1AGd24z1MGQP6XF5Q tyObject_TLayout_7oe2Q1AGd24z1MGQP6XF5Q;
typedef struct tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw;
typedef struct tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ;
typedef struct tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg;
typedef struct tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw;
typedef struct tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA;
typedef struct tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ;
typedef struct tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA;
typedef struct tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ;
typedef struct tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ;
typedef struct tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw;
typedef struct tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA;
typedef struct tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw*, tyProc_GzcOY9cVu1lsl7sSbg21wLA) (NI32 thetype);
typedef N_CDECL_PTR(tyObject_TButton_zkMLVjvhqBf5x5ia9bhBZLA*, tyProc_SymZ1fI9bOYI0NMuNHWWzQA) (NCSTRING label);
typedef N_CDECL_PTR(tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw*, tyProc_svsYVcexLgWbTTchzdBlEw) (NCSTRING str);
typedef N_CDECL_PTR(tyObject_TVBox_159bZqc5AeQ9ct4wkWgJmv2w*, tyProc_iVsVtRwjSknbJ89bRvYYZng) (int homogeneous, int spacing);
typedef N_CDECL_PTR(void, tyProc_bFKcigahFhpcey9cuvArvCg) (tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw* label, NCSTRING str);
typedef NCSTRING tyArray_M0HRG1TxfsgVFfIesgAGBg[256];
typedef N_CDECL_PTR(void, tyProc_LCJy9bQFEE8ObaRc29a4n3LA) (void* argc, void* argv);
typedef N_CDECL_PTR(void, tyProc_Tw3byRoHVQ9cPeqOGC7NE3Q) (tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw* window, NCSTRING title);
typedef N_CDECL_PTR(void, tyProc_GiaX9curpZgDK9bkLqFXMqZA) (tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w* container, tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* widget);
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* para1);
typedef N_CDECL_PTR(unsigned long, tyProc_lM09bnhBcrbxA71al1q6I3w) (tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ* anObject, NCSTRING name, tyProc_32w2ZypAyMWuajvi2Jt79cg fun, void* unknown1, void* func_data, void* unknown2, NI unknown3, NI unknown4);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(void, tyProc_VoMKl77iPAbE7kH39bhiGLA) (tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* widget);
struct tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ {
tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ* g_class;
};
struct tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg {
tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ g_type_instance;
NU32 ref_count;
void* qdata;
};
struct tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
NU32 flags;
};
struct tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg {
int width;
int height;
};
struct tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw {
int x;
int y;
int width;
int height;
};
struct tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA {
  tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ Sup;
NU16 private_flags;
NU8 state;
NU8 saved_state;
NCSTRING name;
tyObject_TStyle_9b5KThw81CgYurztY67hTiQ* style;
tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg requisition;
tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw allocation;
tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg* window;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* parent;
};
struct tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w {
  tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA Sup;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* focus_child;
NU32 Container_flag0;
};
struct tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA {
  tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w Sup;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* child;
};
struct tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw {
  tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA Sup;
NCSTRING title;
NCSTRING wmclass_name;
NCSTRING wmclass_class;
NCSTRING wm_role;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* focus_widget;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* default_widget;
tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw* transient_parent;
void* geometry_info;
tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg* frame;
tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg* group;
NU16 configure_request_count;
NU32 window_flag0;
NU32 frame_left;
NU32 frame_top;
NU32 frame_right;
NU32 frame_bottom;
NU32 keys_changed_handler;
NU32 mnemonic_modifier;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
struct tyObject_TButton_zkMLVjvhqBf5x5ia9bhBZLA {
  tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA Sup;
tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg* event_window;
NCSTRING label_text;
NU32 activate_timeout;
NU16 button_flag0;
};
struct tyObject_TMisc_GZgvr3NWk4gh9brfsR3nAAw {
  tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA Sup;
float xalign;
float yalign;
NU16 xpad;
NU16 ypad;
};
struct tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw {
  tyObject_TMisc_GZgvr3NWk4gh9brfsR3nAAw Sup;
NCSTRING label;
NU16 Label_flag0;
NU32 mnemonic_keyval;
NCSTRING text;
tyObject_TAttrList_EVP824dXKE9blEQXanTMtVA* attrs;
tyObject_TAttrList_EVP824dXKE9blEQXanTMtVA* effective_attrs;
tyObject_TLayout_7oe2Q1AGd24z1MGQP6XF5Q* layout;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* mnemonic_widget;
tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw* mnemonic_window;
void* select_info;
};
struct tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw {
  tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w Sup;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* children;
NI16 spacing;
NU16 box_flag0;
};
struct tyObject_TVBox_159bZqc5AeQ9ct4wkWgJmv2w {
  tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw Sup;
};
struct tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ {
unsigned long g_type;
};
struct tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg {
NU32 pixel;
NU16 red;
NU16 green;
NU16 blue;
};
typedef tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg tyArray_9chWiMwZsMCYI2hkwl9cKGsg[5];
typedef tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* tyArray_mhiVER3NxWObr8Zo003MOg[5];
typedef tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ* tyArray_9a8bp6zR07xOSfUOBUwiOJQ[5];
struct tyObject_TStyle_9b5KThw81CgYurztY67hTiQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg fg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg bg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg light;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg dark;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg mid;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg base;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text_aa;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg black;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg white;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* font_desc;
int xthickness;
int ythickness;
tyArray_mhiVER3NxWObr8Zo003MOg fg_gc;
tyArray_mhiVER3NxWObr8Zo003MOg bg_gc;
tyArray_mhiVER3NxWObr8Zo003MOg light_gc;
tyArray_mhiVER3NxWObr8Zo003MOg dark_gc;
tyArray_mhiVER3NxWObr8Zo003MOg mid_gc;
tyArray_mhiVER3NxWObr8Zo003MOg text_gc;
tyArray_mhiVER3NxWObr8Zo003MOg base_gc;
tyArray_mhiVER3NxWObr8Zo003MOg text_aa_gc;
tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* black_gc;
tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* white_gc;
tyArray_9a8bp6zR07xOSfUOBUwiOJQ bg_pixmap;
NU32 attach_count;
int depth;
tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA* colormap;
tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ* private_font;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* private_font_desc;
tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ* rc_style;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* styles;
void* property_cache;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* icon_factories;
};
struct tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
};
struct tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg {
  tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA Sup;
};
struct tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* grabs;
};
struct tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
};
struct tyObject_TAttrList_EVP824dXKE9blEQXanTMtVA {
char dummy;
};
struct tyObject_TLayout_7oe2Q1AGd24z1MGQP6XF5Q {
char dummy;
};
struct tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ {
void* data;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* next;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* prev;
};
struct tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw {
char dummy;
};
struct tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
int clip_x_origin;
int clip_y_origin;
int ts_x_origin;
int ts_y_origin;
tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA* colormap;
};
struct tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ {
  tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA Sup;
};
struct tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
int size;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg* colors;
tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg* visual;
void* windowing_data;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
typedef NU8 tyEnum_TFontType_nhWPhgR9a7aI9ahmxS3NZHhg;
struct tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ {
tyEnum_TFontType_nhWPhgR9a7aI9ahmxS3NZHhg type_0;
int ascent;
int descent;
};
typedef NCSTRING tyArray_J70ZWTopZxz1yNsmbJgQug[5];
typedef NI32 tyArray_CWoQ39cMobP9audxQ5BU3NgA[5];
struct tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
NCSTRING name;
tyArray_J70ZWTopZxz1yNsmbJgQug bg_pixmap_name;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* font_desc;
tyArray_CWoQ39cMobP9audxQ5BU3NgA color_flags;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg fg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg bg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg base;
int xthickness;
int ythickness;
void* rc_properties;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* rc_style_lists;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* icon_factories;
NU16 RcStyle_flag0;
};
struct tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw {
void* data;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* next;
};
typedef NU8 tyEnum_TVisualType_TR8Ew8oq9b8acgpEx6OHNhQ;
typedef NU8 tyEnum_TByteOrder_yshrw8HYFOH63IsYj7iZOQ;
struct tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyEnum_TVisualType_TR8Ew8oq9b8acgpEx6OHNhQ TheType;
int depth;
tyEnum_TByteOrder_yshrw8HYFOH63IsYj7iZOQ byte_order;
int colormap_size;
int bits_per_rgb;
NU32 red_mask;
int red_shift;
int red_prec;
NU32 green_mask;
int green_shift;
int green_prec;
NU32 blue_mask;
int blue_shift;
int blue_prec;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_hZetKJO9brljcjvVpohVOXg_2;
tyProc_GzcOY9cVu1lsl7sSbg21wLA Dl_144201_;
tyProc_SymZ1fI9bOYI0NMuNHWWzQA Dl_145358_;
tyProc_svsYVcexLgWbTTchzdBlEw Dl_144578_;
tyProc_iVsVtRwjSknbJ89bRvYYZng Dl_146973_;
tyProc_bFKcigahFhpcey9cuvArvCg Dl_144584_;
tyProc_LCJy9bQFEE8ObaRc29a4n3LA Dl_151621_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyProc_Tw3byRoHVQ9cPeqOGC7NE3Q Dl_144204_;
tyProc_GiaX9curpZgDK9bkLqFXMqZA Dl_143824_;
tyProc_lM09bnhBcrbxA71al1q6I3w Dl_171478_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_151627_;
tyProc_VoMKl77iPAbE7kH39bhiGLA Dl_143106_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_151619_;
STRING_LITERAL(TM_hZetKJO9brljcjvVpohVOXg_4, "libgtk-win32-2.0-0.dll", 22);
STRING_LITERAL(TM_hZetKJO9brljcjvVpohVOXg_5, "libgtk-win32-2.0-0.dll", 22);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, nim_init_BI4x6i9c40Tf9b1BitVLexNw)(void) {
	tyArray_M0HRG1TxfsgVFfIesgAGBg cmdLine;
	int cmdCount;
	nimfr_("nim_init", "gtk2.nim");
	memset((void*)cmdLine, 0, sizeof(cmdLine));
	cmdCount = (int)0;
	nimln_(17102, "gtk2.nim");
	Dl_151621_(((void*) (cmdLine)), ((void*) ((&cmdCount))));
	popFrame();
}

N_NIMCALL(unsigned long, signal_connect_bnI6bs39clYFYxM3uaej9c5g)(tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ* anObject, NCSTRING name, tyProc_32w2ZypAyMWuajvi2Jt79cg fun, void* func_data) {
	unsigned long result;
	nimfr_("signal_connect", "gtk2.nim");
	result = (unsigned long)0;
	nimln_(14719, "gtk2.nim");
	result = Dl_171478_(anObject, name, fun, NIM_NIL, func_data, NIM_NIL, ((NI) 0), ((NI) 0));
	popFrame();
	return result;
}

N_NIMCALL(tyProc_32w2ZypAyMWuajvi2Jt79cg, SIGNAL_FUNC_l4lHLP2AG9blznFImvMxrpA)(void* f) {
	tyProc_32w2ZypAyMWuajvi2Jt79cg result;
	nimfr_("SIGNAL_FUNC", "gtk2.nim");
	result = (tyProc_32w2ZypAyMWuajvi2Jt79cg)0;
	nimln_(10917, "gtk2.nim");
	result = ((tyProc_32w2ZypAyMWuajvi2Jt79cg) (f));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, gtk2_gtk2Init000)(void) {
	nimfr_("gtk2", "gtk2.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, gtk2_gtk2DatInit000)(void) {
if (!((TM_hZetKJO9brljcjvVpohVOXg_2 = nimLoadLibrary((NimStringDesc*) &TM_hZetKJO9brljcjvVpohVOXg_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_hZetKJO9brljcjvVpohVOXg_5);
	Dl_144201_ = (tyProc_GzcOY9cVu1lsl7sSbg21wLA) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_window_new");
	Dl_145358_ = (tyProc_SymZ1fI9bOYI0NMuNHWWzQA) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_button_new_with_label");
	Dl_144578_ = (tyProc_svsYVcexLgWbTTchzdBlEw) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_label_new");
	Dl_146973_ = (tyProc_iVsVtRwjSknbJ89bRvYYZng) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_vbox_new");
	Dl_144584_ = (tyProc_bFKcigahFhpcey9cuvArvCg) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_label_set_text");
	Dl_151621_ = (tyProc_LCJy9bQFEE8ObaRc29a4n3LA) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_init");
	Dl_144204_ = (tyProc_Tw3byRoHVQ9cPeqOGC7NE3Q) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_window_set_title");
	Dl_143824_ = (tyProc_GiaX9curpZgDK9bkLqFXMqZA) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_container_add");
	Dl_171478_ = (tyProc_lM09bnhBcrbxA71al1q6I3w) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_signal_connect_full");
	Dl_151627_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_main_quit");
	Dl_143106_ = (tyProc_VoMKl77iPAbE7kH39bhiGLA) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_widget_show_all");
	Dl_151619_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_main");
}

