/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\nim17\nim-0.17.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim17\nim-0.17.2\lib -o c:\Webdev\dmltests\nim\nimcache\GTKwindow.o c:\Webdev\dmltests\nim\nimcache\GTKwindow.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw;
typedef struct tyObject_TButton_zkMLVjvhqBf5x5ia9bhBZLA tyObject_TButton_zkMLVjvhqBf5x5ia9bhBZLA;
typedef struct tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw;
typedef struct tyObject_TVBox_159bZqc5AeQ9ct4wkWgJmv2w tyObject_TVBox_159bZqc5AeQ9ct4wkWgJmv2w;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w;
typedef struct tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA;
typedef struct tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ;
typedef struct tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA;
typedef struct tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg;
typedef struct tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ;
typedef struct tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ;
typedef struct tyObject_TStyle_9b5KThw81CgYurztY67hTiQ tyObject_TStyle_9b5KThw81CgYurztY67hTiQ;
typedef struct tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg;
typedef struct tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw;
typedef struct tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg;
typedef struct tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg;
typedef struct tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg;
typedef struct tyObject_TMisc_GZgvr3NWk4gh9brfsR3nAAw tyObject_TMisc_GZgvr3NWk4gh9brfsR3nAAw;
typedef struct tyObject_TAttrList_EVP824dXKE9blEQXanTMtVA tyObject_TAttrList_EVP824dXKE9blEQXanTMtVA;
typedef struct tyObject_TLayout_7oe2Q1AGd24z1MGQP6XF5Q tyObject_TLayout_7oe2Q1AGd24z1MGQP6XF5Q;
typedef struct tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw;
typedef struct tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ;
typedef struct tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg;
typedef struct tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw;
typedef struct tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA;
typedef struct tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ;
typedef struct tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA;
typedef struct tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ;
typedef struct tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ;
typedef struct tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw;
typedef struct tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA;
typedef struct tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg;
typedef N_CDECL_PTR(tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw*, tyProc_GzcOY9cVu1lsl7sSbg21wLA) (NI32 thetype);
typedef N_CDECL_PTR(tyObject_TButton_zkMLVjvhqBf5x5ia9bhBZLA*, tyProc_SymZ1fI9bOYI0NMuNHWWzQA) (NCSTRING label);
typedef N_CDECL_PTR(tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw*, tyProc_svsYVcexLgWbTTchzdBlEw) (NCSTRING str);
typedef N_CDECL_PTR(tyObject_TVBox_159bZqc5AeQ9ct4wkWgJmv2w*, tyProc_iVsVtRwjSknbJ89bRvYYZng) (int homogeneous, int spacing);
typedef N_CDECL_PTR(void, tyProc_bFKcigahFhpcey9cuvArvCg) (tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw* label, NCSTRING str);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void, tyProc_Tw3byRoHVQ9cPeqOGC7NE3Q) (tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw* window, NCSTRING title);
typedef N_CDECL_PTR(void, tyProc_GiaX9curpZgDK9bkLqFXMqZA) (tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w* container, tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* widget);
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* para1);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(void, tyProc_VoMKl77iPAbE7kH39bhiGLA) (tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* widget);
struct tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ {
tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ* g_class;
};
struct tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg {
tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ g_type_instance;
NU32 ref_count;
void* qdata;
};
struct tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
NU32 flags;
};
struct tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg {
int width;
int height;
};
struct tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw {
int x;
int y;
int width;
int height;
};
struct tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA {
  tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ Sup;
NU16 private_flags;
NU8 state;
NU8 saved_state;
NCSTRING name;
tyObject_TStyle_9b5KThw81CgYurztY67hTiQ* style;
tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg requisition;
tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw allocation;
tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg* window;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* parent;
};
struct tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w {
  tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA Sup;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* focus_child;
NU32 Container_flag0;
};
struct tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA {
  tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w Sup;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* child;
};
struct tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw {
  tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA Sup;
NCSTRING title;
NCSTRING wmclass_name;
NCSTRING wmclass_class;
NCSTRING wm_role;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* focus_widget;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* default_widget;
tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw* transient_parent;
void* geometry_info;
tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg* frame;
tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg* group;
NU16 configure_request_count;
NU32 window_flag0;
NU32 frame_left;
NU32 frame_top;
NU32 frame_right;
NU32 frame_bottom;
NU32 keys_changed_handler;
NU32 mnemonic_modifier;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
struct tyObject_TButton_zkMLVjvhqBf5x5ia9bhBZLA {
  tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA Sup;
tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg* event_window;
NCSTRING label_text;
NU32 activate_timeout;
NU16 button_flag0;
};
struct tyObject_TMisc_GZgvr3NWk4gh9brfsR3nAAw {
  tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA Sup;
float xalign;
float yalign;
NU16 xpad;
NU16 ypad;
};
struct tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw {
  tyObject_TMisc_GZgvr3NWk4gh9brfsR3nAAw Sup;
NCSTRING label;
NU16 Label_flag0;
NU32 mnemonic_keyval;
NCSTRING text;
tyObject_TAttrList_EVP824dXKE9blEQXanTMtVA* attrs;
tyObject_TAttrList_EVP824dXKE9blEQXanTMtVA* effective_attrs;
tyObject_TLayout_7oe2Q1AGd24z1MGQP6XF5Q* layout;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* mnemonic_widget;
tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw* mnemonic_window;
void* select_info;
};
struct tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw {
  tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w Sup;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* children;
NI16 spacing;
NU16 box_flag0;
};
struct tyObject_TVBox_159bZqc5AeQ9ct4wkWgJmv2w {
  tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw Sup;
};
struct tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ {
unsigned long g_type;
};
struct tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg {
NU32 pixel;
NU16 red;
NU16 green;
NU16 blue;
};
typedef tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg tyArray_9chWiMwZsMCYI2hkwl9cKGsg[5];
typedef tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* tyArray_mhiVER3NxWObr8Zo003MOg[5];
typedef tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ* tyArray_9a8bp6zR07xOSfUOBUwiOJQ[5];
struct tyObject_TStyle_9b5KThw81CgYurztY67hTiQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg fg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg bg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg light;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg dark;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg mid;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg base;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text_aa;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg black;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg white;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* font_desc;
int xthickness;
int ythickness;
tyArray_mhiVER3NxWObr8Zo003MOg fg_gc;
tyArray_mhiVER3NxWObr8Zo003MOg bg_gc;
tyArray_mhiVER3NxWObr8Zo003MOg light_gc;
tyArray_mhiVER3NxWObr8Zo003MOg dark_gc;
tyArray_mhiVER3NxWObr8Zo003MOg mid_gc;
tyArray_mhiVER3NxWObr8Zo003MOg text_gc;
tyArray_mhiVER3NxWObr8Zo003MOg base_gc;
tyArray_mhiVER3NxWObr8Zo003MOg text_aa_gc;
tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* black_gc;
tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* white_gc;
tyArray_9a8bp6zR07xOSfUOBUwiOJQ bg_pixmap;
NU32 attach_count;
int depth;
tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA* colormap;
tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ* private_font;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* private_font_desc;
tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ* rc_style;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* styles;
void* property_cache;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* icon_factories;
};
struct tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
};
struct tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg {
  tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA Sup;
};
struct tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* grabs;
};
struct tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
};
struct tyObject_TAttrList_EVP824dXKE9blEQXanTMtVA {
char dummy;
};
struct tyObject_TLayout_7oe2Q1AGd24z1MGQP6XF5Q {
char dummy;
};
struct tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ {
void* data;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* next;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* prev;
};
struct tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw {
char dummy;
};
struct tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
int clip_x_origin;
int clip_y_origin;
int ts_x_origin;
int ts_y_origin;
tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA* colormap;
};
struct tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ {
  tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA Sup;
};
struct tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
int size;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg* colors;
tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg* visual;
void* windowing_data;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
typedef NU8 tyEnum_TFontType_nhWPhgR9a7aI9ahmxS3NZHhg;
struct tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ {
tyEnum_TFontType_nhWPhgR9a7aI9ahmxS3NZHhg type_0;
int ascent;
int descent;
};
typedef NCSTRING tyArray_J70ZWTopZxz1yNsmbJgQug[5];
typedef NI32 tyArray_CWoQ39cMobP9audxQ5BU3NgA[5];
struct tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
NCSTRING name;
tyArray_J70ZWTopZxz1yNsmbJgQug bg_pixmap_name;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* font_desc;
tyArray_CWoQ39cMobP9audxQ5BU3NgA color_flags;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg fg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg bg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg base;
int xthickness;
int ythickness;
void* rc_properties;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* rc_style_lists;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* icon_factories;
NU16 RcStyle_flag0;
};
struct tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw {
void* data;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* next;
};
typedef NU8 tyEnum_TVisualType_TR8Ew8oq9b8acgpEx6OHNhQ;
typedef NU8 tyEnum_TByteOrder_yshrw8HYFOH63IsYj7iZOQ;
struct tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyEnum_TVisualType_TR8Ew8oq9b8acgpEx6OHNhQ TheType;
int depth;
tyEnum_TByteOrder_yshrw8HYFOH63IsYj7iZOQ byte_order;
int colormap_size;
int bits_per_rgb;
NU32 red_mask;
int red_shift;
int red_prec;
NU32 green_mask;
int green_shift;
int green_prec;
NU32 blue_mask;
int blue_shift;
int blue_prec;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
N_NIMCALL(int, gbool_Hrdrv9auPE5AoQelx9arYFnw)(NIM_BOOL nimbool);
N_NIMCALL(void, clickedMe_1mzfETiHWcbA6Wv5XXfd9ag)(tyObject_TButton_zkMLVjvhqBf5x5ia9bhBZLA** ooo, tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw* lll);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, nim_init_BI4x6i9c40Tf9b1BitVLexNw)(void);
N_NIMCALL(unsigned long, signal_connect_bnI6bs39clYFYxM3uaej9c5g)(tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ* anObject, NCSTRING name, tyProc_32w2ZypAyMWuajvi2Jt79cg fun, void* func_data);
N_NIMCALL(tyProc_32w2ZypAyMWuajvi2Jt79cg, SIGNAL_FUNC_l4lHLP2AG9blznFImvMxrpA)(void* f);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_glib2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_glib2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_atkInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_atkDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_pangoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_pangoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_gdk2pixbufInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_gdk2pixbufDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, cairo_cairoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, cairo_cairoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_gdk2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_gdk2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_gtk2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, gtk2_gtk2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, GTKwindowDatInit000)(void);
tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw* win_KQ7C63XDk33SbVasY9czx6A;
extern tyProc_GzcOY9cVu1lsl7sSbg21wLA Dl_144201_;
tyObject_TButton_zkMLVjvhqBf5x5ia9bhBZLA* button_9c6H9ckeWRn9cApNwfUV21G1Q;
extern tyProc_SymZ1fI9bOYI0NMuNHWWzQA Dl_145358_;
tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw* label_9bZ65bbLQJQnH69bwIgidPKQ;
extern tyProc_svsYVcexLgWbTTchzdBlEw Dl_144578_;
tyObject_TVBox_159bZqc5AeQ9ct4wkWgJmv2w* vbox_kV4agvpNi3He9czgEGcyJFA;
extern tyProc_iVsVtRwjSknbJ89bRvYYZng Dl_146973_;
NI counter_RzmiH7deZf6p3VhuWYxSHw;
extern tyProc_bFKcigahFhpcey9cuvArvCg Dl_144584_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_Tw3byRoHVQ9cPeqOGC7NE3Q Dl_144204_;
extern tyProc_GiaX9curpZgDK9bkLqFXMqZA Dl_143824_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_151627_;
extern tyProc_VoMKl77iPAbE7kH39bhiGLA Dl_143106_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_151619_;
STRING_LITERAL(TM_mr6DDU0YrBs9bVw5ZqBsK4w_3, "You clicked me ", 15);
STRING_LITERAL(TM_mr6DDU0YrBs9bVw5ZqBsK4w_4, " times", 6);

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, clickedMe_1mzfETiHWcbA6Wv5XXfd9ag)(tyObject_TButton_zkMLVjvhqBf5x5ia9bhBZLA** ooo, tyObject_TLabel_to9a2kg9aBjgAR6YMMcEjtUw* lll) {
	NI TM_mr6DDU0YrBs9bVw5ZqBsK4w_2;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("clickedMe", "GTKwindow.nim");
	nimln_(11, "GTKwindow.nim");
	TM_mr6DDU0YrBs9bVw5ZqBsK4w_2 = addInt(counter_RzmiH7deZf6p3VhuWYxSHw, ((NI) 1));
	counter_RzmiH7deZf6p3VhuWYxSHw = (NI)(TM_mr6DDU0YrBs9bVw5ZqBsK4w_2);
	nimln_(12, "GTKwindow.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr(counter_RzmiH7deZf6p3VhuWYxSHw);
	T1_ = rawNewString(T2_->Sup.len + 21);
appendString(T1_, ((NimStringDesc*) &TM_mr6DDU0YrBs9bVw5ZqBsK4w_3));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_mr6DDU0YrBs9bVw5ZqBsK4w_4));
	Dl_144584_(lll, T1_->data);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	gtk2_glib2DatInit000();
	gtk2_atkDatInit000();
	gtk2_pangoDatInit000();
	gtk2_gdk2pixbufDatInit000();
	cairo_cairoDatInit000();
	gtk2_gdk2DatInit000();
	gtk2_gtk2DatInit000();
	GTKwindowDatInit000();
	gtk2_glib2Init000();
	gtk2_atkInit000();
	gtk2_pangoInit000();
	gtk2_gdk2pixbufInit000();
	cairo_cairoInit000();
	gtk2_gdk2Init000();
	gtk2_gtk2Init000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	int T1_;
	tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w* T2_;
	tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* T3_;
	tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w* T4_;
	tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* T5_;
	tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w* T6_;
	tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* T7_;
	tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ* T8_;
	tyProc_32w2ZypAyMWuajvi2Jt79cg T9_;
	unsigned long T10_;
	tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ* T11_;
	tyProc_32w2ZypAyMWuajvi2Jt79cg T12_;
	unsigned long T13_;
	tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* T14_;
	nimfr_("GTKwindow", "GTKwindow.nim");
	nimln_(4, "GTKwindow.nim");
	win_KQ7C63XDk33SbVasY9czx6A = Dl_144201_(((NI32) 0));
	nimln_(5, "GTKwindow.nim");
	button_9c6H9ckeWRn9cApNwfUV21G1Q = Dl_145358_("Click me");
	nimln_(6, "GTKwindow.nim");
	label_9bZ65bbLQJQnH69bwIgidPKQ = Dl_144578_("There have been no clicks yet");
	nimln_(7, "GTKwindow.nim");
	T1_ = (int)0;
	T1_ = gbool_Hrdrv9auPE5AoQelx9arYFnw(NIM_TRUE);
	vbox_kV4agvpNi3He9czgEGcyJFA = Dl_146973_(T1_, ((int) 1));
	nimln_(8, "GTKwindow.nim");
	counter_RzmiH7deZf6p3VhuWYxSHw = ((NI) 0);
	nimln_(14, "GTKwindow.nim");
	nim_init_BI4x6i9c40Tf9b1BitVLexNw();
	nimln_(15, "GTKwindow.nim");
	Dl_144204_(win_KQ7C63XDk33SbVasY9czx6A, "Click me");
	nimln_(16, "GTKwindow.nim");
	T2_ = (tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w*)0;
	T2_ = &vbox_kV4agvpNi3He9czgEGcyJFA->Sup.Sup;
	T3_ = (tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA*)0;
	T3_ = &label_9bZ65bbLQJQnH69bwIgidPKQ->Sup.Sup;
	Dl_143824_(T2_, T3_);
	nimln_(17, "GTKwindow.nim");
	T4_ = (tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w*)0;
	T4_ = &vbox_kV4agvpNi3He9czgEGcyJFA->Sup.Sup;
	T5_ = (tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA*)0;
	T5_ = &button_9c6H9ckeWRn9cApNwfUV21G1Q->Sup.Sup.Sup;
	Dl_143824_(T4_, T5_);
	nimln_(18, "GTKwindow.nim");
	T6_ = (tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w*)0;
	T6_ = &win_KQ7C63XDk33SbVasY9czx6A->Sup.Sup;
	T7_ = (tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA*)0;
	T7_ = &vbox_kV4agvpNi3He9czgEGcyJFA->Sup.Sup.Sup;
	Dl_143824_(T6_, T7_);
	nimln_(19, "GTKwindow.nim");
	T8_ = (tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ*)0;
	T8_ = &win_KQ7C63XDk33SbVasY9czx6A->Sup.Sup.Sup.Sup;
	T9_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg)0;
	T9_ = SIGNAL_FUNC_l4lHLP2AG9blznFImvMxrpA(Dl_151627_);
	T10_ = (unsigned long)0;
	T10_ = signal_connect_bnI6bs39clYFYxM3uaej9c5g(T8_, "delete-event", T9_, NIM_NIL);
	T10_;
	nimln_(20, "GTKwindow.nim");
	T11_ = (tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ*)0;
	T11_ = &button_9c6H9ckeWRn9cApNwfUV21G1Q->Sup.Sup.Sup.Sup;
	T12_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg)0;
	T12_ = SIGNAL_FUNC_l4lHLP2AG9blznFImvMxrpA(clickedMe_1mzfETiHWcbA6Wv5XXfd9ag);
	T13_ = (unsigned long)0;
	T13_ = signal_connect_bnI6bs39clYFYxM3uaej9c5g(T11_, "clicked", T12_, ((void*) (label_9bZ65bbLQJQnH69bwIgidPKQ)));
	T13_;
	nimln_(21, "GTKwindow.nim");
	T14_ = (tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA*)0;
	T14_ = &win_KQ7C63XDk33SbVasY9czx6A->Sup.Sup.Sup;
	Dl_143106_(T14_);
	nimln_(22, "GTKwindow.nim");
	Dl_151619_();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, GTKwindowDatInit000)(void) {
}

