# Auto-generated by "pmgen.py" on 2018-02-02 at 15:57:28.
# Any changes will be overwritten by the next run of "pmgen.py".

# These must be included rather than imported, so the static global variables
# can be evaluated at compile time.
include pymodpkg/private/includes/realmacrodefs

include pymodpkg/private/includes/pyobjecttypedefs

# Modules to be imported by the auto-generated Nim wrappers.
registerNimModuleToImport("..\greeting")

# Modules to be included into this Nim code, so their procs can be exportpy'd.
include ..\greeting
