"""empty message

Revision ID: 217a438e61a2
Revises: 2a2410393c47
Create Date: 2018-09-15 18:57:43.121850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217a438e61a2'
down_revision = '2a2410393c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
