/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\nim-0.17.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim-0.17.2\lib -o c:\webdev\dmlauto\nim\hello\nimcache\nimpy_nimpy.o c:\webdev\dmlauto\nim\hello\nimcache\nimpy_nimpy.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <windows.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg;
typedef struct tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA;
typedef struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q tyTuple_wpFMp8IwxV6MlaM4GANJ0Q;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA;
typedef struct tySequence_QIbr9abHr63pwRbRpKuoFFQ tySequence_QIbr9abHr63pwRbRpKuoFFQ;
typedef struct tySequence_1Ib9a4sxiw4YCYbDTADLEsg tySequence_1Ib9a4sxiw4YCYbDTADLEsg;
typedef struct tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_PyNimObjectcolonObjectType__EzO9cx6qeJIOpzFHShySXxA tyObject_PyNimObjectcolonObjectType__EzO9cx6qeJIOpzFHShySXxA;
typedef struct tyObject_PyObject_HEAD_EXTRA_NKPOYYFwv89cZkXWK0Hqo1w tyObject_PyObject_HEAD_EXTRA_NKPOYYFwv89cZkXWK0Hqo1w;
typedef struct tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA;
typedef struct tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg;
typedef struct NimStringDesc NimStringDesc;
typedef struct tySequence_m5LAl09cqBl9bzwvVnw9aEKrg tySequence_m5LAl09cqBl9bzwvVnw9aEKrg;
typedef struct tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tyObject_PyObjectVarHeadObj_E71nKnjQiXK69aSURXxI79cA tyObject_PyObjectVarHeadObj_E71nKnjQiXK69aSURXxI79cA;
typedef struct tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw;
typedef struct tyObject_PyModuleDef_Base_wqaxd9ak8WwrlmOpLIJe2Jg tyObject_PyModuleDef_Base_wqaxd9ak8WwrlmOpLIJe2Jg;
typedef struct tyObject_PyModuleDef_Slot_VAIk3s5fUTMUrpp6Zb0QBg tyObject_PyModuleDef_Slot_VAIk3s5fUTMUrpp6Zb0QBg;
typedef struct tyObject_Py_buffer_nRhjorz1m8nM8MZqKMfgRA tyObject_Py_buffer_nRhjorz1m8nM8MZqKMfgRA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef N_CDECL_PTR(int, tyProc_HsCFdEWlCdoq2wOkZ2URfg) (void* f, NCSTRING fmt, ...);
typedef N_CDECL_PTR(void*, tyProc_SsjMo29bx9bP5kwe2xgM3Scg) (NCSTRING f, ...);
typedef N_CDECL_PTR(size_t, tyProc_ocClJDlcZaqgYpi2lF669cA) (void* f);
typedef N_CDECL_PTR(void*, tyProc_xKuFDtrrlpEd0ARlODf8xA) (void* f, size_t i);
typedef N_CDECL_PTR(int, tyProc_JOheI6S14zehX7QFjD9b9arA) (tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* f);
typedef N_CDECL_PTR(void*, tyProc_gaBVY12IBlwVY2fikmPgHQ) (tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* f, void* a, void* b);
typedef N_CDECL_PTR(int, tyProc_T08W9bgbY4bOv2q64h6irpw) (void* m, NCSTRING n, void* o);
typedef N_CDECL_PTR(void*, tyProc_E3yjbFti2J9bkUN9ckhwcXeg) (size_t size);
typedef N_CDECL_PTR(int, tyProc_nuVTH6REO8jfyM9augS15pw) (void* l, size_t index, void* i);
typedef N_CDECL_PTR(NI64, tyProc_mIlNZ9aGaphVJCyIIofK8mg) (void* l);
typedef N_CDECL_PTR(double, tyProc_2su9b9chqHYibM7sMkbSaSkA) (void* l);
typedef N_CDECL_PTR(void*, tyProc_RKlUmjvtmKGnc01PbvZaRQ) (long v);
struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q {
NF Field0;
NF Field1;
};
typedef N_CDECL_PTR(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, tyProc_pp2rHJik8czES8sAFDwvQQ) (void* op);
struct tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg {
void* module;
tyProc_SsjMo29bx9bP5kwe2xgM3Scg Py_BuildValue;
tyProc_ocClJDlcZaqgYpi2lF669cA PyTuple_Size;
tyProc_xKuFDtrrlpEd0ARlODf8xA PyTuple_GetItem;
void* Py_None;
tyProc_JOheI6S14zehX7QFjD9b9arA PyType_Ready;
tyProc_gaBVY12IBlwVY2fikmPgHQ PyType_GenericNew;
tyProc_T08W9bgbY4bOv2q64h6irpw PyModule_AddObject;
tyProc_E3yjbFti2J9bkUN9ckhwcXeg PyList_New;
tyProc_ocClJDlcZaqgYpi2lF669cA PyList_Size;
tyProc_xKuFDtrrlpEd0ARlODf8xA PyList_GetItem;
tyProc_nuVTH6REO8jfyM9augS15pw PyList_SetItem;
tyProc_mIlNZ9aGaphVJCyIIofK8mg PyLong_AsLongLong;
tyProc_2su9b9chqHYibM7sMkbSaSkA PyFloat_AsDouble;
tyProc_RKlUmjvtmKGnc01PbvZaRQ PyBool_FromLong;
tyProc_pp2rHJik8czES8sAFDwvQQ PyComplex_AsCComplex;
tyProc_2su9b9chqHYibM7sMkbSaSkA PyComplex_RealAsDouble;
tyProc_2su9b9chqHYibM7sMkbSaSkA PyComplex_ImagAsDouble;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef N_CDECL_PTR(void*, tyProc_VQ1ysQk017myXMGb79cPTVw) (void* s, void* a);
struct tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA {
NCSTRING name;
NCSTRING doc;
tySequence_QIbr9abHr63pwRbRpKuoFFQ* methods;
tySequence_1Ib9a4sxiw4YCYbDTADLEsg* types;
};
struct tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA {
NCSTRING ml_name;
tyProc_VQ1ysQk017myXMGb79cPTVw ml_meth;
int ml_flags;
NCSTRING ml_doc;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_PyObject_HEAD_EXTRA_NKPOYYFwv89cZkXWK0Hqo1w {
void* ob_next;
void* ob_prev;
};
struct tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA {
size_t ob_refcnt;
void* ob_type;
};
struct tyObject_PyNimObjectcolonObjectType__EzO9cx6qeJIOpzFHShySXxA {
TNimType* m_type;
tyObject_PyObject_HEAD_EXTRA_NKPOYYFwv89cZkXWK0Hqo1w py_extra_dont_use;
tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA py_object;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg {
tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* module;
NCSTRING name;
NCSTRING doc;
NimStringDesc* fullName;
tyProc_gaBVY12IBlwVY2fikmPgHQ newFunc;
tySequence_QIbr9abHr63pwRbRpKuoFFQ* methods;
tySequence_m5LAl09cqBl9bzwvVnw9aEKrg* members;
NI origSize;
};
struct tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw {
NCSTRING name;
int typ;
size_t offset;
int flags;
NCSTRING doc;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
CRITICAL_SECTION lock;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw toDispose;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_PyObjectVarHeadObj_E71nKnjQiXK69aSURXxI79cA {
  tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA Sup;
size_t ob_size;
};
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* o);
typedef N_CDECL_PTR(int, tyProc_8H9bL9crYRIHExJYg9bWhYvMQ) (void* o, FILE* f, int c);
typedef N_CDECL_PTR(void*, tyProc_YezmFzxOOyM9cb11Eoq1Elg) (void* o, NCSTRING a);
typedef N_CDECL_PTR(void*, tyProc_jvPpjMAkI9bwM1B9apOphnlA) (void* o);
typedef N_CDECL_PTR(int, tyProc_7LMjBc4zOHVIsNdulNv7QQ) (void* o, void* a, void* at);
typedef N_CDECL_PTR(void*, tyProc_k4RBH32nrpDxtGF9acg45zw) (void* a, void* b, int c);
typedef N_CDECL_PTR(void*, tyProc_uQWqJp3WAx8fOY1h9aCwjIg) (void* a, void* b, void* c);
typedef N_CDECL_PTR(void*, tyProc_QuHKuhBxxkyDbOnFG79bCMA) (tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* typ, size_t sz);
struct tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA {
  tyObject_PyObjectVarHeadObj_E71nKnjQiXK69aSURXxI79cA Sup;
NCSTRING tp_name;
size_t tp_basicsize;
size_t tp_itemsize;
tyProc_32w2ZypAyMWuajvi2Jt79cg tp_dealloc;
tyProc_8H9bL9crYRIHExJYg9bWhYvMQ tp_print;
tyProc_YezmFzxOOyM9cb11Eoq1Elg tp_getattr;
tyProc_T08W9bgbY4bOv2q64h6irpw tp_setattr;
void* tp_as_async;
tyProc_jvPpjMAkI9bwM1B9apOphnlA tp_repr;
void* tp_as_number;
void* tp_as_sequence;
void* tp_as_mapping;
void* tp_hash;
void* tp_call;
tyProc_jvPpjMAkI9bwM1B9apOphnlA tp_str;
tyProc_VQ1ysQk017myXMGb79cPTVw tp_getattro;
tyProc_7LMjBc4zOHVIsNdulNv7QQ tp_setattro;
void* tp_as_buffer;
unsigned long tp_flags;
NCSTRING tp_doc;
void* tp_traverse;
void* tp_clear;
tyProc_k4RBH32nrpDxtGF9acg45zw tp_richcompare;
size_t tp_weaklistoffset;
tyProc_jvPpjMAkI9bwM1B9apOphnlA tp_iter;
tyProc_jvPpjMAkI9bwM1B9apOphnlA tp_iternext;
tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA* tp_methods;
tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw* tp_members;
void* tp_getset;
tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* tp_base;
void* tp_dict;
tyProc_uQWqJp3WAx8fOY1h9aCwjIg tp_descr_get;
tyProc_7LMjBc4zOHVIsNdulNv7QQ tp_descr_set;
size_t tp_dictoffset;
tyProc_7LMjBc4zOHVIsNdulNv7QQ tp_init;
tyProc_QuHKuhBxxkyDbOnFG79bCMA tp_alloc;
tyProc_gaBVY12IBlwVY2fikmPgHQ tp_new;
tyProc_32w2ZypAyMWuajvi2Jt79cg tp_free;
void* tp_is_gc;
tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA* tp_bases;
void* tp_mro;
void* tp_cache;
tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA* tp_subclasses;
tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA* tp_weaklist;
tyProc_32w2ZypAyMWuajvi2Jt79cg tp_del;
unsigned int tp_version_tag;
tyProc_32w2ZypAyMWuajvi2Jt79cg tp_finalize;
};
typedef N_CDECL_PTR(void*, tyProc_7NjwwXgjqHVJzOMXYXleoA) (NCSTRING name, tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA* methods, NCSTRING doc, void* self, int apiver);
typedef N_CDECL_PTR(void*, tyProc_NzboHqZVJcbdtVGYrOosXQ) (void);
struct tyObject_PyModuleDef_Base_wqaxd9ak8WwrlmOpLIJe2Jg {
tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA ob_base;
tyProc_NzboHqZVJcbdtVGYrOosXQ m_init;
size_t m_index;
void* m_copy;
};
struct tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw {
tyObject_PyModuleDef_Base_wqaxd9ak8WwrlmOpLIJe2Jg m_base;
NCSTRING m_name;
NCSTRING m_doc;
size_t m_size;
tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA* m_methods;
tyObject_PyModuleDef_Slot_VAIk3s5fUTMUrpp6Zb0QBg* m_slots;
void* m_traverse;
void* m_clear;
void* m_free;
};
typedef N_CDECL_PTR(void*, tyProc_BEMKLd49c5qNHqmldA6aVaw) (void* m, int apiver);
typedef size_t tyArray_5yb7pTez09b829cCwHJP2deg[2];
struct tyObject_Py_buffer_nRhjorz1m8nM8MZqKMfgRA {
void* buf;
void* obj;
size_t len;
size_t itemsize;
int readonly;
int ndim;
NCSTRING format;
size_t* shape;
size_t* strides;
size_t* suboffsets;
tyArray_5yb7pTez09b829cCwHJP2deg smalltable;
void* internal;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef void* tyArray_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* next;
NI dataLen;
tyArray_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
struct tyObject_PyModuleDef_Slot_VAIk3s5fUTMUrpp6Zb0QBg {
int slot;
void* value;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_QIbr9abHr63pwRbRpKuoFFQ {
  TGenericSeq Sup;
  tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA data[SEQ_DECL_SIZE];
};
struct tySequence_1Ib9a4sxiw4YCYbDTADLEsg {
  TGenericSeq Sup;
  tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg data[SEQ_DECL_SIZE];
};
struct tySequence_m5LAl09cqBl9bzwvVnw9aEKrg {
  TGenericSeq Sup;
  tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tyRef_q7GVR3hKxnZZLg2r6rGifQ)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_LoH0foxqckmmftA2y2Dp9aw_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void, addMethod_keJjYiB0Fqpj61YcmmSEgw)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m, NCSTRING name, NCSTRING doc, tyProc_VQ1ysQk017myXMGb79cPTVw f);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void*, newNimObjToPyObj_9augpGiQCXbb9cMk0Ak3OUgQ)(tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* typ, tyObject_PyNimObjectcolonObjectType__EzO9cx6qeJIOpzFHShySXxA* o);
N_NIMCALL(void, nimGCref)(void* p);
N_NIMCALL(void, initPythonModuleDesc_FOOWv9a9c0A9buPW1MnJxC3qA)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m, NCSTRING name, NCSTRING doc);
static N_NIMCALL(void, Marker_tySequence_QIbr9abHr63pwRbRpKuoFFQ)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_NIMCALL(void, Marker_tySequence_m5LAl09cqBl9bzwvVnw9aEKrg)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_1Ib9a4sxiw4YCYbDTADLEsg)(void* p, NI op);
N_NIMCALL(void*, pyAlloc_PTU6OBy9bioXSlNFdi1q2gg)(NI sz);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOCONV(void*, alloc0_sVm4rDImKK2ZDdylByayiA_2)(NI size);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA*, to_9a9ct7JZaqqlUcH6XHu4T9cngnimpy)(void* p);
static N_INLINE(void, incRef_aGFJKMPOa8pYliHzRN2VPAnimpy)(void* p);
N_NIMCALL(void, initCommon_QOPr6RYgxP9c8n2lZVbiDwA)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newObjRC1)(TNimType* typ, NI size);
N_NIMCALL(void*, loadLib_Z1cxp9aB153T5qRduJpPCFA)(void);
N_NIMCALL(void*, symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2)(void* lib, NCSTRING name);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(tyObject_PyNimObjectcolonObjectType__EzO9cx6qeJIOpzFHShySXxA*, toNim_LIdCSVTxVJM5HLcUOCuUGwnimpy)(void* p);
N_CDECL(void, destructNimObj_gP9bSgYtp25aud4g9as1b5JQ)(void* o);
N_NIMCALL(void, nimGCunref)(void* p);
N_CDECL(void, freeNimObj_BSyN3KaI27bZetfSWWb86w)(void* p);
N_NIMCALL(void, initModuleTypes_aYiLzwwt7ZRNmOisahibSA)(void* p, tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m);
static N_INLINE(tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA*, to_39cbYCg6zPfn9a9chN0oM7FHgnimpy)(void* p);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, initModule2_czV3Hp3EXVZK9cnxiVizA9cwnimpy)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m);
static N_INLINE(void, initPyModule_nPSQLKdnxTDvCUB31oENYQnimpy)(tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw* p, tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m);
static N_INLINE(tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw*, to_RvoceX4eN8TgFBHbu8LOvwnimpy)(void* p);
static N_INLINE(void*, initModule3_okp5JtSm53wnPxjJK0sxNAnimpy)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m);
N_NIMCALL(void, initModuleAux2_QOPr6RYgxP9c8n2lZVbiDwA_2)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m);
N_NIMCALL(void, NimMain)(void);
N_NIMCALL(void*, initModuleAux3_fiCOhQD5a4JY3kdtM19cCuQ)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m);
N_NIMCALL(NimStringDesc*, toString_slL8EbtkTixT9aehlJ9cV9bGQ)(tyObject_Py_buffer_nRhjorz1m8nM8MZqKMfgRA* b);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(void, pyObjToNim_yiwC7N9bqau80g2TsV2jwNg)(void* o, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* s);
static N_INLINE(void*, strToPyObject_5KC9cg9bQBGcEpbowAmucpaQnimpy)(NimStringDesc* s);
tyProc_HsCFdEWlCdoq2wOkZ2URfg PyArg_ParseTuple_zzMUabcLwhGju9bqqFfrCGw;
tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg* pyLib_bgKRHU9cKqO7op9cXO6AxcTw;
TNimType NTI_ao1O59bN9asAtLBM32qv9bIJg_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
TNimType NTI_SsjMo29bx9bP5kwe2xgM3Scg_;
TNimType NTI_ocClJDlcZaqgYpi2lF669cA_;
TNimType NTI_xKuFDtrrlpEd0ARlODf8xA_;
TNimType NTI_JOheI6S14zehX7QFjD9b9arA_;
TNimType NTI_gaBVY12IBlwVY2fikmPgHQ_;
TNimType NTI_T08W9bgbY4bOv2q64h6irpw_;
TNimType NTI_E3yjbFti2J9bkUN9ckhwcXeg_;
TNimType NTI_nuVTH6REO8jfyM9augS15pw_;
TNimType NTI_mIlNZ9aGaphVJCyIIofK8mg_;
TNimType NTI_2su9b9chqHYibM7sMkbSaSkA_;
TNimType NTI_RKlUmjvtmKGnc01PbvZaRQ_;
TNimType NTI_pp2rHJik8czES8sAFDwvQQ_;
TNimType NTI_q7GVR3hKxnZZLg2r6rGifQ_;
extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_33Z7fkQhmIaDXevopp3LQA_;
extern TNimType NTI_S9agCYBinaYZnGWcjTdxclg_;
TNimType NTI_VQ1ysQk017myXMGb79cPTVw_;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA_;
TNimType NTI_QIbr9abHr63pwRbRpKuoFFQ_;
TNimType NTI_BKCcJxogshNojOoN23Qfbg_;
TNimType NTI_gBC8z6Ez5xj3dXoP0ylCRA_;
TNimType NTI_v2GijgCrTru9brL7cjgOkag_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_2pF0VEkKjttowUMYhsxfyw_;
TNimType NTI_Q4mRjQ149bG48TfHO9bTZVmA_;
TNimType NTI_m5LAl09cqBl9bzwvVnw9aEKrg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_1Ib9a4sxiw4YCYbDTADLEsg_;
NIM_BOOL traceRefs_tlXpUlkM769cFvi4ZetY15A;
extern NIM_THREADVAR tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_oUKtBcKRdK6usj8RWrlp6A_;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_10, "Symbol not loaded: _Py_BuildValue_SizeT", 39);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_11, "Symbol not loaded: PyTuple_Size", 31);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_12, "Symbol not loaded: PyTuple_GetItem", 34);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_13, "Symbol not loaded: PyArg_ParseTuple", 35);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_14, "Symbol not loaded: _Py_NoneStruct", 33);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_15, "Symbol not loaded: PyType_Ready", 31);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_16, "Symbol not loaded: PyType_GenericNew", 36);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_17, "Symbol not loaded: PyModule_AddObject", 37);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_18, "Symbol not loaded: PyList_New", 29);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_19, "Symbol not loaded: PyList_Size", 30);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_20, "Symbol not loaded: PyList_GetItem", 33);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_21, "Symbol not loaded: PyList_SetItem", 33);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_22, "Symbol not loaded: PyLong_AsLongLong", 36);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_23, "Symbol not loaded: PyFloat_AsDouble", 35);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_24, "Symbol not loaded: PyBool_FromLong", 34);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_25, "Symbol not loaded: PyComplex_AsCComplex", 39);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_26, "Symbol not loaded: PyComplex_RealAsDouble", 41);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_27, "Symbol not loaded: PyComplex_ImagAsDouble", 41);
STRING_LITERAL(TM_LoH0foxqckmmftA2y2Dp9aw_29, "Internal pynim error. Free called on Nim object.", 48);
static N_NIMCALL(void, Marker_tyRef_q7GVR3hKxnZZLg2r6rGifQ)(void* p, NI op) {
	tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg* a;
	a = (tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg*)p;
}
static N_NIMCALL(void, TM_LoH0foxqckmmftA2y2Dp9aw_3)(void) {
	nimGCvisit((void*)pyLib_bgKRHU9cKqO7op9cXO6AxcTw, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, addMethod_keJjYiB0Fqpj61YcmmSEgw)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m, NCSTRING name, NCSTRING doc, tyProc_VQ1ysQk017myXMGb79cPTVw f) {
	tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA T1_;
	NI T2_;
	nimfr_("addMethod", "nimpy.nim");
	nimln_(427, "nimpy.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.ml_name = name;
	T1_.ml_meth = f;
	T1_.ml_flags = ((int) 1);
	T1_.ml_doc = doc;
	(*m).methods = (tySequence_QIbr9abHr63pwRbRpKuoFFQ*) incrSeqV2(&((*m).methods)->Sup, sizeof(tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA));
	T2_ = (*m).methods->Sup.len++;
	(*m).methods->data[T2_] = T1_;
	popFrame();
}

N_NIMCALL(void*, newNimObjToPyObj_9augpGiQCXbb9cMk0Ak3OUgQ)(tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* typ, tyObject_PyNimObjectcolonObjectType__EzO9cx6qeJIOpzFHShySXxA* o) {
	void* result;
	nimfr_("newNimObjToPyObj", "nimpy.nim");
	result = (void*)0;
	nimln_(431, "nimpy.nim");
	nimGCref(o);
	nimln_(432, "nimpy.nim");
	result = ((void*) ((&(*o).py_object)));
	nimln_(433, "nimpy.nim");
	(*o).py_object.ob_type = ((void*) (typ));
	nimln_(434, "nimpy.nim");
	(*o).py_object.ob_refcnt = ((NI) 1);
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_QIbr9abHr63pwRbRpKuoFFQ)(void* p, NI op) {
	tySequence_QIbr9abHr63pwRbRpKuoFFQ* a;
	NI T1_;
	a = (tySequence_QIbr9abHr63pwRbRpKuoFFQ*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tySequence_m5LAl09cqBl9bzwvVnw9aEKrg)(void* p, NI op) {
	tySequence_m5LAl09cqBl9bzwvVnw9aEKrg* a;
	NI T1_;
	a = (tySequence_m5LAl09cqBl9bzwvVnw9aEKrg*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tySequence_1Ib9a4sxiw4YCYbDTADLEsg)(void* p, NI op) {
	tySequence_1Ib9a4sxiw4YCYbDTADLEsg* a;
	NI T1_;
	a = (tySequence_1Ib9a4sxiw4YCYbDTADLEsg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].fullName, op);
	nimGCvisit((void*)a->data[T1_].methods, op);
	nimGCvisit((void*)a->data[T1_].members, op);
	}
}

N_NIMCALL(void, initPythonModuleDesc_FOOWv9a9c0A9buPW1MnJxC3qA)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m, NCSTRING name, NCSTRING doc) {
	nimfr_("initPythonModuleDesc", "nimpy.nim");
	nimln_(440, "nimpy.nim");
	(*m).name = name;
	nimln_(441, "nimpy.nim");
	(*m).doc = doc;
	nimln_(442, "nimpy.nim");
	unsureAsgnRef((void**) (&(*m).methods), (tySequence_QIbr9abHr63pwRbRpKuoFFQ*) newSeq((&NTI_QIbr9abHr63pwRbRpKuoFFQ_), 0));
	nimln_(443, "nimpy.nim");
	unsureAsgnRef((void**) (&(*m).types), (tySequence_1Ib9a4sxiw4YCYbDTADLEsg*) newSeq((&NTI_1Ib9a4sxiw4YCYbDTADLEsg_), 0));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void*, pyAlloc_PTU6OBy9bioXSlNFdi1q2gg)(NI sz) {
	void* result;
	NI sz_2;
	void* T5_;
	nimfr_("pyAlloc", "nimpy.nim");
	result = (void*)0;
	nimln_(448, "nimpy.nim");
	sz_2 = sz;
	nimln_(449, "nimpy.nim");
	{
		NI TM_LoH0foxqckmmftA2y2Dp9aw_8;
		if (!traceRefs_tlXpUlkM769cFvi4ZetY15A) goto LA3_;
		nimln_(450, "nimpy.nim");
		TM_LoH0foxqckmmftA2y2Dp9aw_8 = addInt(sz_2, ((NI)sizeof(tyObject_PyObject_HEAD_EXTRA_NKPOYYFwv89cZkXWK0Hqo1w)));
		sz_2 = (NI)(TM_LoH0foxqckmmftA2y2Dp9aw_8);
	}
	LA3_: ;
	nimln_(451, "nimpy.nim");
	T5_ = (void*)0;
	T5_ = alloc0_sVm4rDImKK2ZDdylByayiA_2(((NI)chckRange(sz_2, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	result = ((void*) (T5_));
	popFrame();
	return result;
}

static N_INLINE(tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA*, to_9a9ct7JZaqqlUcH6XHu4T9cngnimpy)(void* p) {
	tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA* result;
	nimfr_("to", "nimpy.nim");
	result = (tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA*)0;
	nimln_(454, "nimpy.nim");
	{
		if (!traceRefs_tlXpUlkM769cFvi4ZetY15A) goto LA3_;
		nimln_(455, "nimpy.nim");
		result = ((tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA*) ((NU)((NU64)(((NU) (p))) + (NU64)(((NU) (((NI)sizeof(tyObject_PyObject_HEAD_EXTRA_NKPOYYFwv89cZkXWK0Hqo1w))))))));
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(457, "nimpy.nim");
		result = ((tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA*) (p));
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(void, incRef_aGFJKMPOa8pYliHzRN2VPAnimpy)(void* p) {
	tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA* T1_;
	size_t TM_LoH0foxqckmmftA2y2Dp9aw_9;
	nimfr_("incRef", "nimpy.nim");
	nimln_(463, "nimpy.nim");
	T1_ = (tyObject_PyObjectObj_AED2HSRFC6rdxpw8O4exqA*)0;
	T1_ = to_9a9ct7JZaqqlUcH6XHu4T9cngnimpy(p);
	TM_LoH0foxqckmmftA2y2Dp9aw_9 = addInt((*T1_).ob_refcnt, ((NI) 1));
	(*T1_).ob_refcnt = (size_t)(TM_LoH0foxqckmmftA2y2Dp9aw_9);
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(269, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(378, "system.nim");
		nimln_(269, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(270, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(378, "system.nim");
		nimln_(270, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, initCommon_QOPr6RYgxP9c8n2lZVbiDwA)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m) {
	tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA T128_;
	NI T129_;
	nimfr_("initCommon", "nimpy.nim");
	nimln_(466, "nimpy.nim");
	{
		void* T16_;
		void* T22_;
		void* T28_;
		void* T34_;
		void* T40_;
		void* T46_;
		void* T52_;
		void* T58_;
		void* T64_;
		void* T70_;
		void* T76_;
		void* T82_;
		void* T88_;
		void* T94_;
		void* T100_;
		void* T106_;
		if (!(pyLib_bgKRHU9cKqO7op9cXO6AxcTw == 0)) goto LA3_;
		nimln_(467, "nimpy.nim");
		if (pyLib_bgKRHU9cKqO7op9cXO6AxcTw) { nimGCunrefNoCycle(pyLib_bgKRHU9cKqO7op9cXO6AxcTw); pyLib_bgKRHU9cKqO7op9cXO6AxcTw = NIM_NIL; }
		pyLib_bgKRHU9cKqO7op9cXO6AxcTw = (tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg*) newObjRC1((&NTI_q7GVR3hKxnZZLg2r6rGifQ_), sizeof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg));
		nimln_(468, "nimpy.nim");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module = loadLib_Z1cxp9aB153T5qRduJpPCFA();
		nimln_(470, "nimpy.nim");
		{
			NIM_BOOL T7_;
			NIM_BOOL T8_;
			void* T9_;
			void* T11_;
			void* T13_;
			nimln_(471, "nimpy.nim");
			nimln_(470, "nimpy.nim");
			T7_ = (NIM_BOOL)0;
			T8_ = (NIM_BOOL)0;
			T9_ = (void*)0;
			T9_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyModule_Create2");
			T8_ = (T9_ == 0);
			if (T8_) goto LA10_;
			nimln_(471, "nimpy.nim");
			T11_ = (void*)0;
			T11_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "Py_InitModule4_64");
			T8_ = (T11_ == 0);
			LA10_: ;
			T7_ = T8_;
			if (T7_) goto LA12_;
			nimln_(472, "nimpy.nim");
			T13_ = (void*)0;
			T13_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "Py_InitModule4");
			T7_ = (T13_ == 0);
			LA12_: ;
			if (!!(T7_)) goto LA14_;
			nimln_(473, "nimpy.nim");
			traceRefs_tlXpUlkM769cFvi4ZetY15A = NIM_TRUE;
		}
		LA14_: ;
		nimln_(476, "nimpy.nim");
		T16_ = (void*)0;
		T16_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "_Py_BuildValue_SizeT");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).Py_BuildValue = ((tyProc_SsjMo29bx9bP5kwe2xgM3Scg) (T16_));
		nimln_(480, "nimpy.nim");
		{
			Exception* e;
			NimStringDesc* T21_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).Py_BuildValue == 0)) goto LA19_;
			e = (Exception*)0;
			nimln_(2702, "system.nim");
			e = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T21_ = (NimStringDesc*)0;
			T21_ = (*e).message; (*e).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_10));
			if (T21_) nimGCunrefNoCycle(T21_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e, "Exception");
		}
		LA19_: ;
		nimln_(476, "nimpy.nim");
		T22_ = (void*)0;
		T22_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyTuple_Size");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyTuple_Size = ((tyProc_ocClJDlcZaqgYpi2lF669cA) (T22_));
		nimln_(481, "nimpy.nim");
		{
			Exception* e_2;
			NimStringDesc* T27_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyTuple_Size == 0)) goto LA25_;
			e_2 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_2 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_2).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T27_ = (NimStringDesc*)0;
			T27_ = (*e_2).message; (*e_2).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_11));
			if (T27_) nimGCunrefNoCycle(T27_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_2).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_2, "Exception");
		}
		LA25_: ;
		nimln_(476, "nimpy.nim");
		T28_ = (void*)0;
		T28_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyTuple_GetItem");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyTuple_GetItem = ((tyProc_xKuFDtrrlpEd0ARlODf8xA) (T28_));
		nimln_(482, "nimpy.nim");
		{
			Exception* e_3;
			NimStringDesc* T33_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyTuple_GetItem == 0)) goto LA31_;
			e_3 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_3 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_3).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T33_ = (NimStringDesc*)0;
			T33_ = (*e_3).message; (*e_3).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_12));
			if (T33_) nimGCunrefNoCycle(T33_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_3).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_3, "Exception");
		}
		LA31_: ;
		nimln_(483, "nimpy.nim");
		T34_ = (void*)0;
		T34_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "_PyArg_ParseTuple_SizeT");
		PyArg_ParseTuple_zzMUabcLwhGju9bqqFfrCGw = ((tyProc_HsCFdEWlCdoq2wOkZ2URfg) (T34_));
		nimln_(484, "nimpy.nim");
		{
			Exception* e_4;
			NimStringDesc* T39_;
			if (!(PyArg_ParseTuple_zzMUabcLwhGju9bqqFfrCGw == 0)) goto LA37_;
			e_4 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_4 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_4).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(485, "nimpy.nim");
			T39_ = (NimStringDesc*)0;
			T39_ = (*e_4).message; (*e_4).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_13));
			if (T39_) nimGCunrefNoCycle(T39_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_4).parent), NIM_NIL);
			nimln_(485, "nimpy.nim");
			raiseException((Exception*)e_4, "Exception");
		}
		LA37_: ;
		nimln_(476, "nimpy.nim");
		T40_ = (void*)0;
		T40_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "_Py_NoneStruct");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).Py_None = ((void*) (T40_));
		nimln_(487, "nimpy.nim");
		{
			Exception* e_5;
			NimStringDesc* T45_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).Py_None == 0)) goto LA43_;
			e_5 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_5 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_5).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T45_ = (NimStringDesc*)0;
			T45_ = (*e_5).message; (*e_5).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_14));
			if (T45_) nimGCunrefNoCycle(T45_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_5).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_5, "Exception");
		}
		LA43_: ;
		nimln_(476, "nimpy.nim");
		T46_ = (void*)0;
		T46_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyType_Ready");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyType_Ready = ((tyProc_JOheI6S14zehX7QFjD9b9arA) (T46_));
		nimln_(488, "nimpy.nim");
		{
			Exception* e_6;
			NimStringDesc* T51_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyType_Ready == 0)) goto LA49_;
			e_6 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_6 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_6).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T51_ = (NimStringDesc*)0;
			T51_ = (*e_6).message; (*e_6).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_15));
			if (T51_) nimGCunrefNoCycle(T51_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_6).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_6, "Exception");
		}
		LA49_: ;
		nimln_(476, "nimpy.nim");
		T52_ = (void*)0;
		T52_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyType_GenericNew");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyType_GenericNew = ((tyProc_gaBVY12IBlwVY2fikmPgHQ) (T52_));
		nimln_(489, "nimpy.nim");
		{
			Exception* e_7;
			NimStringDesc* T57_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyType_GenericNew == 0)) goto LA55_;
			e_7 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_7 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_7).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T57_ = (NimStringDesc*)0;
			T57_ = (*e_7).message; (*e_7).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_16));
			if (T57_) nimGCunrefNoCycle(T57_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_7).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_7, "Exception");
		}
		LA55_: ;
		nimln_(476, "nimpy.nim");
		T58_ = (void*)0;
		T58_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyModule_AddObject");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyModule_AddObject = ((tyProc_T08W9bgbY4bOv2q64h6irpw) (T58_));
		nimln_(490, "nimpy.nim");
		{
			Exception* e_8;
			NimStringDesc* T63_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyModule_AddObject == 0)) goto LA61_;
			e_8 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_8 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_8).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T63_ = (NimStringDesc*)0;
			T63_ = (*e_8).message; (*e_8).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_17));
			if (T63_) nimGCunrefNoCycle(T63_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_8).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_8, "Exception");
		}
		LA61_: ;
		nimln_(476, "nimpy.nim");
		T64_ = (void*)0;
		T64_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyList_New");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyList_New = ((tyProc_E3yjbFti2J9bkUN9ckhwcXeg) (T64_));
		nimln_(492, "nimpy.nim");
		{
			Exception* e_9;
			NimStringDesc* T69_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyList_New == 0)) goto LA67_;
			e_9 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_9 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_9).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T69_ = (NimStringDesc*)0;
			T69_ = (*e_9).message; (*e_9).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_18));
			if (T69_) nimGCunrefNoCycle(T69_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_9).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_9, "Exception");
		}
		LA67_: ;
		nimln_(476, "nimpy.nim");
		T70_ = (void*)0;
		T70_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyList_Size");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyList_Size = ((tyProc_ocClJDlcZaqgYpi2lF669cA) (T70_));
		nimln_(493, "nimpy.nim");
		{
			Exception* e_10;
			NimStringDesc* T75_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyList_Size == 0)) goto LA73_;
			e_10 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_10 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_10).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T75_ = (NimStringDesc*)0;
			T75_ = (*e_10).message; (*e_10).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_19));
			if (T75_) nimGCunrefNoCycle(T75_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_10).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_10, "Exception");
		}
		LA73_: ;
		nimln_(476, "nimpy.nim");
		T76_ = (void*)0;
		T76_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyList_GetItem");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyList_GetItem = ((tyProc_xKuFDtrrlpEd0ARlODf8xA) (T76_));
		nimln_(494, "nimpy.nim");
		{
			Exception* e_11;
			NimStringDesc* T81_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyList_GetItem == 0)) goto LA79_;
			e_11 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_11 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_11).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T81_ = (NimStringDesc*)0;
			T81_ = (*e_11).message; (*e_11).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_20));
			if (T81_) nimGCunrefNoCycle(T81_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_11).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_11, "Exception");
		}
		LA79_: ;
		nimln_(476, "nimpy.nim");
		T82_ = (void*)0;
		T82_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyList_SetItem");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyList_SetItem = ((tyProc_nuVTH6REO8jfyM9augS15pw) (T82_));
		nimln_(495, "nimpy.nim");
		{
			Exception* e_12;
			NimStringDesc* T87_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyList_SetItem == 0)) goto LA85_;
			e_12 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_12 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_12).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T87_ = (NimStringDesc*)0;
			T87_ = (*e_12).message; (*e_12).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_21));
			if (T87_) nimGCunrefNoCycle(T87_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_12).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_12, "Exception");
		}
		LA85_: ;
		nimln_(476, "nimpy.nim");
		T88_ = (void*)0;
		T88_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyLong_AsLongLong");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyLong_AsLongLong = ((tyProc_mIlNZ9aGaphVJCyIIofK8mg) (T88_));
		nimln_(496, "nimpy.nim");
		{
			Exception* e_13;
			NimStringDesc* T93_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyLong_AsLongLong == 0)) goto LA91_;
			e_13 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_13 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_13).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T93_ = (NimStringDesc*)0;
			T93_ = (*e_13).message; (*e_13).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_22));
			if (T93_) nimGCunrefNoCycle(T93_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_13).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_13, "Exception");
		}
		LA91_: ;
		nimln_(476, "nimpy.nim");
		T94_ = (void*)0;
		T94_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyFloat_AsDouble");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyFloat_AsDouble = ((tyProc_2su9b9chqHYibM7sMkbSaSkA) (T94_));
		nimln_(497, "nimpy.nim");
		{
			Exception* e_14;
			NimStringDesc* T99_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyFloat_AsDouble == 0)) goto LA97_;
			e_14 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_14 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_14).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T99_ = (NimStringDesc*)0;
			T99_ = (*e_14).message; (*e_14).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_23));
			if (T99_) nimGCunrefNoCycle(T99_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_14).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_14, "Exception");
		}
		LA97_: ;
		nimln_(476, "nimpy.nim");
		T100_ = (void*)0;
		T100_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyBool_FromLong");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyBool_FromLong = ((tyProc_RKlUmjvtmKGnc01PbvZaRQ) (T100_));
		nimln_(498, "nimpy.nim");
		{
			Exception* e_15;
			NimStringDesc* T105_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyBool_FromLong == 0)) goto LA103_;
			e_15 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_15 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_15).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T105_ = (NimStringDesc*)0;
			T105_ = (*e_15).message; (*e_15).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_24));
			if (T105_) nimGCunrefNoCycle(T105_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_15).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_15, "Exception");
		}
		LA103_: ;
		nimln_(476, "nimpy.nim");
		T106_ = (void*)0;
		T106_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyComplex_AsCComplex");
		(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyComplex_AsCComplex = ((tyProc_pp2rHJik8czES8sAFDwvQQ) (T106_));
		nimln_(500, "nimpy.nim");
		{
			Exception* e_16;
			NimStringDesc* T111_;
			nimln_(477, "nimpy.nim");
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyComplex_AsCComplex == 0)) goto LA109_;
			e_16 = (Exception*)0;
			nimln_(2702, "system.nim");
			e_16 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e_16).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(478, "nimpy.nim");
			T111_ = (NimStringDesc*)0;
			T111_ = (*e_16).message; (*e_16).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_25));
			if (T111_) nimGCunrefNoCycle(T111_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_16).parent), NIM_NIL);
			nimln_(478, "nimpy.nim");
			raiseException((Exception*)e_16, "Exception");
		}
		LA109_: ;
		nimln_(501, "nimpy.nim");
		{
			void* T116_;
			void* T122_;
			if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyComplex_AsCComplex == 0)) goto LA114_;
			nimln_(476, "nimpy.nim");
			T116_ = (void*)0;
			T116_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyComplex_RealAsDouble");
			(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyComplex_RealAsDouble = ((tyProc_2su9b9chqHYibM7sMkbSaSkA) (T116_));
			nimln_(502, "nimpy.nim");
			{
				Exception* e_17;
				NimStringDesc* T121_;
				nimln_(477, "nimpy.nim");
				if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyComplex_RealAsDouble == 0)) goto LA119_;
				e_17 = (Exception*)0;
				nimln_(2702, "system.nim");
				e_17 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
				(*e_17).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
				nimln_(478, "nimpy.nim");
				T121_ = (NimStringDesc*)0;
				T121_ = (*e_17).message; (*e_17).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_26));
				if (T121_) nimGCunrefNoCycle(T121_);
				nimln_(2697, "system.nim");
				asgnRef((void**) (&(*e_17).parent), NIM_NIL);
				nimln_(478, "nimpy.nim");
				raiseException((Exception*)e_17, "Exception");
			}
			LA119_: ;
			nimln_(476, "nimpy.nim");
			T122_ = (void*)0;
			T122_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyComplex_ImagAsDouble");
			(*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyComplex_ImagAsDouble = ((tyProc_2su9b9chqHYibM7sMkbSaSkA) (T122_));
			nimln_(503, "nimpy.nim");
			{
				Exception* e_18;
				NimStringDesc* T127_;
				nimln_(477, "nimpy.nim");
				if (!((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyComplex_ImagAsDouble == 0)) goto LA125_;
				e_18 = (Exception*)0;
				nimln_(2702, "system.nim");
				e_18 = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
				(*e_18).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
				nimln_(478, "nimpy.nim");
				T127_ = (NimStringDesc*)0;
				T127_ = (*e_18).message; (*e_18).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_27));
				if (T127_) nimGCunrefNoCycle(T127_);
				nimln_(2697, "system.nim");
				asgnRef((void**) (&(*e_18).parent), NIM_NIL);
				nimln_(478, "nimpy.nim");
				raiseException((Exception*)e_18, "Exception");
			}
			LA125_: ;
		}
		LA114_: ;
	}
	LA3_: ;
	nimln_(505, "nimpy.nim");
	memset((void*)(&T128_), 0, sizeof(T128_));
	(*m).methods = (tySequence_QIbr9abHr63pwRbRpKuoFFQ*) incrSeqV2(&((*m).methods)->Sup, sizeof(tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA));
	T129_ = (*m).methods->Sup.len++;
	(*m).methods->data[T129_] = T128_;
	popFrame();
}

static N_INLINE(tyObject_PyNimObjectcolonObjectType__EzO9cx6qeJIOpzFHShySXxA*, toNim_LIdCSVTxVJM5HLcUOCuUGwnimpy)(void* p) {
	tyObject_PyNimObjectcolonObjectType__EzO9cx6qeJIOpzFHShySXxA* result;
	NI TM_LoH0foxqckmmftA2y2Dp9aw_28;
	nimfr_("toNim", "nimpy.nim");
	result = (tyObject_PyNimObjectcolonObjectType__EzO9cx6qeJIOpzFHShySXxA*)0;
	nimln_(460, "nimpy.nim");
	TM_LoH0foxqckmmftA2y2Dp9aw_28 = addInt(((NI)sizeof(tyObject_PyObject_HEAD_EXTRA_NKPOYYFwv89cZkXWK0Hqo1w)), ((NI) 8));
	result = ((tyObject_PyNimObjectcolonObjectType__EzO9cx6qeJIOpzFHShySXxA*) ((NU)((NU64)(((NU) (p))) - (NU64)(((NU) ((NI)(TM_LoH0foxqckmmftA2y2Dp9aw_28)))))));
	popFrame();
	return result;
}

N_CDECL(void, destructNimObj_gP9bSgYtp25aud4g9as1b5JQ)(void* o) {
	tyObject_PyNimObjectcolonObjectType__EzO9cx6qeJIOpzFHShySXxA* n;
	nimfr_("destructNimObj", "nimpy.nim");
	nimln_(508, "nimpy.nim");
	n = toNim_LIdCSVTxVJM5HLcUOCuUGwnimpy(o);
	nimln_(509, "nimpy.nim");
	nimGCunref(n);
	popFrame();
}

N_CDECL(void, freeNimObj_BSyN3KaI27bZetfSWWb86w)(void* p) {
	Exception* e;
	NimStringDesc* T1_;
	nimfr_("freeNimObj", "nimpy.nim");
	e = (Exception*)0;
	nimln_(2702, "system.nim");
	e = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
	(*e).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
	nimln_(513, "nimpy.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*e).message; (*e).message = copyStringRC1(((NimStringDesc*) &TM_LoH0foxqckmmftA2y2Dp9aw_29));
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(2697, "system.nim");
	asgnRef((void**) (&(*e).parent), NIM_NIL);
	nimln_(513, "nimpy.nim");
	raiseException((Exception*)e, "Exception");
	popFrame();
}

static N_INLINE(tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA*, to_39cbYCg6zPfn9a9chN0oM7FHgnimpy)(void* p) {
	tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* result;
	nimfr_("to", "nimpy.nim");
	result = (tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA*)0;
	nimln_(454, "nimpy.nim");
	{
		if (!traceRefs_tlXpUlkM769cFvi4ZetY15A) goto LA3_;
		nimln_(455, "nimpy.nim");
		result = ((tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA*) ((NU)((NU64)(((NU) (p))) + (NU64)(((NU) (((NI)sizeof(tyObject_PyObject_HEAD_EXTRA_NKPOYYFwv89cZkXWK0Hqo1w))))))));
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(457, "nimpy.nim");
		result = ((tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA*) (p));
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, initModuleTypes_aYiLzwwt7ZRNmOisahibSA)(void* p, tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m) {
	nimfr_("initModuleTypes", "nimpy.nim");
	{
		NI i;
		NI colontmp_;
		NI T2_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(516, "nimpy.nim");
		T2_ = ((*m).types ? (*m).types->Sup.len : 0);
		colontmp_ = T2_;
		nimln_(3832, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3833, "system.nim");
			while (1) {
				void* typ;
				tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA* ty;
				NI TM_LoH0foxqckmmftA2y2Dp9aw_30;
				int T5_;
				int T6_;
				NI TM_LoH0foxqckmmftA2y2Dp9aw_31;
				if (!(i_2 < colontmp_)) goto LA4;
				nimln_(3834, "system.nim");
				i = i_2;
				nimln_(517, "nimpy.nim");
				typ = pyAlloc_PTU6OBy9bioXSlNFdi1q2gg(((NI)sizeof(tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA)));
				nimln_(518, "nimpy.nim");
				ty = to_39cbYCg6zPfn9a9chN0oM7FHgnimpy(typ);
				nimln_(519, "nimpy.nim");
				if ((NU)(i) >= (NU)((*m).types->Sup.len)) raiseIndexError();
				(*ty).tp_name = (*m).types->data[i].fullName->data;
				nimln_(523, "nimpy.nim");
				if ((NU)(i) >= (NU)((*m).types->Sup.len)) raiseIndexError();
				TM_LoH0foxqckmmftA2y2Dp9aw_30 = subInt(((int)chckRange((*m).types->data[i].origSize, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int) 8));
				if (TM_LoH0foxqckmmftA2y2Dp9aw_30 < (-2147483647 -1) || TM_LoH0foxqckmmftA2y2Dp9aw_30 > 2147483647) raiseOverflow();
				(*ty).tp_basicsize = ((size_t) ((NI32)(TM_LoH0foxqckmmftA2y2Dp9aw_30)));
				nimln_(524, "nimpy.nim");
				(*ty).tp_flags = ((unsigned long) 131563);
				nimln_(525, "nimpy.nim");
				if ((NU)(i) >= (NU)((*m).types->Sup.len)) raiseIndexError();
				(*ty).tp_doc = (*m).types->data[i].doc;
				nimln_(526, "nimpy.nim");
				if ((NU)(i) >= (NU)((*m).types->Sup.len)) raiseIndexError();
				(*ty).tp_new = (*m).types->data[i].newFunc;
				nimln_(527, "nimpy.nim");
				(*ty).tp_free = freeNimObj_BSyN3KaI27bZetfSWWb86w;
				nimln_(528, "nimpy.nim");
				(*ty).tp_dealloc = destructNimObj_gP9bSgYtp25aud4g9as1b5JQ;
				nimln_(530, "nimpy.nim");
				T5_ = (int)0;
				T5_ = (*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyType_Ready(((tyObject_PyTypeObject3Obj_uAcm1ZeLDGo4DslsWLA9cnA*) (typ)));
				T5_;
				nimln_(531, "nimpy.nim");
				incRef_aGFJKMPOa8pYliHzRN2VPAnimpy(typ);
				nimln_(532, "nimpy.nim");
				if ((NU)(i) >= (NU)((*m).types->Sup.len)) raiseIndexError();
				T6_ = (int)0;
				T6_ = (*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyModule_AddObject(p, (*m).types->data[i].name, typ);
				T6_;
				nimln_(3835, "system.nim");
				TM_LoH0foxqckmmftA2y2Dp9aw_31 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_LoH0foxqckmmftA2y2Dp9aw_31);
			} LA4: ;
		}
	}
	popFrame();
}

static N_INLINE(void, initModule2_czV3Hp3EXVZK9cnxiVizA9cwnimpy)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m) {
	tyProc_7NjwwXgjqHVJzOMXYXleoA Py_InitModule4;
	void* T1_;
	nimfr_("initModule2", "nimpy.nim");
	nimln_(535, "nimpy.nim");
	initCommon_QOPr6RYgxP9c8n2lZVbiDwA(m);
	Py_InitModule4 = (tyProc_7NjwwXgjqHVJzOMXYXleoA)0;
	nimln_(539, "nimpy.nim");
	T1_ = (void*)0;
	T1_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "Py_InitModule4");
	Py_InitModule4 = ((tyProc_7NjwwXgjqHVJzOMXYXleoA) (T1_));
	nimln_(540, "nimpy.nim");
	{
		void* T6_;
		if (!(Py_InitModule4 == 0)) goto LA4_;
		nimln_(541, "nimpy.nim");
		T6_ = (void*)0;
		T6_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "Py_InitModule4_64");
		Py_InitModule4 = ((tyProc_7NjwwXgjqHVJzOMXYXleoA) (T6_));
	}
	LA4_: ;
	nimln_(542, "nimpy.nim");
	{
		void* py;
		if (!!((Py_InitModule4 == 0))) goto LA9_;
		nimln_(543, "nimpy.nim");
		if ((NU)(((NI) 0)) >= (NU)((*m).methods->Sup.len)) raiseIndexError();
		py = Py_InitModule4((*m).name, (&(*m).methods->data[((NI) 0)]), (*m).doc, NIM_NIL, ((int) 1013));
		nimln_(544, "nimpy.nim");
		initModuleTypes_aYiLzwwt7ZRNmOisahibSA(py, m);
	}
	LA9_: ;
	popFrame();
}

static N_INLINE(void, initPyModule_nPSQLKdnxTDvCUB31oENYQnimpy)(tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw* p, tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m) {
	nimfr_("initPyModule", "nimpy.nim");
	nimln_(547, "nimpy.nim");
	(*p).m_base.ob_base.ob_refcnt = ((NI) 1);
	nimln_(548, "nimpy.nim");
	(*p).m_name = (*m).name;
	nimln_(549, "nimpy.nim");
	(*p).m_doc = (*m).doc;
	nimln_(550, "nimpy.nim");
	(*p).m_size = ((NI) -1);
	nimln_(551, "nimpy.nim");
	if ((NU)(((NI) 0)) >= (NU)((*m).methods->Sup.len)) raiseIndexError();
	(*p).m_methods = (&(*m).methods->data[((NI) 0)]);
	popFrame();
}

static N_INLINE(tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw*, to_RvoceX4eN8TgFBHbu8LOvwnimpy)(void* p) {
	tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw* result;
	nimfr_("to", "nimpy.nim");
	result = (tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw*)0;
	nimln_(454, "nimpy.nim");
	{
		if (!traceRefs_tlXpUlkM769cFvi4ZetY15A) goto LA3_;
		nimln_(455, "nimpy.nim");
		result = ((tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw*) ((NU)((NU64)(((NU) (p))) + (NU64)(((NU) (((NI)sizeof(tyObject_PyObject_HEAD_EXTRA_NKPOYYFwv89cZkXWK0Hqo1w))))))));
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(457, "nimpy.nim");
		result = ((tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw*) (p));
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(void*, initModule3_okp5JtSm53wnPxjJK0sxNAnimpy)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m) {
	void* result;
	tyProc_BEMKLd49c5qNHqmldA6aVaw PyModule_Create2;
	void* T1_;
	nimfr_("initModule3", "nimpy.nim");
	result = (void*)0;
	nimln_(554, "nimpy.nim");
	initCommon_QOPr6RYgxP9c8n2lZVbiDwA(m);
	PyModule_Create2 = (tyProc_BEMKLd49c5qNHqmldA6aVaw)0;
	nimln_(557, "nimpy.nim");
	T1_ = (void*)0;
	T1_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyModule_Create2");
	PyModule_Create2 = ((tyProc_BEMKLd49c5qNHqmldA6aVaw) (T1_));
	nimln_(559, "nimpy.nim");
	{
		void* T6_;
		if (!(PyModule_Create2 == 0)) goto LA4_;
		nimln_(560, "nimpy.nim");
		T6_ = (void*)0;
		T6_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).module, "PyModule_Create2TraceRefs");
		PyModule_Create2 = ((tyProc_BEMKLd49c5qNHqmldA6aVaw) (T6_));
	}
	LA4_: ;
	nimln_(562, "nimpy.nim");
	{
		void* pymod;
		tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw* T11_;
		if (!!((PyModule_Create2 == 0))) goto LA9_;
		nimln_(563, "nimpy.nim");
		pymod = pyAlloc_PTU6OBy9bioXSlNFdi1q2gg(((NI)sizeof(tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw)));
		nimln_(564, "nimpy.nim");
		T11_ = (tyObject_PyModuleDef_Svhgqn5skjUG4pePsYxvqw*)0;
		T11_ = to_RvoceX4eN8TgFBHbu8LOvwnimpy(pymod);
		initPyModule_nPSQLKdnxTDvCUB31oENYQnimpy(T11_, m);
		nimln_(565, "nimpy.nim");
		result = PyModule_Create2(pymod, ((int) 3));
		nimln_(566, "nimpy.nim");
		initModuleTypes_aYiLzwwt7ZRNmOisahibSA(result, m);
	}
	LA9_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, initModuleAux2_QOPr6RYgxP9c8n2lZVbiDwA_2)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m) {
	{
		if (!(pyLib_bgKRHU9cKqO7op9cXO6AxcTw == 0)) goto LA3_;
		NimMain();
	}
	LA3_: ;
	initModule2_czV3Hp3EXVZK9cnxiVizA9cwnimpy(m);
}

N_NIMCALL(void*, initModuleAux3_fiCOhQD5a4JY3kdtM19cCuQ)(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA* m) {
	void* result;
	result = (void*)0;
	{
		if (!(pyLib_bgKRHU9cKqO7op9cXO6AxcTw == 0)) goto LA3_;
		NimMain();
	}
	LA3_: ;
	result = initModule3_okp5JtSm53wnPxjJK0sxNAnimpy(m);
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

N_NIMCALL(NimStringDesc*, toString_slL8EbtkTixT9aehlJ9cV9bGQ)(tyObject_Py_buffer_nRhjorz1m8nM8MZqKMfgRA* b) {
	NimStringDesc* result;
	nimfr_("toString", "nimpy.nim");
	result = (NimStringDesc*)0;
	nimln_(624, "nimpy.nim");
	{
		size_t ln;
		if (!!(((*b).buf == 0))) goto LA3_;
		nimln_(625, "nimpy.nim");
		ln = (*b).len;
		nimln_(626, "nimpy.nim");
		result = mnewString(((NI)chckRange(ln, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(627, "nimpy.nim");
		{
			nimln_(378, "system.nim");
			nimln_(627, "nimpy.nim");
			if (!!((ln == ((NI) 0)))) goto LA7_;
			nimln_(628, "nimpy.nim");
			if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
			copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&result->data[((NI) 0)]))), (*b).buf, ((NI)chckRange(ln, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		}
		LA7_: ;
	}
	LA3_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, pyObjToNim_yiwC7N9bqau80g2TsV2jwNg)(void* o, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* s) {
	nimfr_("pyObjToNim", "nimpy.nim");
	nimln_(673, "nimpy.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = unlikely(((*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyComplex_AsCComplex == 0));
		if (!T3_) goto LA4_;
		nimln_(674, "nimpy.nim");
		(*s).Field0 = (*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyComplex_RealAsDouble(o);
		nimln_(675, "nimpy.nim");
		(*s).Field1 = (*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyComplex_ImagAsDouble(o);
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(677, "nimpy.nim");
		(*s) = (*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).PyComplex_AsCComplex(o);
	}
	LA1_: ;
	popFrame();
}

static N_INLINE(void*, strToPyObject_5KC9cg9bQBGcEpbowAmucpaQnimpy)(NimStringDesc* s) {
	void* result;
	NCSTRING cs;
	int ln;
	nimfr_("strToPyObject", "nimpy.nim");
	result = (void*)0;
	nimln_(705, "nimpy.nim");
	cs = (NCSTRING)0;
	ln = (int)0;
	nimln_(707, "nimpy.nim");
	{
		if (!!((s == 0))) goto LA3_;
		nimln_(708, "nimpy.nim");
		cs = s->data;
		nimln_(709, "nimpy.nim");
		ln = ((int)chckRange((s->Sup.len), ((int) (-2147483647 -1)), ((int) 2147483647)));
	}
	LA3_: ;
	nimln_(710, "nimpy.nim");
	result = (*pyLib_bgKRHU9cKqO7op9cXO6AxcTw).Py_BuildValue("s#", cs, ln);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, nimpy_nimpyInit000)(void) {
	nimfr_("nimpy", "nimpy.nim");
nimRegisterGlobalMarker(TM_LoH0foxqckmmftA2y2Dp9aw_3);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimpy_nimpyDatInit000)(void) {
static TNimNode* TM_LoH0foxqckmmftA2y2Dp9aw_2[18];
static TNimNode* TM_LoH0foxqckmmftA2y2Dp9aw_4[4];
static TNimNode* TM_LoH0foxqckmmftA2y2Dp9aw_5[8];
static TNimNode* TM_LoH0foxqckmmftA2y2Dp9aw_6[4];
static TNimNode* TM_LoH0foxqckmmftA2y2Dp9aw_7[5];
static TNimNode TM_LoH0foxqckmmftA2y2Dp9aw_0[44];
NTI_ao1O59bN9asAtLBM32qv9bIJg_.size = sizeof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg);
NTI_ao1O59bN9asAtLBM32qv9bIJg_.kind = 18;
NTI_ao1O59bN9asAtLBM32qv9bIJg_.base = 0;
NTI_ao1O59bN9asAtLBM32qv9bIJg_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_2[0] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[1];
TM_LoH0foxqckmmftA2y2Dp9aw_0[1].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[1].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, module);
TM_LoH0foxqckmmftA2y2Dp9aw_0[1].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[1].name = "module";
TM_LoH0foxqckmmftA2y2Dp9aw_2[1] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[2];
NTI_SsjMo29bx9bP5kwe2xgM3Scg_.size = sizeof(void*);
NTI_SsjMo29bx9bP5kwe2xgM3Scg_.kind = 25;
NTI_SsjMo29bx9bP5kwe2xgM3Scg_.base = 0;
NTI_SsjMo29bx9bP5kwe2xgM3Scg_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[2].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[2].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, Py_BuildValue);
TM_LoH0foxqckmmftA2y2Dp9aw_0[2].typ = (&NTI_SsjMo29bx9bP5kwe2xgM3Scg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[2].name = "Py_BuildValue";
TM_LoH0foxqckmmftA2y2Dp9aw_2[2] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[3];
NTI_ocClJDlcZaqgYpi2lF669cA_.size = sizeof(tyProc_ocClJDlcZaqgYpi2lF669cA);
NTI_ocClJDlcZaqgYpi2lF669cA_.kind = 25;
NTI_ocClJDlcZaqgYpi2lF669cA_.base = 0;
NTI_ocClJDlcZaqgYpi2lF669cA_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[3].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[3].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyTuple_Size);
TM_LoH0foxqckmmftA2y2Dp9aw_0[3].typ = (&NTI_ocClJDlcZaqgYpi2lF669cA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[3].name = "PyTuple_Size";
TM_LoH0foxqckmmftA2y2Dp9aw_2[3] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[4];
NTI_xKuFDtrrlpEd0ARlODf8xA_.size = sizeof(tyProc_xKuFDtrrlpEd0ARlODf8xA);
NTI_xKuFDtrrlpEd0ARlODf8xA_.kind = 25;
NTI_xKuFDtrrlpEd0ARlODf8xA_.base = 0;
NTI_xKuFDtrrlpEd0ARlODf8xA_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[4].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[4].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyTuple_GetItem);
TM_LoH0foxqckmmftA2y2Dp9aw_0[4].typ = (&NTI_xKuFDtrrlpEd0ARlODf8xA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[4].name = "PyTuple_GetItem";
TM_LoH0foxqckmmftA2y2Dp9aw_2[4] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[5];
TM_LoH0foxqckmmftA2y2Dp9aw_0[5].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[5].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, Py_None);
TM_LoH0foxqckmmftA2y2Dp9aw_0[5].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[5].name = "Py_None";
TM_LoH0foxqckmmftA2y2Dp9aw_2[5] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[6];
NTI_JOheI6S14zehX7QFjD9b9arA_.size = sizeof(tyProc_JOheI6S14zehX7QFjD9b9arA);
NTI_JOheI6S14zehX7QFjD9b9arA_.kind = 25;
NTI_JOheI6S14zehX7QFjD9b9arA_.base = 0;
NTI_JOheI6S14zehX7QFjD9b9arA_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[6].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[6].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyType_Ready);
TM_LoH0foxqckmmftA2y2Dp9aw_0[6].typ = (&NTI_JOheI6S14zehX7QFjD9b9arA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[6].name = "PyType_Ready";
TM_LoH0foxqckmmftA2y2Dp9aw_2[6] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[7];
NTI_gaBVY12IBlwVY2fikmPgHQ_.size = sizeof(tyProc_gaBVY12IBlwVY2fikmPgHQ);
NTI_gaBVY12IBlwVY2fikmPgHQ_.kind = 25;
NTI_gaBVY12IBlwVY2fikmPgHQ_.base = 0;
NTI_gaBVY12IBlwVY2fikmPgHQ_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[7].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[7].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyType_GenericNew);
TM_LoH0foxqckmmftA2y2Dp9aw_0[7].typ = (&NTI_gaBVY12IBlwVY2fikmPgHQ_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[7].name = "PyType_GenericNew";
TM_LoH0foxqckmmftA2y2Dp9aw_2[7] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[8];
NTI_T08W9bgbY4bOv2q64h6irpw_.size = sizeof(tyProc_T08W9bgbY4bOv2q64h6irpw);
NTI_T08W9bgbY4bOv2q64h6irpw_.kind = 25;
NTI_T08W9bgbY4bOv2q64h6irpw_.base = 0;
NTI_T08W9bgbY4bOv2q64h6irpw_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[8].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[8].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyModule_AddObject);
TM_LoH0foxqckmmftA2y2Dp9aw_0[8].typ = (&NTI_T08W9bgbY4bOv2q64h6irpw_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[8].name = "PyModule_AddObject";
TM_LoH0foxqckmmftA2y2Dp9aw_2[8] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[9];
NTI_E3yjbFti2J9bkUN9ckhwcXeg_.size = sizeof(tyProc_E3yjbFti2J9bkUN9ckhwcXeg);
NTI_E3yjbFti2J9bkUN9ckhwcXeg_.kind = 25;
NTI_E3yjbFti2J9bkUN9ckhwcXeg_.base = 0;
NTI_E3yjbFti2J9bkUN9ckhwcXeg_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[9].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[9].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyList_New);
TM_LoH0foxqckmmftA2y2Dp9aw_0[9].typ = (&NTI_E3yjbFti2J9bkUN9ckhwcXeg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[9].name = "PyList_New";
TM_LoH0foxqckmmftA2y2Dp9aw_2[9] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[10];
TM_LoH0foxqckmmftA2y2Dp9aw_0[10].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[10].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyList_Size);
TM_LoH0foxqckmmftA2y2Dp9aw_0[10].typ = (&NTI_ocClJDlcZaqgYpi2lF669cA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[10].name = "PyList_Size";
TM_LoH0foxqckmmftA2y2Dp9aw_2[10] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[11];
TM_LoH0foxqckmmftA2y2Dp9aw_0[11].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[11].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyList_GetItem);
TM_LoH0foxqckmmftA2y2Dp9aw_0[11].typ = (&NTI_xKuFDtrrlpEd0ARlODf8xA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[11].name = "PyList_GetItem";
TM_LoH0foxqckmmftA2y2Dp9aw_2[11] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[12];
NTI_nuVTH6REO8jfyM9augS15pw_.size = sizeof(tyProc_nuVTH6REO8jfyM9augS15pw);
NTI_nuVTH6REO8jfyM9augS15pw_.kind = 25;
NTI_nuVTH6REO8jfyM9augS15pw_.base = 0;
NTI_nuVTH6REO8jfyM9augS15pw_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[12].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[12].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyList_SetItem);
TM_LoH0foxqckmmftA2y2Dp9aw_0[12].typ = (&NTI_nuVTH6REO8jfyM9augS15pw_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[12].name = "PyList_SetItem";
TM_LoH0foxqckmmftA2y2Dp9aw_2[12] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[13];
NTI_mIlNZ9aGaphVJCyIIofK8mg_.size = sizeof(tyProc_mIlNZ9aGaphVJCyIIofK8mg);
NTI_mIlNZ9aGaphVJCyIIofK8mg_.kind = 25;
NTI_mIlNZ9aGaphVJCyIIofK8mg_.base = 0;
NTI_mIlNZ9aGaphVJCyIIofK8mg_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[13].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[13].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyLong_AsLongLong);
TM_LoH0foxqckmmftA2y2Dp9aw_0[13].typ = (&NTI_mIlNZ9aGaphVJCyIIofK8mg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[13].name = "PyLong_AsLongLong";
TM_LoH0foxqckmmftA2y2Dp9aw_2[13] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[14];
NTI_2su9b9chqHYibM7sMkbSaSkA_.size = sizeof(tyProc_2su9b9chqHYibM7sMkbSaSkA);
NTI_2su9b9chqHYibM7sMkbSaSkA_.kind = 25;
NTI_2su9b9chqHYibM7sMkbSaSkA_.base = 0;
NTI_2su9b9chqHYibM7sMkbSaSkA_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[14].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[14].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyFloat_AsDouble);
TM_LoH0foxqckmmftA2y2Dp9aw_0[14].typ = (&NTI_2su9b9chqHYibM7sMkbSaSkA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[14].name = "PyFloat_AsDouble";
TM_LoH0foxqckmmftA2y2Dp9aw_2[14] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[15];
NTI_RKlUmjvtmKGnc01PbvZaRQ_.size = sizeof(tyProc_RKlUmjvtmKGnc01PbvZaRQ);
NTI_RKlUmjvtmKGnc01PbvZaRQ_.kind = 25;
NTI_RKlUmjvtmKGnc01PbvZaRQ_.base = 0;
NTI_RKlUmjvtmKGnc01PbvZaRQ_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[15].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[15].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyBool_FromLong);
TM_LoH0foxqckmmftA2y2Dp9aw_0[15].typ = (&NTI_RKlUmjvtmKGnc01PbvZaRQ_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[15].name = "PyBool_FromLong";
TM_LoH0foxqckmmftA2y2Dp9aw_2[15] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[16];
NTI_pp2rHJik8czES8sAFDwvQQ_.size = sizeof(tyProc_pp2rHJik8czES8sAFDwvQQ);
NTI_pp2rHJik8czES8sAFDwvQQ_.kind = 25;
NTI_pp2rHJik8czES8sAFDwvQQ_.base = 0;
NTI_pp2rHJik8czES8sAFDwvQQ_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[16].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[16].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyComplex_AsCComplex);
TM_LoH0foxqckmmftA2y2Dp9aw_0[16].typ = (&NTI_pp2rHJik8czES8sAFDwvQQ_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[16].name = "PyComplex_AsCComplex";
TM_LoH0foxqckmmftA2y2Dp9aw_2[16] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[17];
TM_LoH0foxqckmmftA2y2Dp9aw_0[17].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[17].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyComplex_RealAsDouble);
TM_LoH0foxqckmmftA2y2Dp9aw_0[17].typ = (&NTI_2su9b9chqHYibM7sMkbSaSkA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[17].name = "PyComplex_RealAsDouble";
TM_LoH0foxqckmmftA2y2Dp9aw_2[17] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[18];
TM_LoH0foxqckmmftA2y2Dp9aw_0[18].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[18].offset = offsetof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg, PyComplex_ImagAsDouble);
TM_LoH0foxqckmmftA2y2Dp9aw_0[18].typ = (&NTI_2su9b9chqHYibM7sMkbSaSkA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[18].name = "PyComplex_ImagAsDouble";
TM_LoH0foxqckmmftA2y2Dp9aw_0[0].len = 18; TM_LoH0foxqckmmftA2y2Dp9aw_0[0].kind = 2; TM_LoH0foxqckmmftA2y2Dp9aw_0[0].sons = &TM_LoH0foxqckmmftA2y2Dp9aw_2[0];
NTI_ao1O59bN9asAtLBM32qv9bIJg_.node = &TM_LoH0foxqckmmftA2y2Dp9aw_0[0];
NTI_q7GVR3hKxnZZLg2r6rGifQ_.size = sizeof(tyObject_PyLibcolonObjectType__ao1O59bN9asAtLBM32qv9bIJg*);
NTI_q7GVR3hKxnZZLg2r6rGifQ_.kind = 22;
NTI_q7GVR3hKxnZZLg2r6rGifQ_.base = (&NTI_ao1O59bN9asAtLBM32qv9bIJg_);
NTI_q7GVR3hKxnZZLg2r6rGifQ_.flags = 2;
NTI_q7GVR3hKxnZZLg2r6rGifQ_.marker = Marker_tyRef_q7GVR3hKxnZZLg2r6rGifQ;
NTI_33Z7fkQhmIaDXevopp3LQA_.size = sizeof(tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA);
NTI_33Z7fkQhmIaDXevopp3LQA_.kind = 18;
NTI_33Z7fkQhmIaDXevopp3LQA_.base = 0;
NTI_33Z7fkQhmIaDXevopp3LQA_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_4[0] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[20];
TM_LoH0foxqckmmftA2y2Dp9aw_0[20].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[20].offset = offsetof(tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA, ml_name);
TM_LoH0foxqckmmftA2y2Dp9aw_0[20].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[20].name = "ml_name";
TM_LoH0foxqckmmftA2y2Dp9aw_4[1] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[21];
NTI_VQ1ysQk017myXMGb79cPTVw_.size = sizeof(tyProc_VQ1ysQk017myXMGb79cPTVw);
NTI_VQ1ysQk017myXMGb79cPTVw_.kind = 25;
NTI_VQ1ysQk017myXMGb79cPTVw_.base = 0;
NTI_VQ1ysQk017myXMGb79cPTVw_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[21].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[21].offset = offsetof(tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA, ml_meth);
TM_LoH0foxqckmmftA2y2Dp9aw_0[21].typ = (&NTI_VQ1ysQk017myXMGb79cPTVw_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[21].name = "ml_meth";
TM_LoH0foxqckmmftA2y2Dp9aw_4[2] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[22];
TM_LoH0foxqckmmftA2y2Dp9aw_0[22].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[22].offset = offsetof(tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA, ml_flags);
TM_LoH0foxqckmmftA2y2Dp9aw_0[22].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[22].name = "ml_flags";
TM_LoH0foxqckmmftA2y2Dp9aw_4[3] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[23];
TM_LoH0foxqckmmftA2y2Dp9aw_0[23].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[23].offset = offsetof(tyObject_PyMethodDef_33Z7fkQhmIaDXevopp3LQA, ml_doc);
TM_LoH0foxqckmmftA2y2Dp9aw_0[23].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[23].name = "ml_doc";
TM_LoH0foxqckmmftA2y2Dp9aw_0[19].len = 4; TM_LoH0foxqckmmftA2y2Dp9aw_0[19].kind = 2; TM_LoH0foxqckmmftA2y2Dp9aw_0[19].sons = &TM_LoH0foxqckmmftA2y2Dp9aw_4[0];
NTI_33Z7fkQhmIaDXevopp3LQA_.node = &TM_LoH0foxqckmmftA2y2Dp9aw_0[19];
NTI_QIbr9abHr63pwRbRpKuoFFQ_.size = sizeof(tySequence_QIbr9abHr63pwRbRpKuoFFQ*);
NTI_QIbr9abHr63pwRbRpKuoFFQ_.kind = 24;
NTI_QIbr9abHr63pwRbRpKuoFFQ_.base = (&NTI_33Z7fkQhmIaDXevopp3LQA_);
NTI_QIbr9abHr63pwRbRpKuoFFQ_.flags = 2;
NTI_QIbr9abHr63pwRbRpKuoFFQ_.marker = Marker_tySequence_QIbr9abHr63pwRbRpKuoFFQ;
NTI_BKCcJxogshNojOoN23Qfbg_.size = sizeof(tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg);
NTI_BKCcJxogshNojOoN23Qfbg_.kind = 18;
NTI_BKCcJxogshNojOoN23Qfbg_.base = 0;
NTI_BKCcJxogshNojOoN23Qfbg_.flags = 2;
TM_LoH0foxqckmmftA2y2Dp9aw_5[0] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[25];
NTI_gBC8z6Ez5xj3dXoP0ylCRA_.size = sizeof(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA);
NTI_gBC8z6Ez5xj3dXoP0ylCRA_.kind = 18;
NTI_gBC8z6Ez5xj3dXoP0ylCRA_.base = 0;
NTI_gBC8z6Ez5xj3dXoP0ylCRA_.flags = 2;
TM_LoH0foxqckmmftA2y2Dp9aw_6[0] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[27];
TM_LoH0foxqckmmftA2y2Dp9aw_0[27].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[27].offset = offsetof(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA, name);
TM_LoH0foxqckmmftA2y2Dp9aw_0[27].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[27].name = "name";
TM_LoH0foxqckmmftA2y2Dp9aw_6[1] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[28];
TM_LoH0foxqckmmftA2y2Dp9aw_0[28].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[28].offset = offsetof(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA, doc);
TM_LoH0foxqckmmftA2y2Dp9aw_0[28].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[28].name = "doc";
TM_LoH0foxqckmmftA2y2Dp9aw_6[2] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[29];
TM_LoH0foxqckmmftA2y2Dp9aw_0[29].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[29].offset = offsetof(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA, methods);
TM_LoH0foxqckmmftA2y2Dp9aw_0[29].typ = (&NTI_QIbr9abHr63pwRbRpKuoFFQ_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[29].name = "methods";
TM_LoH0foxqckmmftA2y2Dp9aw_6[3] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[30];
TM_LoH0foxqckmmftA2y2Dp9aw_0[30].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[30].offset = offsetof(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA, types);
TM_LoH0foxqckmmftA2y2Dp9aw_0[30].typ = (&NTI_1Ib9a4sxiw4YCYbDTADLEsg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[30].name = "types";
TM_LoH0foxqckmmftA2y2Dp9aw_0[26].len = 4; TM_LoH0foxqckmmftA2y2Dp9aw_0[26].kind = 2; TM_LoH0foxqckmmftA2y2Dp9aw_0[26].sons = &TM_LoH0foxqckmmftA2y2Dp9aw_6[0];
NTI_gBC8z6Ez5xj3dXoP0ylCRA_.node = &TM_LoH0foxqckmmftA2y2Dp9aw_0[26];
NTI_v2GijgCrTru9brL7cjgOkag_.size = sizeof(tyObject_PyModuleDesc_gBC8z6Ez5xj3dXoP0ylCRA*);
NTI_v2GijgCrTru9brL7cjgOkag_.kind = 21;
NTI_v2GijgCrTru9brL7cjgOkag_.base = (&NTI_gBC8z6Ez5xj3dXoP0ylCRA_);
NTI_v2GijgCrTru9brL7cjgOkag_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[25].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[25].offset = offsetof(tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg, module);
TM_LoH0foxqckmmftA2y2Dp9aw_0[25].typ = (&NTI_v2GijgCrTru9brL7cjgOkag_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[25].name = "module";
TM_LoH0foxqckmmftA2y2Dp9aw_5[1] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[31];
TM_LoH0foxqckmmftA2y2Dp9aw_0[31].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[31].offset = offsetof(tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg, name);
TM_LoH0foxqckmmftA2y2Dp9aw_0[31].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[31].name = "name";
TM_LoH0foxqckmmftA2y2Dp9aw_5[2] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[32];
TM_LoH0foxqckmmftA2y2Dp9aw_0[32].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[32].offset = offsetof(tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg, doc);
TM_LoH0foxqckmmftA2y2Dp9aw_0[32].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[32].name = "doc";
TM_LoH0foxqckmmftA2y2Dp9aw_5[3] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[33];
TM_LoH0foxqckmmftA2y2Dp9aw_0[33].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[33].offset = offsetof(tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg, fullName);
TM_LoH0foxqckmmftA2y2Dp9aw_0[33].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[33].name = "fullName";
TM_LoH0foxqckmmftA2y2Dp9aw_5[4] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[34];
TM_LoH0foxqckmmftA2y2Dp9aw_0[34].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[34].offset = offsetof(tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg, newFunc);
TM_LoH0foxqckmmftA2y2Dp9aw_0[34].typ = (&NTI_gaBVY12IBlwVY2fikmPgHQ_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[34].name = "newFunc";
TM_LoH0foxqckmmftA2y2Dp9aw_5[5] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[35];
TM_LoH0foxqckmmftA2y2Dp9aw_0[35].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[35].offset = offsetof(tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg, methods);
TM_LoH0foxqckmmftA2y2Dp9aw_0[35].typ = (&NTI_QIbr9abHr63pwRbRpKuoFFQ_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[35].name = "methods";
TM_LoH0foxqckmmftA2y2Dp9aw_5[6] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[36];
NTI_2pF0VEkKjttowUMYhsxfyw_.size = sizeof(tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw);
NTI_2pF0VEkKjttowUMYhsxfyw_.kind = 18;
NTI_2pF0VEkKjttowUMYhsxfyw_.base = 0;
NTI_2pF0VEkKjttowUMYhsxfyw_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_7[0] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[38];
TM_LoH0foxqckmmftA2y2Dp9aw_0[38].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[38].offset = offsetof(tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw, name);
TM_LoH0foxqckmmftA2y2Dp9aw_0[38].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[38].name = "name";
TM_LoH0foxqckmmftA2y2Dp9aw_7[1] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[39];
TM_LoH0foxqckmmftA2y2Dp9aw_0[39].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[39].offset = offsetof(tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw, typ);
TM_LoH0foxqckmmftA2y2Dp9aw_0[39].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[39].name = "typ";
TM_LoH0foxqckmmftA2y2Dp9aw_7[2] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[40];
NTI_Q4mRjQ149bG48TfHO9bTZVmA_.size = sizeof(size_t);
NTI_Q4mRjQ149bG48TfHO9bTZVmA_.kind = 31;
NTI_Q4mRjQ149bG48TfHO9bTZVmA_.base = 0;
NTI_Q4mRjQ149bG48TfHO9bTZVmA_.flags = 3;
TM_LoH0foxqckmmftA2y2Dp9aw_0[40].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[40].offset = offsetof(tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw, offset);
TM_LoH0foxqckmmftA2y2Dp9aw_0[40].typ = (&NTI_Q4mRjQ149bG48TfHO9bTZVmA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[40].name = "offset";
TM_LoH0foxqckmmftA2y2Dp9aw_7[3] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[41];
TM_LoH0foxqckmmftA2y2Dp9aw_0[41].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[41].offset = offsetof(tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw, flags);
TM_LoH0foxqckmmftA2y2Dp9aw_0[41].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[41].name = "flags";
TM_LoH0foxqckmmftA2y2Dp9aw_7[4] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[42];
TM_LoH0foxqckmmftA2y2Dp9aw_0[42].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[42].offset = offsetof(tyObject_PyMemberDef_2pF0VEkKjttowUMYhsxfyw, doc);
TM_LoH0foxqckmmftA2y2Dp9aw_0[42].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[42].name = "doc";
TM_LoH0foxqckmmftA2y2Dp9aw_0[37].len = 5; TM_LoH0foxqckmmftA2y2Dp9aw_0[37].kind = 2; TM_LoH0foxqckmmftA2y2Dp9aw_0[37].sons = &TM_LoH0foxqckmmftA2y2Dp9aw_7[0];
NTI_2pF0VEkKjttowUMYhsxfyw_.node = &TM_LoH0foxqckmmftA2y2Dp9aw_0[37];
NTI_m5LAl09cqBl9bzwvVnw9aEKrg_.size = sizeof(tySequence_m5LAl09cqBl9bzwvVnw9aEKrg*);
NTI_m5LAl09cqBl9bzwvVnw9aEKrg_.kind = 24;
NTI_m5LAl09cqBl9bzwvVnw9aEKrg_.base = (&NTI_2pF0VEkKjttowUMYhsxfyw_);
NTI_m5LAl09cqBl9bzwvVnw9aEKrg_.flags = 2;
NTI_m5LAl09cqBl9bzwvVnw9aEKrg_.marker = Marker_tySequence_m5LAl09cqBl9bzwvVnw9aEKrg;
TM_LoH0foxqckmmftA2y2Dp9aw_0[36].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[36].offset = offsetof(tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg, members);
TM_LoH0foxqckmmftA2y2Dp9aw_0[36].typ = (&NTI_m5LAl09cqBl9bzwvVnw9aEKrg_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[36].name = "members";
TM_LoH0foxqckmmftA2y2Dp9aw_5[7] = &TM_LoH0foxqckmmftA2y2Dp9aw_0[43];
TM_LoH0foxqckmmftA2y2Dp9aw_0[43].kind = 1;
TM_LoH0foxqckmmftA2y2Dp9aw_0[43].offset = offsetof(tyObject_PyTypeDesc_BKCcJxogshNojOoN23Qfbg, origSize);
TM_LoH0foxqckmmftA2y2Dp9aw_0[43].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_LoH0foxqckmmftA2y2Dp9aw_0[43].name = "origSize";
TM_LoH0foxqckmmftA2y2Dp9aw_0[24].len = 8; TM_LoH0foxqckmmftA2y2Dp9aw_0[24].kind = 2; TM_LoH0foxqckmmftA2y2Dp9aw_0[24].sons = &TM_LoH0foxqckmmftA2y2Dp9aw_5[0];
NTI_BKCcJxogshNojOoN23Qfbg_.node = &TM_LoH0foxqckmmftA2y2Dp9aw_0[24];
NTI_1Ib9a4sxiw4YCYbDTADLEsg_.size = sizeof(tySequence_1Ib9a4sxiw4YCYbDTADLEsg*);
NTI_1Ib9a4sxiw4YCYbDTADLEsg_.kind = 24;
NTI_1Ib9a4sxiw4YCYbDTADLEsg_.base = (&NTI_BKCcJxogshNojOoN23Qfbg_);
NTI_1Ib9a4sxiw4YCYbDTADLEsg_.flags = 2;
NTI_1Ib9a4sxiw4YCYbDTADLEsg_.marker = Marker_tySequence_1Ib9a4sxiw4YCYbDTADLEsg;
}

