
#include "nuitka/prelude.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_float_0_5;
PyObject *const_int_neg_1;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_int_pos_4;
PyObject *const_int_pos_5;
PyObject *const_int_pos_8;
PyObject *const_str_empty;
PyObject *const_str_space;
PyObject *const_dict_empty;
PyObject *const_int_pos_10;
PyObject *const_int_pos_16;
PyObject *const_int_pos_32;
PyObject *const_str_chr_42;
PyObject *const_str_chr_44;
PyObject *const_bytes_empty;
PyObject *const_str_newline;
PyObject *const_str_plain_X;
PyObject *const_str_plain__;
PyObject *const_str_plain_b;
PyObject *const_str_plain_c;
PyObject *const_str_plain_f;
PyObject *const_str_plain_h;
PyObject *const_str_plain_i;
PyObject *const_str_plain_o;
PyObject *const_str_plain_r;
PyObject *const_str_plain_s;
PyObject *const_str_plain_u;
PyObject *const_str_plain_w;
PyObject *const_str_plain_x;
PyObject *const_str_plain_y;
PyObject *const_tuple_empty;
PyObject *const_str_plain_io;
PyObject *const_str_plain_nt;
PyObject *const_str_plain_os;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_chr;
PyObject *const_str_plain_doc;
PyObject *const_str_plain_end;
PyObject *const_str_plain_get;
PyObject *const_str_plain_imp;
PyObject *const_str_plain_int;
PyObject *const_str_plain_key;
PyObject *const_str_plain_len;
PyObject *const_str_plain_map;
PyObject *const_str_plain_mod;
PyObject *const_str_plain_obj;
PyObject *const_str_plain_pop;
PyObject *const_str_plain_pos;
PyObject *const_str_plain_str;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sys;
PyObject *const_str_plain_val;
PyObject *const_str_plain_ver;
PyObject *const_str_plain_Font;
PyObject *const_str_plain_None;
PyObject *const_str_plain_Rect;
PyObject *const_str_plain_args;
PyObject *const_str_plain_argv;
PyObject *const_str_plain_bold;
PyObject *const_str_plain_copy;
PyObject *const_str_plain_data;
PyObject *const_str_plain_dict;
PyObject *const_str_plain_draw;
PyObject *const_str_plain_file;
PyObject *const_str_plain_font;
PyObject *const_str_plain_imap;
PyObject *const_str_plain_info;
PyObject *const_str_plain_init;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_join;
PyObject *const_str_plain_keys;
PyObject *const_str_plain_left;
PyObject *const_str_plain_line;
PyObject *const_str_plain_long;
PyObject *const_str_plain_mask;
PyObject *const_str_plain_name;
PyObject *const_str_plain_next;
PyObject *const_str_plain_open;
PyObject *const_str_plain_path;
PyObject *const_str_plain_quit;
PyObject *const_str_plain_read;
PyObject *const_str_plain_rect;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_self;
PyObject *const_str_plain_send;
PyObject *const_str_plain_site;
PyObject *const_str_plain_size;
PyObject *const_str_plain_time;
PyObject *const_str_plain_type;
PyObject *const_str_plain_wait;
PyObject *const_str_plain_Close;
PyObject *const_str_plain_Color;
PyObject *const_str_plain_False;
PyObject *const_str_plain_Queue;
PyObject *const_str_plain_array;
PyObject *const_str_plain_ascii;
PyObject *const_str_plain_bytes;
PyObject *const_str_plain_close;
PyObject *const_str_plain_color;
PyObject *const_str_plain_empty;
PyObject *const_str_plain_error;
PyObject *const_str_plain_event;
PyObject *const_str_plain_found;
PyObject *const_str_plain_image;
PyObject *const_str_plain_input;
PyObject *const_str_plain_items;
PyObject *const_str_plain_level;
PyObject *const_str_plain_lower;
PyObject *const_str_plain_mixer;
PyObject *const_str_plain_numpy;
PyObject *const_str_plain_print;
PyObject *const_str_plain_queue;
PyObject *const_str_plain_range;
PyObject *const_str_plain_shape;
PyObject *const_str_plain_sound;
PyObject *const_str_plain_split;
PyObject *const_str_plain_throw;
PyObject *const_str_plain_tuple;
PyObject *const_str_plain_types;
PyObject *const_str_plain_value;
PyObject *const_str_plain_width;
PyObject *const_str_plain_win32;
PyObject *const_str_angle_lambda;
PyObject *const_str_plain_append;
PyObject *const_str_plain_bytes_;
PyObject *const_str_plain_decode;
PyObject *const_str_plain_encode;
PyObject *const_str_plain_exists;
PyObject *const_str_plain_filter;
PyObject *const_str_plain_format;
PyObject *const_str_plain_frozen;
PyObject *const_str_plain_getcwd;
PyObject *const_str_plain_height;
PyObject *const_str_plain_italic;
PyObject *const_str_plain_kwargs;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_object;
PyObject *const_str_plain_pickle;
PyObject *const_str_plain_pygame;
PyObject *const_str_plain_remove;
PyObject *const_str_plain_result;
PyObject *const_str_plain_sprite;
PyObject *const_str_plain_stdout;
PyObject *const_str_plain_strict;
PyObject *const_str_plain_target;
PyObject *const_str_plain_thread;
PyObject *const_str_plain_unichr;
PyObject *const_str_plain_update;
PyObject *const_str_plain_values;
PyObject *const_str_plain_winreg;
PyObject *const_str_plain_xrange;
PyObject *const_tuple_none_tuple;
PyObject *const_tuple_true_tuple;
PyObject *const_str_angle_genexpr;
PyObject *const_str_plain_BytesIO;
PyObject *const_str_plain_OpenKey;
PyObject *const_str_plain_Surface;
PyObject *const_str_plain_SysFont;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain___len__;
PyObject *const_str_plain__winreg;
PyObject *const_str_plain_array2d;
PyObject *const_str_plain_array3d;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_copyreg;
PyObject *const_str_plain_diamond;
PyObject *const_str_plain_dirname;
PyObject *const_str_plain_display;
PyObject *const_str_plain_environ;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_modules;
PyObject *const_str_plain_oblique;
PyObject *const_str_plain_old_mod;
PyObject *const_str_plain_replace;
PyObject *const_str_plain_samples;
PyObject *const_str_plain_surface;
PyObject *const_str_plain_unicode;
PyObject *const_str_plain_xrange_;
PyObject *const_tuple_int_0_tuple;
PyObject *const_str_angle_listcomp;
PyObject *const_str_plain_StringIO;
PyObject *const_str_plain___call__;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain___spec__;
PyObject *const_str_plain_as_bytes;
PyObject *const_str_plain_basename;
PyObject *const_str_plain_callable;
PyObject *const_str_plain_copy_reg;
PyObject *const_str_plain_exc_info;
PyObject *const_str_plain_filename;
PyObject *const_str_plain_fontpath;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_get_rect;
PyObject *const_str_plain_geterror;
PyObject *const_str_plain_operator;
PyObject *const_str_plain_pixels2d;
PyObject *const_str_plain_pixels3d;
PyObject *const_str_plain_platform;
PyObject *const_str_plain_set_bold;
PyObject *const_str_plain_splitext;
PyObject *const_str_plain_unicode_;
PyObject *const_str_plain_win32com;
PyObject *const_str_angle_metaclass;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___debug__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain_arraytype;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_cStringIO;
PyObject *const_str_plain_get_fonts;
PyObject *const_str_plain_itertools;
PyObject *const_str_plain_map_array;
PyObject *const_str_plain_metaclass;
PyObject *const_str_plain_pythoncom;
PyObject *const_str_plain_raw_input;
PyObject *const_str_plain_transform;
PyObject *const_str_plain___author__;
PyObject *const_str_plain___cached__;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___loader__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain_as_unicode;
PyObject *const_str_plain_blit_array;
PyObject *const_str_plain_make_sound;
PyObject *const_str_plain_match_font;
PyObject *const_str_plain_pixels_red;
PyObject *const_str_plain_pywintypes;
PyObject *const_str_plain_set_italic;
PyObject *const_str_plain_startswith;
PyObject *const_str_plain_subprocess;
PyObject *const_str_plain___getattr__;
PyObject *const_str_plain___getitem__;
PyObject *const_str_plain___nonzero__;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___prepare__;
PyObject *const_str_plain___version__;
PyObject *const_str_plain_array_alpha;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_constructor;
PyObject *const_str_plain_getResource;
PyObject *const_str_plain_get_BytesIO;
PyObject *const_str_plain_load_module;
PyObject *const_str_plain_pixels_blue;
PyObject *const_tuple_int_pos_1_tuple;
PyObject *const_tuple_none_none_tuple;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___internal__;
PyObject *const_str_plain___qualname__;
PyObject *const_str_plain_make_surface;
PyObject *const_str_plain_pixels_alpha;
PyObject *const_str_plain_pixels_green;
PyObject *const_str_plain_staticmethod;
PyObject *const_str_plain_version_info;
PyObject *const_tuple_str_chr_42_tuple;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain__initializing;
PyObject *const_str_plain_get_arraytype;
PyObject *const_str_plain_use_arraytype;
PyObject *const_tuple_int_0_int_0_tuple;
PyObject *const_tuple_str_newline_tuple;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_plain___orig_bases__;
PyObject *const_str_plain_array_colorkey;
PyObject *const_str_plain_get_arraytypes;
PyObject *const_str_plain_unicode_escape;
PyObject *const_slice_none_int_pos_2_none;
PyObject *const_str_plain___mro_entries__;
PyObject *const_tuple_str_plain_obj_tuple;
PyObject *const_slice_int_0_int_pos_2_none;
PyObject *const_str_plain_PY_MAJOR_VERSION;
PyObject *const_str_plain_array_to_surface;
PyObject *const_str_plain_encode_file_path;
PyObject *const_tuple_str_plain_Rect_tuple;
PyObject *const_tuple_str_plain_name_tuple;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_str_plain___class_getitem__;
PyObject *const_str_plain_getwindowsversion;
PyObject *const_tuple_str_plain_array_tuple;
PyObject *const_tuple_str_plain_numpy_tuple;
PyObject *const_tuple_str_plain_sound_tuple;
PyObject *const_str_plain_HKEY_LOCAL_MACHINE;
PyObject *const_tuple_str_plain_surface_tuple;
PyObject *const_tuple_int_pos_3_int_pos_3_tuple;
PyObject *const_tuple_str_plain___class___tuple;
PyObject *const_tuple_str_plain_arraytype_tuple;
PyObject *const_dict_a7ab110deec347786bcfa718065f5388;
PyObject *const_str_plain___PackageSupportBuildPath__;
PyObject *const_tuple_str_plain_self_str_plain_args_tuple;
PyObject *const_str_plain___import_pywin32_system_module__;
PyObject *const_tuple_str_plain_self_str_plain_value_tuple;
PyObject *const_str_digest_0652bb03f90c2cca6cd14fe6735986b2;
PyObject *const_str_digest_09071ce7627c997b2ddfbec9a930c08b;
PyObject *const_str_digest_11bb5f146c38d7c06053353ff65da84a;
PyObject *const_str_digest_18565fc6928515f154561cd2cc076c49;
PyObject *const_str_digest_1ef86d6d9cfb907791755ff131616348;
PyObject *const_str_digest_252c7dce96687f8919bf3c3a90e1690f;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_311cff636bc9fe2337ef6b561e3a7fa9;
PyObject *const_str_digest_390dcb68817636bbd0641245b5f96e70;
PyObject *const_str_digest_397a17452f1c53e6ae5af26f0cec775b;
PyObject *const_str_digest_436e7eb61b35d39994d896416c082efa;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_60ac2b0d0530324399922e9b4f074c7a;
PyObject *const_str_digest_62b7e67e29e99420603c12d205222fa5;
PyObject *const_str_digest_672366ed1fcc7aba1730c8c9e9e92aea;
PyObject *const_str_digest_749448536aec7c722f6b23d71bbbb4b1;
PyObject *const_str_digest_75fd71b1edada749c2ef7ac810062295;
PyObject *const_str_digest_7b06e36aa54006877c6dbd4046f3d7da;
PyObject *const_str_digest_80672e58a7263f3bf64f5274ab7b87ec;
PyObject *const_str_digest_86c7bb6b17330427d0fab757eb020984;
PyObject *const_str_digest_886429de8fdd53f8d5c9561510a627a3;
PyObject *const_str_digest_9816e8d1552296af90d250823c964059;
PyObject *const_str_digest_a9c9058b24a02dd5e800ad5af29701ac;
PyObject *const_str_digest_adc474dd61fbd736d69c1bac5d9712e0;
PyObject *const_str_digest_b010b74deac075981c5003854bdfd1a6;
PyObject *const_str_digest_b2e0d613f6b2aca091d775f4312aede2;
PyObject *const_str_digest_b646956a0fd89f2f0ee5168bcdb2f2b8;
PyObject *const_str_digest_b9c4baf879ebd882d40843df3a4dead7;
PyObject *const_str_digest_be0c58c5fcf712145ccaf4e61ea24ef9;
PyObject *const_str_digest_c075052d723d6707083e869a0e3659bb;
PyObject *const_str_digest_d174e39ef12748481d2d13702313aa6c;
PyObject *const_str_digest_d90ff4b5f2bc9a4d934872fe1164b3ec;
PyObject *const_str_digest_df4bac290232ff9f319b12d3d498971c;
PyObject *const_str_digest_e420c3319159a1e6d3a583b2fbaf6bd0;
PyObject *const_str_digest_ec33b54dbd13f5c2292ba451b0640cb1;
PyObject *const_str_digest_f8b7823bdfb14e2c4cbd75b5ca5fd166;
PyObject *const_tuple_str_plain_surface_str_plain_array_tuple;
PyObject *const_tuple_anon_function_anon_builtin_function_or_method_tuple;
PyObject *const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple;

static void _createGlobalConstants( void )
{
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyLong_FromUnsignedLong( 0ul );
    const_str_dot = UNSTREAM_STRING( &constant_bin[ 35 ], 1, 0 );
    const_float_0_5 = UNSTREAM_FLOAT( &constant_bin[ 95458 ] );
    const_int_neg_1 = PyLong_FromLong( -1l );
    const_int_pos_1 = PyLong_FromUnsignedLong( 1ul );
    const_int_pos_2 = PyLong_FromUnsignedLong( 2ul );
    const_int_pos_3 = PyLong_FromUnsignedLong( 3ul );
    const_int_pos_4 = PyLong_FromUnsignedLong( 4ul );
    const_int_pos_5 = PyLong_FromUnsignedLong( 5ul );
    const_int_pos_8 = PyLong_FromUnsignedLong( 8ul );
    const_str_empty = UNSTREAM_STRING( &constant_bin[ 0 ], 0, 0 );
    const_str_space = UNSTREAM_STRING( &constant_bin[ 424 ], 1, 0 );
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert( PyDict_Size( const_dict_empty ) == 0 );
    const_int_pos_10 = PyLong_FromUnsignedLong( 10ul );
    const_int_pos_16 = PyLong_FromUnsignedLong( 16ul );
    const_int_pos_32 = PyLong_FromUnsignedLong( 32ul );
    const_str_chr_42 = UNSTREAM_STRING( &constant_bin[ 14670 ], 1, 0 );
    const_str_chr_44 = UNSTREAM_STRING( &constant_bin[ 3148 ], 1, 0 );
    const_bytes_empty = UNSTREAM_BYTES( &constant_bin[ 0 ], 0 );
    const_str_newline = UNSTREAM_STRING( &constant_bin[ 1999 ], 1, 0 );
    const_str_plain_X = UNSTREAM_STRING( &constant_bin[ 865 ], 1, 1 );
    const_str_plain__ = UNSTREAM_STRING( &constant_bin[ 39 ], 1, 1 );
    const_str_plain_b = UNSTREAM_STRING( &constant_bin[ 45 ], 1, 1 );
    const_str_plain_c = UNSTREAM_STRING( &constant_bin[ 14 ], 1, 1 );
    const_str_plain_f = UNSTREAM_STRING( &constant_bin[ 74 ], 1, 1 );
    const_str_plain_h = UNSTREAM_STRING( &constant_bin[ 50 ], 1, 1 );
    const_str_plain_i = UNSTREAM_STRING( &constant_bin[ 13 ], 1, 1 );
    const_str_plain_o = UNSTREAM_STRING( &constant_bin[ 9 ], 1, 1 );
    const_str_plain_r = UNSTREAM_STRING( &constant_bin[ 0 ], 1, 1 );
    const_str_plain_s = UNSTREAM_STRING( &constant_bin[ 12 ], 1, 1 );
    const_str_plain_u = UNSTREAM_STRING( &constant_bin[ 65 ], 1, 1 );
    const_str_plain_w = UNSTREAM_STRING( &constant_bin[ 36 ], 1, 1 );
    const_str_plain_x = UNSTREAM_STRING( &constant_bin[ 10 ], 1, 1 );
    const_str_plain_y = UNSTREAM_STRING( &constant_bin[ 18 ], 1, 1 );
    const_tuple_empty = PyTuple_New( 0 );
    const_str_plain_io = UNSTREAM_STRING( &constant_bin[ 161 ], 2, 1 );
    const_str_plain_nt = UNSTREAM_STRING( &constant_bin[ 236 ], 2, 1 );
    const_str_plain_os = UNSTREAM_STRING( &constant_bin[ 1694 ], 2, 1 );
    const_str_plain_rb = UNSTREAM_STRING( &constant_bin[ 16044 ], 2, 1 );
    const_str_plain_chr = UNSTREAM_STRING( &constant_bin[ 34648 ], 3, 1 );
    const_str_plain_doc = UNSTREAM_STRING( &constant_bin[ 48102 ], 3, 1 );
    const_str_plain_end = UNSTREAM_STRING( &constant_bin[ 4506 ], 3, 1 );
    const_str_plain_get = UNSTREAM_STRING( &constant_bin[ 258 ], 3, 1 );
    const_str_plain_imp = UNSTREAM_STRING( &constant_bin[ 1892 ], 3, 1 );
    const_str_plain_int = UNSTREAM_STRING( &constant_bin[ 627 ], 3, 1 );
    const_str_plain_key = UNSTREAM_STRING( &constant_bin[ 1678 ], 3, 1 );
    const_str_plain_len = UNSTREAM_STRING( &constant_bin[ 1754 ], 3, 1 );
    const_str_plain_map = UNSTREAM_STRING( &constant_bin[ 7846 ], 3, 1 );
    const_str_plain_mod = UNSTREAM_STRING( &constant_bin[ 1363 ], 3, 1 );
    const_str_plain_obj = UNSTREAM_STRING( &constant_bin[ 3246 ], 3, 1 );
    const_str_plain_pop = UNSTREAM_STRING( &constant_bin[ 95466 ], 3, 1 );
    const_str_plain_pos = UNSTREAM_STRING( &constant_bin[ 52213 ], 3, 1 );
    const_str_plain_str = UNSTREAM_STRING( &constant_bin[ 1632 ], 3, 1 );
    const_str_plain_sum = UNSTREAM_STRING( &constant_bin[ 95469 ], 3, 1 );
    const_str_plain_sys = UNSTREAM_STRING( &constant_bin[ 3280 ], 3, 1 );
    const_str_plain_val = UNSTREAM_STRING( &constant_bin[ 1517 ], 3, 1 );
    const_str_plain_ver = UNSTREAM_STRING( &constant_bin[ 147 ], 3, 1 );
    const_str_plain_Font = UNSTREAM_STRING( &constant_bin[ 40489 ], 4, 1 );
    const_str_plain_None = UNSTREAM_STRING( &constant_bin[ 40819 ], 4, 1 );
    const_str_plain_Rect = UNSTREAM_STRING( &constant_bin[ 1064 ], 4, 1 );
    const_str_plain_args = UNSTREAM_STRING( &constant_bin[ 39444 ], 4, 1 );
    const_str_plain_argv = UNSTREAM_STRING( &constant_bin[ 95472 ], 4, 1 );
    const_str_plain_bold = UNSTREAM_STRING( &constant_bin[ 40359 ], 4, 1 );
    const_str_plain_copy = UNSTREAM_STRING( &constant_bin[ 3329 ], 4, 1 );
    const_str_plain_data = UNSTREAM_STRING( &constant_bin[ 4051 ], 4, 1 );
    const_str_plain_dict = UNSTREAM_STRING( &constant_bin[ 13179 ], 4, 1 );
    const_str_plain_draw = UNSTREAM_STRING( &constant_bin[ 773 ], 4, 1 );
    const_str_plain_file = UNSTREAM_STRING( &constant_bin[ 1947 ], 4, 1 );
    const_str_plain_font = UNSTREAM_STRING( &constant_bin[ 3283 ], 4, 1 );
    const_str_plain_imap = UNSTREAM_STRING( &constant_bin[ 34657 ], 4, 1 );
    const_str_plain_info = UNSTREAM_STRING( &constant_bin[ 62038 ], 4, 1 );
    const_str_plain_init = UNSTREAM_STRING( &constant_bin[ 1126 ], 4, 1 );
    const_str_plain_iter = UNSTREAM_STRING( &constant_bin[ 34675 ], 4, 1 );
    const_str_plain_join = UNSTREAM_STRING( &constant_bin[ 45079 ], 4, 1 );
    const_str_plain_keys = UNSTREAM_STRING( &constant_bin[ 87575 ], 4, 1 );
    const_str_plain_left = UNSTREAM_STRING( &constant_bin[ 118 ], 4, 1 );
    const_str_plain_line = UNSTREAM_STRING( &constant_bin[ 1469 ], 4, 1 );
    const_str_plain_long = UNSTREAM_STRING( &constant_bin[ 10417 ], 4, 1 );
    const_str_plain_mask = UNSTREAM_STRING( &constant_bin[ 38851 ], 4, 1 );
    const_str_plain_name = UNSTREAM_STRING( &constant_bin[ 6776 ], 4, 1 );
    const_str_plain_next = UNSTREAM_STRING( &constant_bin[ 34652 ], 4, 1 );
    const_str_plain_open = UNSTREAM_STRING( &constant_bin[ 80744 ], 4, 1 );
    const_str_plain_path = UNSTREAM_STRING( &constant_bin[ 1907 ], 4, 1 );
    const_str_plain_quit = UNSTREAM_STRING( &constant_bin[ 95476 ], 4, 1 );
    const_str_plain_read = UNSTREAM_STRING( &constant_bin[ 2570 ], 4, 1 );
    const_str_plain_rect = UNSTREAM_STRING( &constant_bin[ 1702 ], 4, 1 );
    const_str_plain_repr = UNSTREAM_STRING( &constant_bin[ 9471 ], 4, 1 );
    const_str_plain_self = UNSTREAM_STRING( &constant_bin[ 52788 ], 4, 1 );
    const_str_plain_send = UNSTREAM_STRING( &constant_bin[ 95480 ], 4, 1 );
    const_str_plain_site = UNSTREAM_STRING( &constant_bin[ 1780 ], 4, 1 );
    const_str_plain_size = UNSTREAM_STRING( &constant_bin[ 5010 ], 4, 1 );
    const_str_plain_time = UNSTREAM_STRING( &constant_bin[ 2545 ], 4, 1 );
    const_str_plain_type = UNSTREAM_STRING( &constant_bin[ 5544 ], 4, 1 );
    const_str_plain_wait = UNSTREAM_STRING( &constant_bin[ 83880 ], 4, 1 );
    const_str_plain_Close = UNSTREAM_STRING( &constant_bin[ 95484 ], 5, 1 );
    const_str_plain_Color = UNSTREAM_STRING( &constant_bin[ 704 ], 5, 1 );
    const_str_plain_False = UNSTREAM_STRING( &constant_bin[ 41065 ], 5, 1 );
    const_str_plain_Queue = UNSTREAM_STRING( &constant_bin[ 83930 ], 5, 1 );
    const_str_plain_array = UNSTREAM_STRING( &constant_bin[ 2462 ], 5, 1 );
    const_str_plain_ascii = UNSTREAM_STRING( &constant_bin[ 83253 ], 5, 1 );
    const_str_plain_bytes = UNSTREAM_STRING( &constant_bin[ 6864 ], 5, 1 );
    const_str_plain_close = UNSTREAM_STRING( &constant_bin[ 66083 ], 5, 1 );
    const_str_plain_color = UNSTREAM_STRING( &constant_bin[ 677 ], 5, 1 );
    const_str_plain_empty = UNSTREAM_STRING( &constant_bin[ 6786 ], 5, 1 );
    const_str_plain_error = UNSTREAM_STRING( &constant_bin[ 34732 ], 5, 1 );
    const_str_plain_event = UNSTREAM_STRING( &constant_bin[ 1620 ], 5, 1 );
    const_str_plain_found = UNSTREAM_STRING( &constant_bin[ 41514 ], 5, 1 );
    const_str_plain_image = UNSTREAM_STRING( &constant_bin[ 2134 ], 5, 1 );
    const_str_plain_input = UNSTREAM_STRING( &constant_bin[ 34609 ], 5, 1 );
    const_str_plain_items = UNSTREAM_STRING( &constant_bin[ 88202 ], 5, 1 );
    const_str_plain_level = UNSTREAM_STRING( &constant_bin[ 95489 ], 5, 1 );
    const_str_plain_lower = UNSTREAM_STRING( &constant_bin[ 16884 ], 5, 1 );
    const_str_plain_mixer = UNSTREAM_STRING( &constant_bin[ 2729 ], 5, 1 );
    const_str_plain_numpy = UNSTREAM_STRING( &constant_bin[ 3440 ], 5, 1 );
    const_str_plain_print = UNSTREAM_STRING( &constant_bin[ 89187 ], 5, 1 );
    const_str_plain_queue = UNSTREAM_STRING( &constant_bin[ 83942 ], 5, 1 );
    const_str_plain_range = UNSTREAM_STRING( &constant_bin[ 14404 ], 5, 1 );
    const_str_plain_shape = UNSTREAM_STRING( &constant_bin[ 404 ], 5, 1 );
    const_str_plain_sound = UNSTREAM_STRING( &constant_bin[ 3768 ], 5, 1 );
    const_str_plain_split = UNSTREAM_STRING( &constant_bin[ 225 ], 5, 1 );
    const_str_plain_throw = UNSTREAM_STRING( &constant_bin[ 95494 ], 5, 1 );
    const_str_plain_tuple = UNSTREAM_STRING( &constant_bin[ 39249 ], 5, 1 );
    const_str_plain_types = UNSTREAM_STRING( &constant_bin[ 9924 ], 5, 1 );
    const_str_plain_value = UNSTREAM_STRING( &constant_bin[ 4561 ], 5, 1 );
    const_str_plain_width = UNSTREAM_STRING( &constant_bin[ 39000 ], 5, 1 );
    const_str_plain_win32 = UNSTREAM_STRING( &constant_bin[ 80525 ], 5, 1 );
    const_str_angle_lambda = UNSTREAM_STRING( &constant_bin[ 59596 ], 8, 0 );
    const_str_plain_append = UNSTREAM_STRING( &constant_bin[ 49826 ], 6, 1 );
    const_str_plain_bytes_ = UNSTREAM_STRING( &constant_bin[ 92991 ], 6, 1 );
    const_str_plain_decode = UNSTREAM_STRING( &constant_bin[ 95499 ], 6, 1 );
    const_str_plain_encode = UNSTREAM_STRING( &constant_bin[ 1625 ], 6, 1 );
    const_str_plain_exists = UNSTREAM_STRING( &constant_bin[ 44630 ], 6, 1 );
    const_str_plain_filter = UNSTREAM_STRING( &constant_bin[ 91659 ], 6, 1 );
    const_str_plain_format = UNSTREAM_STRING( &constant_bin[ 3691 ], 6, 1 );
    const_str_plain_frozen = UNSTREAM_STRING( &constant_bin[ 87041 ], 6, 1 );
    const_str_plain_getcwd = UNSTREAM_STRING( &constant_bin[ 90496 ], 6, 1 );
    const_str_plain_height = UNSTREAM_STRING( &constant_bin[ 40601 ], 6, 1 );
    const_str_plain_italic = UNSTREAM_STRING( &constant_bin[ 41072 ], 6, 1 );
    const_str_plain_kwargs = UNSTREAM_STRING( &constant_bin[ 47917 ], 6, 1 );
    const_str_plain_locals = UNSTREAM_STRING( &constant_bin[ 40295 ], 6, 1 );
    const_str_plain_object = UNSTREAM_STRING( &constant_bin[ 3246 ], 6, 1 );
    const_str_plain_pickle = UNSTREAM_STRING( &constant_bin[ 95505 ], 6, 1 );
    const_str_plain_pygame = UNSTREAM_STRING( &constant_bin[ 1156 ], 6, 1 );
    const_str_plain_remove = UNSTREAM_STRING( &constant_bin[ 1724 ], 6, 1 );
    const_str_plain_result = UNSTREAM_STRING( &constant_bin[ 83767 ], 6, 1 );
    const_str_plain_sprite = UNSTREAM_STRING( &constant_bin[ 47886 ], 6, 1 );
    const_str_plain_stdout = UNSTREAM_STRING( &constant_bin[ 95511 ], 6, 1 );
    const_str_plain_strict = UNSTREAM_STRING( &constant_bin[ 95517 ], 6, 1 );
    const_str_plain_target = UNSTREAM_STRING( &constant_bin[ 95523 ], 6, 1 );
    const_str_plain_thread = UNSTREAM_STRING( &constant_bin[ 2568 ], 6, 1 );
    const_str_plain_unichr = UNSTREAM_STRING( &constant_bin[ 34645 ], 6, 1 );
    const_str_plain_update = UNSTREAM_STRING( &constant_bin[ 47651 ], 6, 1 );
    const_str_plain_values = UNSTREAM_STRING( &constant_bin[ 4561 ], 6, 1 );
    const_str_plain_winreg = UNSTREAM_STRING( &constant_bin[ 95529 ], 6, 1 );
    const_str_plain_xrange = UNSTREAM_STRING( &constant_bin[ 95535 ], 6, 1 );
    const_tuple_none_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    const_tuple_true_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_true_tuple, 0, Py_True ); Py_INCREF( Py_True );
    const_str_angle_genexpr = UNSTREAM_STRING( &constant_bin[ 81988 ], 9, 0 );
    const_str_plain_BytesIO = UNSTREAM_STRING( &constant_bin[ 95541 ], 7, 1 );
    const_str_plain_OpenKey = UNSTREAM_STRING( &constant_bin[ 94905 ], 7, 1 );
    const_str_plain_Surface = UNSTREAM_STRING( &constant_bin[ 5067 ], 7, 1 );
    const_str_plain_SysFont = UNSTREAM_STRING( &constant_bin[ 41040 ], 7, 1 );
    const_str_plain___all__ = UNSTREAM_STRING( &constant_bin[ 95548 ], 7, 1 );
    const_str_plain___cmp__ = UNSTREAM_STRING( &constant_bin[ 95555 ], 7, 1 );
    const_str_plain___doc__ = UNSTREAM_STRING( &constant_bin[ 95562 ], 7, 1 );
    const_str_plain___len__ = UNSTREAM_STRING( &constant_bin[ 64105 ], 7, 1 );
    const_str_plain__winreg = UNSTREAM_STRING( &constant_bin[ 95569 ], 7, 1 );
    const_str_plain_array2d = UNSTREAM_STRING( &constant_bin[ 10219 ], 7, 1 );
    const_str_plain_array3d = UNSTREAM_STRING( &constant_bin[ 10202 ], 7, 1 );
    const_str_plain_compile = UNSTREAM_STRING( &constant_bin[ 36172 ], 7, 1 );
    const_str_plain_copyreg = UNSTREAM_STRING( &constant_bin[ 95576 ], 7, 1 );
    const_str_plain_diamond = UNSTREAM_STRING( &constant_bin[ 36049 ], 7, 1 );
    const_str_plain_dirname = UNSTREAM_STRING( &constant_bin[ 45017 ], 7, 1 );
    const_str_plain_display = UNSTREAM_STRING( &constant_bin[ 3413 ], 7, 1 );
    const_str_plain_environ = UNSTREAM_STRING( &constant_bin[ 95583 ], 7, 1 );
    const_str_plain_globals = UNSTREAM_STRING( &constant_bin[ 87421 ], 7, 1 );
    const_str_plain_inspect = UNSTREAM_STRING( &constant_bin[ 95590 ], 7, 1 );
    const_str_plain_modules = UNSTREAM_STRING( &constant_bin[ 2936 ], 7, 1 );
    const_str_plain_oblique = UNSTREAM_STRING( &constant_bin[ 95597 ], 7, 1 );
    const_str_plain_old_mod = UNSTREAM_STRING( &constant_bin[ 95604 ], 7, 1 );
    const_str_plain_replace = UNSTREAM_STRING( &constant_bin[ 95611 ], 7, 1 );
    const_str_plain_samples = UNSTREAM_STRING( &constant_bin[ 3454 ], 7, 1 );
    const_str_plain_surface = UNSTREAM_STRING( &constant_bin[ 1664 ], 7, 1 );
    const_str_plain_unicode = UNSTREAM_STRING( &constant_bin[ 81502 ], 7, 1 );
    const_str_plain_xrange_ = UNSTREAM_STRING( &constant_bin[ 95618 ], 7, 1 );
    const_tuple_int_0_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    const_str_angle_listcomp = UNSTREAM_STRING( &constant_bin[ 95625 ], 10, 0 );
    const_str_plain_StringIO = UNSTREAM_STRING( &constant_bin[ 34749 ], 8, 1 );
    const_str_plain___call__ = UNSTREAM_STRING( &constant_bin[ 50630 ], 8, 1 );
    const_str_plain___dict__ = UNSTREAM_STRING( &constant_bin[ 95635 ], 8, 1 );
    const_str_plain___exit__ = UNSTREAM_STRING( &constant_bin[ 95643 ], 8, 1 );
    const_str_plain___file__ = UNSTREAM_STRING( &constant_bin[ 44706 ], 8, 1 );
    const_str_plain___init__ = UNSTREAM_STRING( &constant_bin[ 1124 ], 8, 1 );
    const_str_plain___iter__ = UNSTREAM_STRING( &constant_bin[ 71600 ], 8, 1 );
    const_str_plain___main__ = UNSTREAM_STRING( &constant_bin[ 95651 ], 8, 1 );
    const_str_plain___name__ = UNSTREAM_STRING( &constant_bin[ 44980 ], 8, 1 );
    const_str_plain___path__ = UNSTREAM_STRING( &constant_bin[ 95659 ], 8, 1 );
    const_str_plain___spec__ = UNSTREAM_STRING( &constant_bin[ 95667 ], 8, 1 );
    const_str_plain_as_bytes = UNSTREAM_STRING( &constant_bin[ 95675 ], 8, 1 );
    const_str_plain_basename = UNSTREAM_STRING( &constant_bin[ 95683 ], 8, 1 );
    const_str_plain_callable = UNSTREAM_STRING( &constant_bin[ 49864 ], 8, 1 );
    const_str_plain_copy_reg = UNSTREAM_STRING( &constant_bin[ 95691 ], 8, 1 );
    const_str_plain_exc_info = UNSTREAM_STRING( &constant_bin[ 95699 ], 8, 1 );
    const_str_plain_filename = UNSTREAM_STRING( &constant_bin[ 39526 ], 8, 1 );
    const_str_plain_fontpath = UNSTREAM_STRING( &constant_bin[ 41898 ], 8, 1 );
    const_str_plain_fromlist = UNSTREAM_STRING( &constant_bin[ 95707 ], 8, 1 );
    const_str_plain_get_rect = UNSTREAM_STRING( &constant_bin[ 95715 ], 8, 1 );
    const_str_plain_geterror = UNSTREAM_STRING( &constant_bin[ 95723 ], 8, 1 );
    const_str_plain_operator = UNSTREAM_STRING( &constant_bin[ 70641 ], 8, 1 );
    const_str_plain_pixels2d = UNSTREAM_STRING( &constant_bin[ 7915 ], 8, 1 );
    const_str_plain_pixels3d = UNSTREAM_STRING( &constant_bin[ 12233 ], 8, 1 );
    const_str_plain_platform = UNSTREAM_STRING( &constant_bin[ 95731 ], 8, 1 );
    const_str_plain_set_bold = UNSTREAM_STRING( &constant_bin[ 42402 ], 8, 1 );
    const_str_plain_splitext = UNSTREAM_STRING( &constant_bin[ 95739 ], 8, 1 );
    const_str_plain_unicode_ = UNSTREAM_STRING( &constant_bin[ 88217 ], 8, 1 );
    const_str_plain_win32com = UNSTREAM_STRING( &constant_bin[ 94810 ], 8, 1 );
    const_str_angle_metaclass = UNSTREAM_STRING( &constant_bin[ 95747 ], 11, 0 );
    const_str_plain___class__ = UNSTREAM_STRING( &constant_bin[ 95758 ], 9, 1 );
    const_str_plain___debug__ = UNSTREAM_STRING( &constant_bin[ 95767 ], 9, 1 );
    const_str_plain___enter__ = UNSTREAM_STRING( &constant_bin[ 95776 ], 9, 1 );
    const_str_plain_arraytype = UNSTREAM_STRING( &constant_bin[ 45356 ], 9, 1 );
    const_str_plain_bytearray = UNSTREAM_STRING( &constant_bin[ 95785 ], 9, 1 );
    const_str_plain_cStringIO = UNSTREAM_STRING( &constant_bin[ 95794 ], 9, 1 );
    const_str_plain_get_fonts = UNSTREAM_STRING( &constant_bin[ 81189 ], 9, 1 );
    const_str_plain_itertools = UNSTREAM_STRING( &constant_bin[ 95803 ], 9, 1 );
    const_str_plain_map_array = UNSTREAM_STRING( &constant_bin[ 7846 ], 9, 1 );
    const_str_plain_metaclass = UNSTREAM_STRING( &constant_bin[ 88780 ], 9, 1 );
    const_str_plain_pythoncom = UNSTREAM_STRING( &constant_bin[ 86948 ], 9, 1 );
    const_str_plain_raw_input = UNSTREAM_STRING( &constant_bin[ 34605 ], 9, 1 );
    const_str_plain_transform = UNSTREAM_STRING( &constant_bin[ 95812 ], 9, 1 );
    const_str_plain___author__ = UNSTREAM_STRING( &constant_bin[ 95821 ], 10, 1 );
    const_str_plain___cached__ = UNSTREAM_STRING( &constant_bin[ 95831 ], 10, 1 );
    const_str_plain___import__ = UNSTREAM_STRING( &constant_bin[ 95841 ], 10, 1 );
    const_str_plain___loader__ = UNSTREAM_STRING( &constant_bin[ 45168 ], 10, 1 );
    const_str_plain___module__ = UNSTREAM_STRING( &constant_bin[ 95851 ], 10, 1 );
    const_str_plain_as_unicode = UNSTREAM_STRING( &constant_bin[ 95861 ], 10, 1 );
    const_str_plain_blit_array = UNSTREAM_STRING( &constant_bin[ 95871 ], 10, 1 );
    const_str_plain_make_sound = UNSTREAM_STRING( &constant_bin[ 3763 ], 10, 1 );
    const_str_plain_match_font = UNSTREAM_STRING( &constant_bin[ 80779 ], 10, 1 );
    const_str_plain_pixels_red = UNSTREAM_STRING( &constant_bin[ 6935 ], 10, 1 );
    const_str_plain_pywintypes = UNSTREAM_STRING( &constant_bin[ 87147 ], 10, 1 );
    const_str_plain_set_italic = UNSTREAM_STRING( &constant_bin[ 42558 ], 10, 1 );
    const_str_plain_startswith = UNSTREAM_STRING( &constant_bin[ 95881 ], 10, 1 );
    const_str_plain_subprocess = UNSTREAM_STRING( &constant_bin[ 95891 ], 10, 1 );
    const_str_plain___getattr__ = UNSTREAM_STRING( &constant_bin[ 2350 ], 11, 1 );
    const_str_plain___getitem__ = UNSTREAM_STRING( &constant_bin[ 95901 ], 11, 1 );
    const_str_plain___nonzero__ = UNSTREAM_STRING( &constant_bin[ 1814 ], 11, 1 );
    const_str_plain___package__ = UNSTREAM_STRING( &constant_bin[ 95912 ], 11, 1 );
    const_str_plain___prepare__ = UNSTREAM_STRING( &constant_bin[ 88809 ], 11, 1 );
    const_str_plain___version__ = UNSTREAM_STRING( &constant_bin[ 95923 ], 11, 1 );
    const_str_plain_array_alpha = UNSTREAM_STRING( &constant_bin[ 7383 ], 11, 1 );
    const_str_plain_classmethod = UNSTREAM_STRING( &constant_bin[ 95934 ], 11, 1 );
    const_str_plain_constructor = UNSTREAM_STRING( &constant_bin[ 2227 ], 11, 1 );
    const_str_plain_getResource = UNSTREAM_STRING( &constant_bin[ 44182 ], 11, 1 );
    const_str_plain_get_BytesIO = UNSTREAM_STRING( &constant_bin[ 95945 ], 11, 1 );
    const_str_plain_load_module = UNSTREAM_STRING( &constant_bin[ 92547 ], 11, 1 );
    const_str_plain_pixels_blue = UNSTREAM_STRING( &constant_bin[ 5932 ], 11, 1 );
    const_tuple_int_pos_1_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_tuple, 0, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    const_tuple_none_none_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_none_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_tuple, 1, Py_None ); Py_INCREF( Py_None );
    const_str_plain___builtins__ = UNSTREAM_STRING( &constant_bin[ 95956 ], 12, 1 );
    const_str_plain___internal__ = UNSTREAM_STRING( &constant_bin[ 95968 ], 12, 1 );
    const_str_plain___qualname__ = UNSTREAM_STRING( &constant_bin[ 95980 ], 12, 1 );
    const_str_plain_make_surface = UNSTREAM_STRING( &constant_bin[ 5024 ], 12, 1 );
    const_str_plain_pixels_alpha = UNSTREAM_STRING( &constant_bin[ 5054 ], 12, 1 );
    const_str_plain_pixels_green = UNSTREAM_STRING( &constant_bin[ 11742 ], 12, 1 );
    const_str_plain_staticmethod = UNSTREAM_STRING( &constant_bin[ 95992 ], 12, 1 );
    const_str_plain_version_info = UNSTREAM_STRING( &constant_bin[ 96004 ], 12, 1 );
    const_tuple_str_chr_42_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_chr_42_tuple, 0, const_str_chr_42 ); Py_INCREF( const_str_chr_42 );
    const_str_plain___metaclass__ = UNSTREAM_STRING( &constant_bin[ 96016 ], 13, 1 );
    const_str_plain__initializing = UNSTREAM_STRING( &constant_bin[ 96029 ], 13, 1 );
    const_str_plain_get_arraytype = UNSTREAM_STRING( &constant_bin[ 45769 ], 13, 1 );
    const_str_plain_use_arraytype = UNSTREAM_STRING( &constant_bin[ 45352 ], 13, 1 );
    const_tuple_int_0_int_0_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_tuple, 1, const_int_0 ); Py_INCREF( const_int_0 );
    const_tuple_str_newline_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_newline_tuple, 0, const_str_newline ); Py_INCREF( const_str_newline );
    const_tuple_type_object_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type ); Py_INCREF( (PyObject *)&PyBaseObject_Type );
    const_str_plain___orig_bases__ = UNSTREAM_STRING( &constant_bin[ 96042 ], 14, 1 );
    const_str_plain_array_colorkey = UNSTREAM_STRING( &constant_bin[ 8489 ], 14, 1 );
    const_str_plain_get_arraytypes = UNSTREAM_STRING( &constant_bin[ 47088 ], 14, 1 );
    const_str_plain_unicode_escape = UNSTREAM_STRING( &constant_bin[ 96056 ], 14, 1 );
    const_slice_none_int_pos_2_none = PySlice_New( Py_None, const_int_pos_2, Py_None );
    const_str_plain___mro_entries__ = UNSTREAM_STRING( &constant_bin[ 96070 ], 15, 1 );
    const_tuple_str_plain_obj_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_obj_tuple, 0, const_str_plain_obj ); Py_INCREF( const_str_plain_obj );
    const_slice_int_0_int_pos_2_none = PySlice_New( const_int_0, const_int_pos_2, Py_None );
    const_str_plain_PY_MAJOR_VERSION = UNSTREAM_STRING( &constant_bin[ 96085 ], 16, 1 );
    const_str_plain_array_to_surface = UNSTREAM_STRING( &constant_bin[ 96101 ], 16, 1 );
    const_str_plain_encode_file_path = UNSTREAM_STRING( &constant_bin[ 40495 ], 16, 1 );
    const_tuple_str_plain_Rect_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Rect_tuple, 0, const_str_plain_Rect ); Py_INCREF( const_str_plain_Rect );
    const_tuple_str_plain_name_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_name_tuple, 0, const_str_plain_name ); Py_INCREF( const_str_plain_name );
    const_tuple_str_plain_self_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    const_str_plain___class_getitem__ = UNSTREAM_STRING( &constant_bin[ 96117 ], 17, 1 );
    const_str_plain_getwindowsversion = UNSTREAM_STRING( &constant_bin[ 96134 ], 17, 1 );
    const_tuple_str_plain_array_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_array_tuple, 0, const_str_plain_array ); Py_INCREF( const_str_plain_array );
    const_tuple_str_plain_numpy_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_numpy_tuple, 0, const_str_plain_numpy ); Py_INCREF( const_str_plain_numpy );
    const_tuple_str_plain_sound_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_sound_tuple, 0, const_str_plain_sound ); Py_INCREF( const_str_plain_sound );
    const_str_plain_HKEY_LOCAL_MACHINE = UNSTREAM_STRING( &constant_bin[ 96151 ], 18, 1 );
    const_tuple_str_plain_surface_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_surface_tuple, 0, const_str_plain_surface ); Py_INCREF( const_str_plain_surface );
    const_tuple_int_pos_3_int_pos_3_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_pos_3_int_pos_3_tuple, 0, const_int_pos_3 ); Py_INCREF( const_int_pos_3 );
    PyTuple_SET_ITEM( const_tuple_int_pos_3_int_pos_3_tuple, 1, const_int_pos_3 ); Py_INCREF( const_int_pos_3 );
    const_tuple_str_plain___class___tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain___class___tuple, 0, const_str_plain___class__ ); Py_INCREF( const_str_plain___class__ );
    const_tuple_str_plain_arraytype_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_arraytype_tuple, 0, const_str_plain_arraytype ); Py_INCREF( const_str_plain_arraytype );
    const_dict_a7ab110deec347786bcfa718065f5388 = _PyDict_NewPresized( 1 );
    PyDict_SetItem( const_dict_a7ab110deec347786bcfa718065f5388, const_str_plain_copy, Py_False );
    assert( PyDict_Size( const_dict_a7ab110deec347786bcfa718065f5388 ) == 1 );
    const_str_plain___PackageSupportBuildPath__ = UNSTREAM_STRING( &constant_bin[ 96169 ], 27, 1 );
    const_tuple_str_plain_self_str_plain_args_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_tuple, 1, const_str_plain_args ); Py_INCREF( const_str_plain_args );
    const_str_plain___import_pywin32_system_module__ = UNSTREAM_STRING( &constant_bin[ 96196 ], 32, 1 );
    const_tuple_str_plain_self_str_plain_value_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_value_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_value_tuple, 1, const_str_plain_value ); Py_INCREF( const_str_plain_value );
    const_str_digest_0652bb03f90c2cca6cd14fe6735986b2 = UNSTREAM_STRING( &constant_bin[ 96228 ], 11, 0 );
    const_str_digest_09071ce7627c997b2ddfbec9a930c08b = UNSTREAM_STRING( &constant_bin[ 80674 ], 14, 0 );
    const_str_digest_11bb5f146c38d7c06053353ff65da84a = UNSTREAM_STRING( &constant_bin[ 80767 ], 11, 0 );
    const_str_digest_18565fc6928515f154561cd2cc076c49 = UNSTREAM_STRING( &constant_bin[ 96239 ], 16, 0 );
    const_str_digest_1ef86d6d9cfb907791755ff131616348 = UNSTREAM_STRING( &constant_bin[ 47879 ], 13, 0 );
    const_str_digest_252c7dce96687f8919bf3c3a90e1690f = UNSTREAM_STRING( &constant_bin[ 43501 ], 13, 0 );
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING( &constant_bin[ 3733 ], 2, 0 );
    const_str_digest_311cff636bc9fe2337ef6b561e3a7fa9 = UNSTREAM_STRING( &constant_bin[ 34511 ], 13, 0 );
    const_str_digest_390dcb68817636bbd0641245b5f96e70 = UNSTREAM_STRING( &constant_bin[ 96255 ], 18, 0 );
    const_str_digest_397a17452f1c53e6ae5af26f0cec775b = UNSTREAM_STRING( &constant_bin[ 45336 ], 15, 0 );
    const_str_digest_436e7eb61b35d39994d896416c082efa = UNSTREAM_STRING( &constant_bin[ 35981 ], 14, 0 );
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING( &constant_bin[ 3603 ], 7, 0 );
    const_str_digest_60ac2b0d0530324399922e9b4f074c7a = UNSTREAM_STRING( &constant_bin[ 44591 ], 14, 0 );
    const_str_digest_62b7e67e29e99420603c12d205222fa5 = UNSTREAM_STRING( &constant_bin[ 96273 ], 7, 0 );
    const_str_digest_672366ed1fcc7aba1730c8c9e9e92aea = UNSTREAM_STRING( &constant_bin[ 3432 ], 21, 0 );
    const_str_digest_749448536aec7c722f6b23d71bbbb4b1 = UNSTREAM_STRING( &constant_bin[ 96280 ], 14, 0 );
    const_str_digest_75fd71b1edada749c2ef7ac810062295 = UNSTREAM_STRING( &constant_bin[ 96294 ], 46, 0 );
    const_str_digest_7b06e36aa54006877c6dbd4046f3d7da = UNSTREAM_STRING( &constant_bin[ 96340 ], 487, 0 );
    const_str_digest_80672e58a7263f3bf64f5274ab7b87ec = UNSTREAM_STRING( &constant_bin[ 96827 ], 11, 0 );
    const_str_digest_86c7bb6b17330427d0fab757eb020984 = UNSTREAM_STRING( &constant_bin[ 96838 ], 11, 0 );
    const_str_digest_886429de8fdd53f8d5c9561510a627a3 = UNSTREAM_STRING( &constant_bin[ 40888 ], 13, 0 );
    const_str_digest_9816e8d1552296af90d250823c964059 = UNSTREAM_STRING( &constant_bin[ 96849 ], 46, 0 );
    const_str_digest_a9c9058b24a02dd5e800ad5af29701ac = UNSTREAM_STRING( &constant_bin[ 13167 ], 12, 0 );
    const_str_digest_adc474dd61fbd736d69c1bac5d9712e0 = UNSTREAM_STRING( &constant_bin[ 96895 ], 47, 0 );
    const_str_digest_b010b74deac075981c5003854bdfd1a6 = UNSTREAM_STRING( &constant_bin[ 8971 ], 22, 0 );
    const_str_digest_b2e0d613f6b2aca091d775f4312aede2 = UNSTREAM_STRING( &constant_bin[ 85965 ], 14, 0 );
    const_str_digest_b646956a0fd89f2f0ee5168bcdb2f2b8 = UNSTREAM_STRING( &constant_bin[ 43782 ], 13, 0 );
    const_str_digest_b9c4baf879ebd882d40843df3a4dead7 = UNSTREAM_STRING( &constant_bin[ 47551 ], 2, 1 );
    const_str_digest_be0c58c5fcf712145ccaf4e61ea24ef9 = UNSTREAM_STRING( &constant_bin[ 96942 ], 236, 0 );
    const_str_digest_c075052d723d6707083e869a0e3659bb = UNSTREAM_STRING( &constant_bin[ 97178 ], 5, 0 );
    const_str_digest_d174e39ef12748481d2d13702313aa6c = UNSTREAM_STRING( &constant_bin[ 5915 ], 16, 0 );
    const_str_digest_d90ff4b5f2bc9a4d934872fe1164b3ec = UNSTREAM_STRING( &constant_bin[ 97183 ], 64, 0 );
    const_str_digest_df4bac290232ff9f319b12d3d498971c = UNSTREAM_STRING( &constant_bin[ 13167 ], 16, 0 );
    const_str_digest_e420c3319159a1e6d3a583b2fbaf6bd0 = UNSTREAM_STRING( &constant_bin[ 97247 ], 16, 0 );
    const_str_digest_ec33b54dbd13f5c2292ba451b0640cb1 = UNSTREAM_STRING( &constant_bin[ 97263 ], 16, 0 );
    const_str_digest_f8b7823bdfb14e2c4cbd75b5ca5fd166 = UNSTREAM_STRING( &constant_bin[ 2722 ], 12, 0 );
    const_tuple_str_plain_surface_str_plain_array_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_surface_str_plain_array_tuple, 0, const_str_plain_surface ); Py_INCREF( const_str_plain_surface );
    PyTuple_SET_ITEM( const_tuple_str_plain_surface_str_plain_array_tuple, 1, const_str_plain_array ); Py_INCREF( const_str_plain_array );
    const_tuple_anon_function_anon_builtin_function_or_method_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_anon_function_anon_builtin_function_or_method_tuple, 0, (PyObject *)&PyFunction_Type ); Py_INCREF( (PyObject *)&PyFunction_Type );
    PyTuple_SET_ITEM( const_tuple_anon_function_anon_builtin_function_or_method_tuple, 1, (PyObject *)&PyCFunction_Type ); Py_INCREF( (PyObject *)&PyCFunction_Type );
    const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 1, const_str_plain_args ); Py_INCREF( const_str_plain_args );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 2, const_str_plain_kwargs ); Py_INCREF( const_str_plain_kwargs );

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_d90ff4b5f2bc9a4d934872fe1164b3ec
    );
#endif
}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants( void )
{

}
#endif

void createGlobalConstants( void )
{
    if ( _sentinel_value == NULL )
    {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr( NULL, NULL );
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New( (void *)27, "sentinel", NULL );
#endif
        assert( _sentinel_value );

        _createGlobalConstants();
    }
}
